// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2025-2026 lin-snow

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package echomock

import (
	"context"

	model0 "github.com/lin-snow/ech0/internal/model/common"
	"github.com/lin-snow/ech0/internal/model/echo"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreateTag provides a mock function for the type MockService
func (_mock *MockService) CreateTag(ctx context.Context, name string) (*model.Tag, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for CreateTag")
	}

	var r0 *model.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Tag, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Tag); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_CreateTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTag'
type MockService_CreateTag_Call struct {
	*mock.Call
}

// CreateTag is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockService_Expecter) CreateTag(ctx any, name any) *MockService_CreateTag_Call {
	return &MockService_CreateTag_Call{Call: _e.mock.On("CreateTag", ctx, name)}
}

func (_c *MockService_CreateTag_Call) Run(run func(ctx context.Context, name string)) *MockService_CreateTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_CreateTag_Call) Return(tag *model.Tag, err error) *MockService_CreateTag_Call {
	_c.Call.Return(tag, err)
	return _c
}

func (_c *MockService_CreateTag_Call) RunAndReturn(run func(ctx context.Context, name string) (*model.Tag, error)) *MockService_CreateTag_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEchoById provides a mock function for the type MockService
func (_mock *MockService) DeleteEchoById(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEchoById")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteEchoById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEchoById'
type MockService_DeleteEchoById_Call struct {
	*mock.Call
}

// DeleteEchoById is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockService_Expecter) DeleteEchoById(ctx any, id any) *MockService_DeleteEchoById_Call {
	return &MockService_DeleteEchoById_Call{Call: _e.mock.On("DeleteEchoById", ctx, id)}
}

func (_c *MockService_DeleteEchoById_Call) Run(run func(ctx context.Context, id string)) *MockService_DeleteEchoById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_DeleteEchoById_Call) Return(err error) *MockService_DeleteEchoById_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteEchoById_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockService_DeleteEchoById_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTag provides a mock function for the type MockService
func (_mock *MockService) DeleteTag(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTag")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTag'
type MockService_DeleteTag_Call struct {
	*mock.Call
}

// DeleteTag is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockService_Expecter) DeleteTag(ctx any, id any) *MockService_DeleteTag_Call {
	return &MockService_DeleteTag_Call{Call: _e.mock.On("DeleteTag", ctx, id)}
}

func (_c *MockService_DeleteTag_Call) Run(run func(ctx context.Context, id string)) *MockService_DeleteTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_DeleteTag_Call) Return(err error) *MockService_DeleteTag_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteTag_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockService_DeleteTag_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllTags provides a mock function for the type MockService
func (_mock *MockService) GetAllTags() ([]model.Tag, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllTags")
	}

	var r0 []model.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]model.Tag, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []model.Tag); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetAllTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllTags'
type MockService_GetAllTags_Call struct {
	*mock.Call
}

// GetAllTags is a helper method to define mock.On call
func (_e *MockService_Expecter) GetAllTags() *MockService_GetAllTags_Call {
	return &MockService_GetAllTags_Call{Call: _e.mock.On("GetAllTags")}
}

func (_c *MockService_GetAllTags_Call) Run(run func()) *MockService_GetAllTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_GetAllTags_Call) Return(tags []model.Tag, err error) *MockService_GetAllTags_Call {
	_c.Call.Return(tags, err)
	return _c
}

func (_c *MockService_GetAllTags_Call) RunAndReturn(run func() ([]model.Tag, error)) *MockService_GetAllTags_Call {
	_c.Call.Return(run)
	return _c
}

// GetEchoById provides a mock function for the type MockService
func (_mock *MockService) GetEchoById(ctx context.Context, id string) (*model.Echo, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetEchoById")
	}

	var r0 *model.Echo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Echo, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Echo); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Echo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetEchoById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEchoById'
type MockService_GetEchoById_Call struct {
	*mock.Call
}

// GetEchoById is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockService_Expecter) GetEchoById(ctx any, id any) *MockService_GetEchoById_Call {
	return &MockService_GetEchoById_Call{Call: _e.mock.On("GetEchoById", ctx, id)}
}

func (_c *MockService_GetEchoById_Call) Run(run func(ctx context.Context, id string)) *MockService_GetEchoById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetEchoById_Call) Return(echo *model.Echo, err error) *MockService_GetEchoById_Call {
	_c.Call.Return(echo, err)
	return _c
}

func (_c *MockService_GetEchoById_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.Echo, error)) *MockService_GetEchoById_Call {
	_c.Call.Return(run)
	return _c
}

// GetEchosByPage provides a mock function for the type MockService
func (_mock *MockService) GetEchosByPage(ctx context.Context, pageQueryDto model0.PageQueryDto) (model0.PageQueryResult[[]model.Echo], error) {
	ret := _mock.Called(ctx, pageQueryDto)

	if len(ret) == 0 {
		panic("no return value specified for GetEchosByPage")
	}

	var r0 model0.PageQueryResult[[]model.Echo]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model0.PageQueryDto) (model0.PageQueryResult[[]model.Echo], error)); ok {
		return returnFunc(ctx, pageQueryDto)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model0.PageQueryDto) model0.PageQueryResult[[]model.Echo]); ok {
		r0 = returnFunc(ctx, pageQueryDto)
	} else {
		r0 = ret.Get(0).(model0.PageQueryResult[[]model.Echo])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model0.PageQueryDto) error); ok {
		r1 = returnFunc(ctx, pageQueryDto)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetEchosByPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEchosByPage'
type MockService_GetEchosByPage_Call struct {
	*mock.Call
}

// GetEchosByPage is a helper method to define mock.On call
//   - ctx context.Context
//   - pageQueryDto model0.PageQueryDto
func (_e *MockService_Expecter) GetEchosByPage(ctx any, pageQueryDto any) *MockService_GetEchosByPage_Call {
	return &MockService_GetEchosByPage_Call{Call: _e.mock.On("GetEchosByPage", ctx, pageQueryDto)}
}

func (_c *MockService_GetEchosByPage_Call) Run(run func(ctx context.Context, pageQueryDto model0.PageQueryDto)) *MockService_GetEchosByPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model0.PageQueryDto
		if args[1] != nil {
			arg1 = args[1].(model0.PageQueryDto)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetEchosByPage_Call) Return(pageQueryResult model0.PageQueryResult[[]model.Echo], err error) *MockService_GetEchosByPage_Call {
	_c.Call.Return(pageQueryResult, err)
	return _c
}

func (_c *MockService_GetEchosByPage_Call) RunAndReturn(run func(ctx context.Context, pageQueryDto model0.PageQueryDto) (model0.PageQueryResult[[]model.Echo], error)) *MockService_GetEchosByPage_Call {
	_c.Call.Return(run)
	return _c
}

// GetEchosByTagId provides a mock function for the type MockService
func (_mock *MockService) GetEchosByTagId(ctx context.Context, tagId string, pageQueryDto model0.PageQueryDto) (model0.PageQueryResult[[]model.Echo], error) {
	ret := _mock.Called(ctx, tagId, pageQueryDto)

	if len(ret) == 0 {
		panic("no return value specified for GetEchosByTagId")
	}

	var r0 model0.PageQueryResult[[]model.Echo]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model0.PageQueryDto) (model0.PageQueryResult[[]model.Echo], error)); ok {
		return returnFunc(ctx, tagId, pageQueryDto)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model0.PageQueryDto) model0.PageQueryResult[[]model.Echo]); ok {
		r0 = returnFunc(ctx, tagId, pageQueryDto)
	} else {
		r0 = ret.Get(0).(model0.PageQueryResult[[]model.Echo])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, model0.PageQueryDto) error); ok {
		r1 = returnFunc(ctx, tagId, pageQueryDto)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetEchosByTagId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEchosByTagId'
type MockService_GetEchosByTagId_Call struct {
	*mock.Call
}

// GetEchosByTagId is a helper method to define mock.On call
//   - ctx context.Context
//   - tagId string
//   - pageQueryDto model0.PageQueryDto
func (_e *MockService_Expecter) GetEchosByTagId(ctx any, tagId any, pageQueryDto any) *MockService_GetEchosByTagId_Call {
	return &MockService_GetEchosByTagId_Call{Call: _e.mock.On("GetEchosByTagId", ctx, tagId, pageQueryDto)}
}

func (_c *MockService_GetEchosByTagId_Call) Run(run func(ctx context.Context, tagId string, pageQueryDto model0.PageQueryDto)) *MockService_GetEchosByTagId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 model0.PageQueryDto
		if args[2] != nil {
			arg2 = args[2].(model0.PageQueryDto)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_GetEchosByTagId_Call) Return(pageQueryResult model0.PageQueryResult[[]model.Echo], err error) *MockService_GetEchosByTagId_Call {
	_c.Call.Return(pageQueryResult, err)
	return _c
}

func (_c *MockService_GetEchosByTagId_Call) RunAndReturn(run func(ctx context.Context, tagId string, pageQueryDto model0.PageQueryDto) (model0.PageQueryResult[[]model.Echo], error)) *MockService_GetEchosByTagId_Call {
	_c.Call.Return(run)
	return _c
}

// GetHotEchos provides a mock function for the type MockService
func (_mock *MockService) GetHotEchos(ctx context.Context, limit int) ([]model.Echo, error) {
	ret := _mock.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetHotEchos")
	}

	var r0 []model.Echo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]model.Echo, error)); ok {
		return returnFunc(ctx, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []model.Echo); ok {
		r0 = returnFunc(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Echo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetHotEchos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHotEchos'
type MockService_GetHotEchos_Call struct {
	*mock.Call
}

// GetHotEchos is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockService_Expecter) GetHotEchos(ctx any, limit any) *MockService_GetHotEchos_Call {
	return &MockService_GetHotEchos_Call{Call: _e.mock.On("GetHotEchos", ctx, limit)}
}

func (_c *MockService_GetHotEchos_Call) Run(run func(ctx context.Context, limit int)) *MockService_GetHotEchos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetHotEchos_Call) Return(echos []model.Echo, err error) *MockService_GetHotEchos_Call {
	_c.Call.Return(echos, err)
	return _c
}

func (_c *MockService_GetHotEchos_Call) RunAndReturn(run func(ctx context.Context, limit int) ([]model.Echo, error)) *MockService_GetHotEchos_Call {
	_c.Call.Return(run)
	return _c
}

// GetOnThisDayEchos provides a mock function for the type MockService
func (_mock *MockService) GetOnThisDayEchos(ctx context.Context, timezone string) ([]model.Echo, error) {
	ret := _mock.Called(ctx, timezone)

	if len(ret) == 0 {
		panic("no return value specified for GetOnThisDayEchos")
	}

	var r0 []model.Echo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]model.Echo, error)); ok {
		return returnFunc(ctx, timezone)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []model.Echo); ok {
		r0 = returnFunc(ctx, timezone)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Echo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, timezone)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetOnThisDayEchos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOnThisDayEchos'
type MockService_GetOnThisDayEchos_Call struct {
	*mock.Call
}

// GetOnThisDayEchos is a helper method to define mock.On call
//   - ctx context.Context
//   - timezone string
func (_e *MockService_Expecter) GetOnThisDayEchos(ctx any, timezone any) *MockService_GetOnThisDayEchos_Call {
	return &MockService_GetOnThisDayEchos_Call{Call: _e.mock.On("GetOnThisDayEchos", ctx, timezone)}
}

func (_c *MockService_GetOnThisDayEchos_Call) Run(run func(ctx context.Context, timezone string)) *MockService_GetOnThisDayEchos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetOnThisDayEchos_Call) Return(echos []model.Echo, err error) *MockService_GetOnThisDayEchos_Call {
	_c.Call.Return(echos, err)
	return _c
}

func (_c *MockService_GetOnThisDayEchos_Call) RunAndReturn(run func(ctx context.Context, timezone string) ([]model.Echo, error)) *MockService_GetOnThisDayEchos_Call {
	_c.Call.Return(run)
	return _c
}

// GetRandomEcho provides a mock function for the type MockService
func (_mock *MockService) GetRandomEcho(ctx context.Context) (*model.Echo, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRandomEcho")
	}

	var r0 *model.Echo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*model.Echo, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *model.Echo); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Echo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetRandomEcho_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRandomEcho'
type MockService_GetRandomEcho_Call struct {
	*mock.Call
}

// GetRandomEcho is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) GetRandomEcho(ctx any) *MockService_GetRandomEcho_Call {
	return &MockService_GetRandomEcho_Call{Call: _e.mock.On("GetRandomEcho", ctx)}
}

func (_c *MockService_GetRandomEcho_Call) Run(run func(ctx context.Context)) *MockService_GetRandomEcho_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_GetRandomEcho_Call) Return(echo *model.Echo, err error) *MockService_GetRandomEcho_Call {
	_c.Call.Return(echo, err)
	return _c
}

func (_c *MockService_GetRandomEcho_Call) RunAndReturn(run func(ctx context.Context) (*model.Echo, error)) *MockService_GetRandomEcho_Call {
	_c.Call.Return(run)
	return _c
}

// GetTodayEchos provides a mock function for the type MockService
func (_mock *MockService) GetTodayEchos(ctx context.Context, timezone string) ([]model.Echo, error) {
	ret := _mock.Called(ctx, timezone)

	if len(ret) == 0 {
		panic("no return value specified for GetTodayEchos")
	}

	var r0 []model.Echo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]model.Echo, error)); ok {
		return returnFunc(ctx, timezone)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []model.Echo); ok {
		r0 = returnFunc(ctx, timezone)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Echo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, timezone)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetTodayEchos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTodayEchos'
type MockService_GetTodayEchos_Call struct {
	*mock.Call
}

// GetTodayEchos is a helper method to define mock.On call
//   - ctx context.Context
//   - timezone string
func (_e *MockService_Expecter) GetTodayEchos(ctx any, timezone any) *MockService_GetTodayEchos_Call {
	return &MockService_GetTodayEchos_Call{Call: _e.mock.On("GetTodayEchos", ctx, timezone)}
}

func (_c *MockService_GetTodayEchos_Call) Run(run func(ctx context.Context, timezone string)) *MockService_GetTodayEchos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetTodayEchos_Call) Return(echos []model.Echo, err error) *MockService_GetTodayEchos_Call {
	_c.Call.Return(echos, err)
	return _c
}

func (_c *MockService_GetTodayEchos_Call) RunAndReturn(run func(ctx context.Context, timezone string) ([]model.Echo, error)) *MockService_GetTodayEchos_Call {
	_c.Call.Return(run)
	return _c
}

// LikeEcho provides a mock function for the type MockService
func (_mock *MockService) LikeEcho(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for LikeEcho")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_LikeEcho_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LikeEcho'
type MockService_LikeEcho_Call struct {
	*mock.Call
}

// LikeEcho is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockService_Expecter) LikeEcho(ctx any, id any) *MockService_LikeEcho_Call {
	return &MockService_LikeEcho_Call{Call: _e.mock.On("LikeEcho", ctx, id)}
}

func (_c *MockService_LikeEcho_Call) Run(run func(ctx context.Context, id string)) *MockService_LikeEcho_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_LikeEcho_Call) Return(err error) *MockService_LikeEcho_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_LikeEcho_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockService_LikeEcho_Call {
	_c.Call.Return(run)
	return _c
}

// PostEcho provides a mock function for the type MockService
func (_mock *MockService) PostEcho(ctx context.Context, newEcho *model.Echo) error {
	ret := _mock.Called(ctx, newEcho)

	if len(ret) == 0 {
		panic("no return value specified for PostEcho")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Echo) error); ok {
		r0 = returnFunc(ctx, newEcho)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_PostEcho_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostEcho'
type MockService_PostEcho_Call struct {
	*mock.Call
}

// PostEcho is a helper method to define mock.On call
//   - ctx context.Context
//   - newEcho *model.Echo
func (_e *MockService_Expecter) PostEcho(ctx any, newEcho any) *MockService_PostEcho_Call {
	return &MockService_PostEcho_Call{Call: _e.mock.On("PostEcho", ctx, newEcho)}
}

func (_c *MockService_PostEcho_Call) Run(run func(ctx context.Context, newEcho *model.Echo)) *MockService_PostEcho_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Echo
		if args[1] != nil {
			arg1 = args[1].(*model.Echo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_PostEcho_Call) Return(err error) *MockService_PostEcho_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_PostEcho_Call) RunAndReturn(run func(ctx context.Context, newEcho *model.Echo) error) *MockService_PostEcho_Call {
	_c.Call.Return(run)
	return _c
}

// QueryEchos provides a mock function for the type MockService
func (_mock *MockService) QueryEchos(ctx context.Context, queryDto model0.EchoQueryDto) (model0.PageQueryResult[[]model.Echo], error) {
	ret := _mock.Called(ctx, queryDto)

	if len(ret) == 0 {
		panic("no return value specified for QueryEchos")
	}

	var r0 model0.PageQueryResult[[]model.Echo]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model0.EchoQueryDto) (model0.PageQueryResult[[]model.Echo], error)); ok {
		return returnFunc(ctx, queryDto)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model0.EchoQueryDto) model0.PageQueryResult[[]model.Echo]); ok {
		r0 = returnFunc(ctx, queryDto)
	} else {
		r0 = ret.Get(0).(model0.PageQueryResult[[]model.Echo])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model0.EchoQueryDto) error); ok {
		r1 = returnFunc(ctx, queryDto)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_QueryEchos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryEchos'
type MockService_QueryEchos_Call struct {
	*mock.Call
}

// QueryEchos is a helper method to define mock.On call
//   - ctx context.Context
//   - queryDto model0.EchoQueryDto
func (_e *MockService_Expecter) QueryEchos(ctx any, queryDto any) *MockService_QueryEchos_Call {
	return &MockService_QueryEchos_Call{Call: _e.mock.On("QueryEchos", ctx, queryDto)}
}

func (_c *MockService_QueryEchos_Call) Run(run func(ctx context.Context, queryDto model0.EchoQueryDto)) *MockService_QueryEchos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model0.EchoQueryDto
		if args[1] != nil {
			arg1 = args[1].(model0.EchoQueryDto)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_QueryEchos_Call) Return(pageQueryResult model0.PageQueryResult[[]model.Echo], err error) *MockService_QueryEchos_Call {
	_c.Call.Return(pageQueryResult, err)
	return _c
}

func (_c *MockService_QueryEchos_Call) RunAndReturn(run func(ctx context.Context, queryDto model0.EchoQueryDto) (model0.PageQueryResult[[]model.Echo], error)) *MockService_QueryEchos_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEcho provides a mock function for the type MockService
func (_mock *MockService) UpdateEcho(ctx context.Context, echo *model.Echo) error {
	ret := _mock.Called(ctx, echo)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEcho")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Echo) error); ok {
		r0 = returnFunc(ctx, echo)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_UpdateEcho_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEcho'
type MockService_UpdateEcho_Call struct {
	*mock.Call
}

// UpdateEcho is a helper method to define mock.On call
//   - ctx context.Context
//   - echo *model.Echo
func (_e *MockService_Expecter) UpdateEcho(ctx any, echo any) *MockService_UpdateEcho_Call {
	return &MockService_UpdateEcho_Call{Call: _e.mock.On("UpdateEcho", ctx, echo)}
}

func (_c *MockService_UpdateEcho_Call) Run(run func(ctx context.Context, echo *model.Echo)) *MockService_UpdateEcho_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Echo
		if args[1] != nil {
			arg1 = args[1].(*model.Echo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_UpdateEcho_Call) Return(err error) *MockService_UpdateEcho_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_UpdateEcho_Call) RunAndReturn(run func(ctx context.Context, echo *model.Echo) error) *MockService_UpdateEcho_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateEcho provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateEcho(ctx context.Context, newEcho *model.Echo) error {
	ret := _mock.Called(ctx, newEcho)

	if len(ret) == 0 {
		panic("no return value specified for CreateEcho")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Echo) error); ok {
		r0 = returnFunc(ctx, newEcho)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_CreateEcho_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEcho'
type MockRepository_CreateEcho_Call struct {
	*mock.Call
}

// CreateEcho is a helper method to define mock.On call
//   - ctx context.Context
//   - newEcho *model.Echo
func (_e *MockRepository_Expecter) CreateEcho(ctx any, newEcho any) *MockRepository_CreateEcho_Call {
	return &MockRepository_CreateEcho_Call{Call: _e.mock.On("CreateEcho", ctx, newEcho)}
}

func (_c *MockRepository_CreateEcho_Call) Run(run func(ctx context.Context, newEcho *model.Echo)) *MockRepository_CreateEcho_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Echo
		if args[1] != nil {
			arg1 = args[1].(*model.Echo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateEcho_Call) Return(err error) *MockRepository_CreateEcho_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_CreateEcho_Call) RunAndReturn(run func(ctx context.Context, newEcho *model.Echo) error) *MockRepository_CreateEcho_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTag provides a mock function for the type MockRepository
func (_mock *MockRepository) CreateTag(ctx context.Context, tag *model.Tag) error {
	ret := _mock.Called(ctx, tag)

	if len(ret) == 0 {
		panic("no return value specified for CreateTag")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Tag) error); ok {
		r0 = returnFunc(ctx, tag)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_CreateTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTag'
type MockRepository_CreateTag_Call struct {
	*mock.Call
}

// CreateTag is a helper method to define mock.On call
//   - ctx context.Context
//   - tag *model.Tag
func (_e *MockRepository_Expecter) CreateTag(ctx any, tag any) *MockRepository_CreateTag_Call {
	return &MockRepository_CreateTag_Call{Call: _e.mock.On("CreateTag", ctx, tag)}
}

func (_c *MockRepository_CreateTag_Call) Run(run func(ctx context.Context, tag *model.Tag)) *MockRepository_CreateTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Tag
		if args[1] != nil {
			arg1 = args[1].(*model.Tag)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreateTag_Call) Return(err error) *MockRepository_CreateTag_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_CreateTag_Call) RunAndReturn(run func(ctx context.Context, tag *model.Tag) error) *MockRepository_CreateTag_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEchoById provides a mock function for the type MockRepository
func (_mock *MockRepository) DeleteEchoById(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEchoById")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeleteEchoById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEchoById'
type MockRepository_DeleteEchoById_Call struct {
	*mock.Call
}

// DeleteEchoById is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) DeleteEchoById(ctx any, id any) *MockRepository_DeleteEchoById_Call {
	return &MockRepository_DeleteEchoById_Call{Call: _e.mock.On("DeleteEchoById", ctx, id)}
}

func (_c *MockRepository_DeleteEchoById_Call) Run(run func(ctx context.Context, id string)) *MockRepository_DeleteEchoById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteEchoById_Call) Return(err error) *MockRepository_DeleteEchoById_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeleteEchoById_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockRepository_DeleteEchoById_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTagById provides a mock function for the type MockRepository
func (_mock *MockRepository) DeleteTagById(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTagById")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeleteTagById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTagById'
type MockRepository_DeleteTagById_Call struct {
	*mock.Call
}

// DeleteTagById is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) DeleteTagById(ctx any, id any) *MockRepository_DeleteTagById_Call {
	return &MockRepository_DeleteTagById_Call{Call: _e.mock.On("DeleteTagById", ctx, id)}
}

func (_c *MockRepository_DeleteTagById_Call) Run(run func(ctx context.Context, id string)) *MockRepository_DeleteTagById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_DeleteTagById_Call) Return(err error) *MockRepository_DeleteTagById_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeleteTagById_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockRepository_DeleteTagById_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllTags provides a mock function for the type MockRepository
func (_mock *MockRepository) GetAllTags() ([]model.Tag, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllTags")
	}

	var r0 []model.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]model.Tag, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []model.Tag); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetAllTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllTags'
type MockRepository_GetAllTags_Call struct {
	*mock.Call
}

// GetAllTags is a helper method to define mock.On call
func (_e *MockRepository_Expecter) GetAllTags() *MockRepository_GetAllTags_Call {
	return &MockRepository_GetAllTags_Call{Call: _e.mock.On("GetAllTags")}
}

func (_c *MockRepository_GetAllTags_Call) Run(run func()) *MockRepository_GetAllTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_GetAllTags_Call) Return(tags []model.Tag, err error) *MockRepository_GetAllTags_Call {
	_c.Call.Return(tags, err)
	return _c
}

func (_c *MockRepository_GetAllTags_Call) RunAndReturn(run func() ([]model.Tag, error)) *MockRepository_GetAllTags_Call {
	_c.Call.Return(run)
	return _c
}

// GetEchosById provides a mock function for the type MockRepository
func (_mock *MockRepository) GetEchosById(ctx context.Context, id string) (*model.Echo, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetEchosById")
	}

	var r0 *model.Echo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model.Echo, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model.Echo); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Echo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetEchosById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEchosById'
type MockRepository_GetEchosById_Call struct {
	*mock.Call
}

// GetEchosById is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) GetEchosById(ctx any, id any) *MockRepository_GetEchosById_Call {
	return &MockRepository_GetEchosById_Call{Call: _e.mock.On("GetEchosById", ctx, id)}
}

func (_c *MockRepository_GetEchosById_Call) Run(run func(ctx context.Context, id string)) *MockRepository_GetEchosById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetEchosById_Call) Return(echo *model.Echo, err error) *MockRepository_GetEchosById_Call {
	_c.Call.Return(echo, err)
	return _c
}

func (_c *MockRepository_GetEchosById_Call) RunAndReturn(run func(ctx context.Context, id string) (*model.Echo, error)) *MockRepository_GetEchosById_Call {
	_c.Call.Return(run)
	return _c
}

// GetEchosByPage provides a mock function for the type MockRepository
func (_mock *MockRepository) GetEchosByPage(page int, pageSize int, search string, showPrivate bool) ([]model.Echo, int64) {
	ret := _mock.Called(page, pageSize, search, showPrivate)

	if len(ret) == 0 {
		panic("no return value specified for GetEchosByPage")
	}

	var r0 []model.Echo
	var r1 int64
	if returnFunc, ok := ret.Get(0).(func(int, int, string, bool) ([]model.Echo, int64)); ok {
		return returnFunc(page, pageSize, search, showPrivate)
	}
	if returnFunc, ok := ret.Get(0).(func(int, int, string, bool) []model.Echo); ok {
		r0 = returnFunc(page, pageSize, search, showPrivate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Echo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, int, string, bool) int64); ok {
		r1 = returnFunc(page, pageSize, search, showPrivate)
	} else {
		r1 = ret.Get(1).(int64)
	}
	return r0, r1
}

// MockRepository_GetEchosByPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEchosByPage'
type MockRepository_GetEchosByPage_Call struct {
	*mock.Call
}

// GetEchosByPage is a helper method to define mock.On call
//   - page int
//   - pageSize int
//   - search string
//   - showPrivate bool
func (_e *MockRepository_Expecter) GetEchosByPage(page any, pageSize any, search any, showPrivate any) *MockRepository_GetEchosByPage_Call {
	return &MockRepository_GetEchosByPage_Call{Call: _e.mock.On("GetEchosByPage", page, pageSize, search, showPrivate)}
}

func (_c *MockRepository_GetEchosByPage_Call) Run(run func(page int, pageSize int, search string, showPrivate bool)) *MockRepository_GetEchosByPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_GetEchosByPage_Call) Return(echos []model.Echo, n int64) *MockRepository_GetEchosByPage_Call {
	_c.Call.Return(echos, n)
	return _c
}

func (_c *MockRepository_GetEchosByPage_Call) RunAndReturn(run func(page int, pageSize int, search string, showPrivate bool) ([]model.Echo, int64)) *MockRepository_GetEchosByPage_Call {
	_c.Call.Return(run)
	return _c
}

// GetEchosByTagId provides a mock function for the type MockRepository
func (_mock *MockRepository) GetEchosByTagId(tagID string, page int, pageSize int, search string, showPrivate bool) ([]model.Echo, int64, error) {
	ret := _mock.Called(tagID, page, pageSize, search, showPrivate)

	if len(ret) == 0 {
		panic("no return value specified for GetEchosByTagId")
	}

	var r0 []model.Echo
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, int, int, string, bool) ([]model.Echo, int64, error)); ok {
		return returnFunc(tagID, page, pageSize, search, showPrivate)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int, int, string, bool) []model.Echo); ok {
		r0 = returnFunc(tagID, page, pageSize, search, showPrivate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Echo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int, int, string, bool) int64); ok {
		r1 = returnFunc(tagID, page, pageSize, search, showPrivate)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(string, int, int, string, bool) error); ok {
		r2 = returnFunc(tagID, page, pageSize, search, showPrivate)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepository_GetEchosByTagId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEchosByTagId'
type MockRepository_GetEchosByTagId_Call struct {
	*mock.Call
}

// GetEchosByTagId is a helper method to define mock.On call
//   - tagID string
//   - page int
//   - pageSize int
//   - search string
//   - showPrivate bool
func (_e *MockRepository_Expecter) GetEchosByTagId(tagID any, page any, pageSize any, search any, showPrivate any) *MockRepository_GetEchosByTagId_Call {
	return &MockRepository_GetEchosByTagId_Call{Call: _e.mock.On("GetEchosByTagId", tagID, page, pageSize, search, showPrivate)}
}

func (_c *MockRepository_GetEchosByTagId_Call) Run(run func(tagID string, page int, pageSize int, search string, showPrivate bool)) *MockRepository_GetEchosByTagId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockRepository_GetEchosByTagId_Call) Return(echos []model.Echo, n int64, err error) *MockRepository_GetEchosByTagId_Call {
	_c.Call.Return(echos, n, err)
	return _c
}

func (_c *MockRepository_GetEchosByTagId_Call) RunAndReturn(run func(tagID string, page int, pageSize int, search string, showPrivate bool) ([]model.Echo, int64, error)) *MockRepository_GetEchosByTagId_Call {
	_c.Call.Return(run)
	return _c
}

// GetHotEchos provides a mock function for the type MockRepository
func (_mock *MockRepository) GetHotEchos(limit int, showPrivate bool) ([]model.Echo, error) {
	ret := _mock.Called(limit, showPrivate)

	if len(ret) == 0 {
		panic("no return value specified for GetHotEchos")
	}

	var r0 []model.Echo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, bool) ([]model.Echo, error)); ok {
		return returnFunc(limit, showPrivate)
	}
	if returnFunc, ok := ret.Get(0).(func(int, bool) []model.Echo); ok {
		r0 = returnFunc(limit, showPrivate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Echo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, bool) error); ok {
		r1 = returnFunc(limit, showPrivate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetHotEchos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHotEchos'
type MockRepository_GetHotEchos_Call struct {
	*mock.Call
}

// GetHotEchos is a helper method to define mock.On call
//   - limit int
//   - showPrivate bool
func (_e *MockRepository_Expecter) GetHotEchos(limit any, showPrivate any) *MockRepository_GetHotEchos_Call {
	return &MockRepository_GetHotEchos_Call{Call: _e.mock.On("GetHotEchos", limit, showPrivate)}
}

func (_c *MockRepository_GetHotEchos_Call) Run(run func(limit int, showPrivate bool)) *MockRepository_GetHotEchos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetHotEchos_Call) Return(echos []model.Echo, err error) *MockRepository_GetHotEchos_Call {
	_c.Call.Return(echos, err)
	return _c
}

func (_c *MockRepository_GetHotEchos_Call) RunAndReturn(run func(limit int, showPrivate bool) ([]model.Echo, error)) *MockRepository_GetHotEchos_Call {
	_c.Call.Return(run)
	return _c
}

// GetOnThisDayEchos provides a mock function for the type MockRepository
func (_mock *MockRepository) GetOnThisDayEchos(showPrivate bool, timezone string) []model.Echo {
	ret := _mock.Called(showPrivate, timezone)

	if len(ret) == 0 {
		panic("no return value specified for GetOnThisDayEchos")
	}

	var r0 []model.Echo
	if returnFunc, ok := ret.Get(0).(func(bool, string) []model.Echo); ok {
		r0 = returnFunc(showPrivate, timezone)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Echo)
		}
	}
	return r0
}

// MockRepository_GetOnThisDayEchos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOnThisDayEchos'
type MockRepository_GetOnThisDayEchos_Call struct {
	*mock.Call
}

// GetOnThisDayEchos is a helper method to define mock.On call
//   - showPrivate bool
//   - timezone string
func (_e *MockRepository_Expecter) GetOnThisDayEchos(showPrivate any, timezone any) *MockRepository_GetOnThisDayEchos_Call {
	return &MockRepository_GetOnThisDayEchos_Call{Call: _e.mock.On("GetOnThisDayEchos", showPrivate, timezone)}
}

func (_c *MockRepository_GetOnThisDayEchos_Call) Run(run func(showPrivate bool, timezone string)) *MockRepository_GetOnThisDayEchos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetOnThisDayEchos_Call) Return(echos []model.Echo) *MockRepository_GetOnThisDayEchos_Call {
	_c.Call.Return(echos)
	return _c
}

func (_c *MockRepository_GetOnThisDayEchos_Call) RunAndReturn(run func(showPrivate bool, timezone string) []model.Echo) *MockRepository_GetOnThisDayEchos_Call {
	_c.Call.Return(run)
	return _c
}

// GetRandomEcho provides a mock function for the type MockRepository
func (_mock *MockRepository) GetRandomEcho(showPrivate bool) (*model.Echo, error) {
	ret := _mock.Called(showPrivate)

	if len(ret) == 0 {
		panic("no return value specified for GetRandomEcho")
	}

	var r0 *model.Echo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(bool) (*model.Echo, error)); ok {
		return returnFunc(showPrivate)
	}
	if returnFunc, ok := ret.Get(0).(func(bool) *model.Echo); ok {
		r0 = returnFunc(showPrivate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Echo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(bool) error); ok {
		r1 = returnFunc(showPrivate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetRandomEcho_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRandomEcho'
type MockRepository_GetRandomEcho_Call struct {
	*mock.Call
}

// GetRandomEcho is a helper method to define mock.On call
//   - showPrivate bool
func (_e *MockRepository_Expecter) GetRandomEcho(showPrivate any) *MockRepository_GetRandomEcho_Call {
	return &MockRepository_GetRandomEcho_Call{Call: _e.mock.On("GetRandomEcho", showPrivate)}
}

func (_c *MockRepository_GetRandomEcho_Call) Run(run func(showPrivate bool)) *MockRepository_GetRandomEcho_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_GetRandomEcho_Call) Return(echo *model.Echo, err error) *MockRepository_GetRandomEcho_Call {
	_c.Call.Return(echo, err)
	return _c
}

func (_c *MockRepository_GetRandomEcho_Call) RunAndReturn(run func(showPrivate bool) (*model.Echo, error)) *MockRepository_GetRandomEcho_Call {
	_c.Call.Return(run)
	return _c
}

// GetTagsByNames provides a mock function for the type MockRepository
func (_mock *MockRepository) GetTagsByNames(ctx context.Context, names []string) ([]*model.Tag, error) {
	ret := _mock.Called(ctx, names)

	if len(ret) == 0 {
		panic("no return value specified for GetTagsByNames")
	}

	var r0 []*model.Tag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) ([]*model.Tag, error)); ok {
		return returnFunc(ctx, names)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) []*model.Tag); ok {
		r0 = returnFunc(ctx, names)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Tag)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = returnFunc(ctx, names)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetTagsByNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTagsByNames'
type MockRepository_GetTagsByNames_Call struct {
	*mock.Call
}

// GetTagsByNames is a helper method to define mock.On call
//   - ctx context.Context
//   - names []string
func (_e *MockRepository_Expecter) GetTagsByNames(ctx any, names any) *MockRepository_GetTagsByNames_Call {
	return &MockRepository_GetTagsByNames_Call{Call: _e.mock.On("GetTagsByNames", ctx, names)}
}

func (_c *MockRepository_GetTagsByNames_Call) Run(run func(ctx context.Context, names []string)) *MockRepository_GetTagsByNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetTagsByNames_Call) Return(tags []*model.Tag, err error) *MockRepository_GetTagsByNames_Call {
	_c.Call.Return(tags, err)
	return _c
}

func (_c *MockRepository_GetTagsByNames_Call) RunAndReturn(run func(ctx context.Context, names []string) ([]*model.Tag, error)) *MockRepository_GetTagsByNames_Call {
	_c.Call.Return(run)
	return _c
}

// GetTodayEchos provides a mock function for the type MockRepository
func (_mock *MockRepository) GetTodayEchos(showPrivate bool, timezone string) []model.Echo {
	ret := _mock.Called(showPrivate, timezone)

	if len(ret) == 0 {
		panic("no return value specified for GetTodayEchos")
	}

	var r0 []model.Echo
	if returnFunc, ok := ret.Get(0).(func(bool, string) []model.Echo); ok {
		r0 = returnFunc(showPrivate, timezone)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Echo)
		}
	}
	return r0
}

// MockRepository_GetTodayEchos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTodayEchos'
type MockRepository_GetTodayEchos_Call struct {
	*mock.Call
}

// GetTodayEchos is a helper method to define mock.On call
//   - showPrivate bool
//   - timezone string
func (_e *MockRepository_Expecter) GetTodayEchos(showPrivate any, timezone any) *MockRepository_GetTodayEchos_Call {
	return &MockRepository_GetTodayEchos_Call{Call: _e.mock.On("GetTodayEchos", showPrivate, timezone)}
}

func (_c *MockRepository_GetTodayEchos_Call) Run(run func(showPrivate bool, timezone string)) *MockRepository_GetTodayEchos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetTodayEchos_Call) Return(echos []model.Echo) *MockRepository_GetTodayEchos_Call {
	_c.Call.Return(echos)
	return _c
}

func (_c *MockRepository_GetTodayEchos_Call) RunAndReturn(run func(showPrivate bool, timezone string) []model.Echo) *MockRepository_GetTodayEchos_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementTagUsageCount provides a mock function for the type MockRepository
func (_mock *MockRepository) IncrementTagUsageCount(ctx context.Context, tagID string) error {
	ret := _mock.Called(ctx, tagID)

	if len(ret) == 0 {
		panic("no return value specified for IncrementTagUsageCount")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, tagID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_IncrementTagUsageCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementTagUsageCount'
type MockRepository_IncrementTagUsageCount_Call struct {
	*mock.Call
}

// IncrementTagUsageCount is a helper method to define mock.On call
//   - ctx context.Context
//   - tagID string
func (_e *MockRepository_Expecter) IncrementTagUsageCount(ctx any, tagID any) *MockRepository_IncrementTagUsageCount_Call {
	return &MockRepository_IncrementTagUsageCount_Call{Call: _e.mock.On("IncrementTagUsageCount", ctx, tagID)}
}

func (_c *MockRepository_IncrementTagUsageCount_Call) Run(run func(ctx context.Context, tagID string)) *MockRepository_IncrementTagUsageCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_IncrementTagUsageCount_Call) Return(err error) *MockRepository_IncrementTagUsageCount_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_IncrementTagUsageCount_Call) RunAndReturn(run func(ctx context.Context, tagID string) error) *MockRepository_IncrementTagUsageCount_Call {
	_c.Call.Return(run)
	return _c
}

// InvalidateEchoCaches provides a mock function for the type MockRepository
func (_mock *MockRepository) InvalidateEchoCaches(echoIDs ...string) {
	// string
	_va := make([]any, len(echoIDs))
	for _i := range echoIDs {
		_va[_i] = echoIDs[_i]
	}
	var _ca []any
	_ca = append(_ca, _va...)
	_mock.Called(_ca...)
	return
}

// MockRepository_InvalidateEchoCaches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateEchoCaches'
type MockRepository_InvalidateEchoCaches_Call struct {
	*mock.Call
}

// InvalidateEchoCaches is a helper method to define mock.On call
//   - echoIDs ...string
func (_e *MockRepository_Expecter) InvalidateEchoCaches(echoIDs ...any) *MockRepository_InvalidateEchoCaches_Call {
	return &MockRepository_InvalidateEchoCaches_Call{Call: _e.mock.On("InvalidateEchoCaches",
		append([]any{}, echoIDs...)...)}
}

func (_c *MockRepository_InvalidateEchoCaches_Call) Run(run func(echoIDs ...string)) *MockRepository_InvalidateEchoCaches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		variadicArgs := make([]string, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockRepository_InvalidateEchoCaches_Call) Return() *MockRepository_InvalidateEchoCaches_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRepository_InvalidateEchoCaches_Call) RunAndReturn(run func(echoIDs ...string)) *MockRepository_InvalidateEchoCaches_Call {
	_c.Run(run)
	return _c
}

// LikeEcho provides a mock function for the type MockRepository
func (_mock *MockRepository) LikeEcho(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for LikeEcho")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_LikeEcho_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LikeEcho'
type MockRepository_LikeEcho_Call struct {
	*mock.Call
}

// LikeEcho is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) LikeEcho(ctx any, id any) *MockRepository_LikeEcho_Call {
	return &MockRepository_LikeEcho_Call{Call: _e.mock.On("LikeEcho", ctx, id)}
}

func (_c *MockRepository_LikeEcho_Call) Run(run func(ctx context.Context, id string)) *MockRepository_LikeEcho_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_LikeEcho_Call) Return(err error) *MockRepository_LikeEcho_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_LikeEcho_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockRepository_LikeEcho_Call {
	_c.Call.Return(run)
	return _c
}

// QueryEchos provides a mock function for the type MockRepository
func (_mock *MockRepository) QueryEchos(queryDto model0.EchoQueryDto, showPrivate bool) ([]model.Echo, int64, error) {
	ret := _mock.Called(queryDto, showPrivate)

	if len(ret) == 0 {
		panic("no return value specified for QueryEchos")
	}

	var r0 []model.Echo
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(model0.EchoQueryDto, bool) ([]model.Echo, int64, error)); ok {
		return returnFunc(queryDto, showPrivate)
	}
	if returnFunc, ok := ret.Get(0).(func(model0.EchoQueryDto, bool) []model.Echo); ok {
		r0 = returnFunc(queryDto, showPrivate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Echo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(model0.EchoQueryDto, bool) int64); ok {
		r1 = returnFunc(queryDto, showPrivate)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(model0.EchoQueryDto, bool) error); ok {
		r2 = returnFunc(queryDto, showPrivate)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepository_QueryEchos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryEchos'
type MockRepository_QueryEchos_Call struct {
	*mock.Call
}

// QueryEchos is a helper method to define mock.On call
//   - queryDto model0.EchoQueryDto
//   - showPrivate bool
func (_e *MockRepository_Expecter) QueryEchos(queryDto any, showPrivate any) *MockRepository_QueryEchos_Call {
	return &MockRepository_QueryEchos_Call{Call: _e.mock.On("QueryEchos", queryDto, showPrivate)}
}

func (_c *MockRepository_QueryEchos_Call) Run(run func(queryDto model0.EchoQueryDto, showPrivate bool)) *MockRepository_QueryEchos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model0.EchoQueryDto
		if args[0] != nil {
			arg0 = args[0].(model0.EchoQueryDto)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_QueryEchos_Call) Return(echos []model.Echo, n int64, err error) *MockRepository_QueryEchos_Call {
	_c.Call.Return(echos, n, err)
	return _c
}

func (_c *MockRepository_QueryEchos_Call) RunAndReturn(run func(queryDto model0.EchoQueryDto, showPrivate bool) ([]model.Echo, int64, error)) *MockRepository_QueryEchos_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEcho provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdateEcho(ctx context.Context, echo *model.Echo) error {
	ret := _mock.Called(ctx, echo)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEcho")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Echo) error); ok {
		r0 = returnFunc(ctx, echo)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdateEcho_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEcho'
type MockRepository_UpdateEcho_Call struct {
	*mock.Call
}

// UpdateEcho is a helper method to define mock.On call
//   - ctx context.Context
//   - echo *model.Echo
func (_e *MockRepository_Expecter) UpdateEcho(ctx any, echo any) *MockRepository_UpdateEcho_Call {
	return &MockRepository_UpdateEcho_Call{Call: _e.mock.On("UpdateEcho", ctx, echo)}
}

func (_c *MockRepository_UpdateEcho_Call) Run(run func(ctx context.Context, echo *model.Echo)) *MockRepository_UpdateEcho_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Echo
		if args[1] != nil {
			arg1 = args[1].(*model.Echo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_UpdateEcho_Call) Return(err error) *MockRepository_UpdateEcho_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdateEcho_Call) RunAndReturn(run func(ctx context.Context, echo *model.Echo) error) *MockRepository_UpdateEcho_Call {
	_c.Call.Return(run)
	return _c
}
