// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2025-2026 lin-snow

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package authmock

import (
	"context"
	"encoding/json"
	"time"

	"github.com/lin-snow/ech0/internal/model/auth"
	model0 "github.com/lin-snow/ech0/internal/model/user"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// BindOAuth provides a mock function for the type MockService
func (_mock *MockService) BindOAuth(ctx context.Context, provider string, redirectURI string) (string, error) {
	ret := _mock.Called(ctx, provider, redirectURI)

	if len(ret) == 0 {
		panic("no return value specified for BindOAuth")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, provider, redirectURI)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, provider, redirectURI)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, provider, redirectURI)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_BindOAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BindOAuth'
type MockService_BindOAuth_Call struct {
	*mock.Call
}

// BindOAuth is a helper method to define mock.On call
//   - ctx context.Context
//   - provider string
//   - redirectURI string
func (_e *MockService_Expecter) BindOAuth(ctx any, provider any, redirectURI any) *MockService_BindOAuth_Call {
	return &MockService_BindOAuth_Call{Call: _e.mock.On("BindOAuth", ctx, provider, redirectURI)}
}

func (_c *MockService_BindOAuth_Call) Run(run func(ctx context.Context, provider string, redirectURI string)) *MockService_BindOAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_BindOAuth_Call) Return(s string, err error) *MockService_BindOAuth_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockService_BindOAuth_Call) RunAndReturn(run func(ctx context.Context, provider string, redirectURI string) (string, error)) *MockService_BindOAuth_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePasskey provides a mock function for the type MockService
func (_mock *MockService) DeletePasskey(ctx context.Context, passkeyID string) error {
	ret := _mock.Called(ctx, passkeyID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePasskey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, passkeyID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeletePasskey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePasskey'
type MockService_DeletePasskey_Call struct {
	*mock.Call
}

// DeletePasskey is a helper method to define mock.On call
//   - ctx context.Context
//   - passkeyID string
func (_e *MockService_Expecter) DeletePasskey(ctx any, passkeyID any) *MockService_DeletePasskey_Call {
	return &MockService_DeletePasskey_Call{Call: _e.mock.On("DeletePasskey", ctx, passkeyID)}
}

func (_c *MockService_DeletePasskey_Call) Run(run func(ctx context.Context, passkeyID string)) *MockService_DeletePasskey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_DeletePasskey_Call) Return(err error) *MockService_DeletePasskey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeletePasskey_Call) RunAndReturn(run func(ctx context.Context, passkeyID string) error) *MockService_DeletePasskey_Call {
	_c.Call.Return(run)
	return _c
}

// ExchangeOAuthCode provides a mock function for the type MockService
func (_mock *MockService) ExchangeOAuthCode(code string) (*model.TokenPair, error) {
	ret := _mock.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for ExchangeOAuthCode")
	}

	var r0 *model.TokenPair
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*model.TokenPair, error)); ok {
		return returnFunc(code)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *model.TokenPair); ok {
		r0 = returnFunc(code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TokenPair)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ExchangeOAuthCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExchangeOAuthCode'
type MockService_ExchangeOAuthCode_Call struct {
	*mock.Call
}

// ExchangeOAuthCode is a helper method to define mock.On call
//   - code string
func (_e *MockService_Expecter) ExchangeOAuthCode(code any) *MockService_ExchangeOAuthCode_Call {
	return &MockService_ExchangeOAuthCode_Call{Call: _e.mock.On("ExchangeOAuthCode", code)}
}

func (_c *MockService_ExchangeOAuthCode_Call) Run(run func(code string)) *MockService_ExchangeOAuthCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_ExchangeOAuthCode_Call) Return(tokenPair *model.TokenPair, err error) *MockService_ExchangeOAuthCode_Call {
	_c.Call.Return(tokenPair, err)
	return _c
}

func (_c *MockService_ExchangeOAuthCode_Call) RunAndReturn(run func(code string) (*model.TokenPair, error)) *MockService_ExchangeOAuthCode_Call {
	_c.Call.Return(run)
	return _c
}

// GetOAuthInfo provides a mock function for the type MockService
func (_mock *MockService) GetOAuthInfo(ctx context.Context, provider string) (model0.OAuthInfoDto, error) {
	ret := _mock.Called(ctx, provider)

	if len(ret) == 0 {
		panic("no return value specified for GetOAuthInfo")
	}

	var r0 model0.OAuthInfoDto
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model0.OAuthInfoDto, error)); ok {
		return returnFunc(ctx, provider)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model0.OAuthInfoDto); ok {
		r0 = returnFunc(ctx, provider)
	} else {
		r0 = ret.Get(0).(model0.OAuthInfoDto)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, provider)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetOAuthInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOAuthInfo'
type MockService_GetOAuthInfo_Call struct {
	*mock.Call
}

// GetOAuthInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - provider string
func (_e *MockService_Expecter) GetOAuthInfo(ctx any, provider any) *MockService_GetOAuthInfo_Call {
	return &MockService_GetOAuthInfo_Call{Call: _e.mock.On("GetOAuthInfo", ctx, provider)}
}

func (_c *MockService_GetOAuthInfo_Call) Run(run func(ctx context.Context, provider string)) *MockService_GetOAuthInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetOAuthInfo_Call) Return(oAuthInfoDto model0.OAuthInfoDto, err error) *MockService_GetOAuthInfo_Call {
	_c.Call.Return(oAuthInfoDto, err)
	return _c
}

func (_c *MockService_GetOAuthInfo_Call) RunAndReturn(run func(ctx context.Context, provider string) (model0.OAuthInfoDto, error)) *MockService_GetOAuthInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetOAuthLoginURL provides a mock function for the type MockService
func (_mock *MockService) GetOAuthLoginURL(provider string, redirectURI string) (string, error) {
	ret := _mock.Called(provider, redirectURI)

	if len(ret) == 0 {
		panic("no return value specified for GetOAuthLoginURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return returnFunc(provider, redirectURI)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(provider, redirectURI)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(provider, redirectURI)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetOAuthLoginURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOAuthLoginURL'
type MockService_GetOAuthLoginURL_Call struct {
	*mock.Call
}

// GetOAuthLoginURL is a helper method to define mock.On call
//   - provider string
//   - redirectURI string
func (_e *MockService_Expecter) GetOAuthLoginURL(provider any, redirectURI any) *MockService_GetOAuthLoginURL_Call {
	return &MockService_GetOAuthLoginURL_Call{Call: _e.mock.On("GetOAuthLoginURL", provider, redirectURI)}
}

func (_c *MockService_GetOAuthLoginURL_Call) Run(run func(provider string, redirectURI string)) *MockService_GetOAuthLoginURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetOAuthLoginURL_Call) Return(s string, err error) *MockService_GetOAuthLoginURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockService_GetOAuthLoginURL_Call) RunAndReturn(run func(provider string, redirectURI string) (string, error)) *MockService_GetOAuthLoginURL_Call {
	_c.Call.Return(run)
	return _c
}

// HandleOAuthCallback provides a mock function for the type MockService
func (_mock *MockService) HandleOAuthCallback(provider string, code string, state string) (string, error) {
	ret := _mock.Called(provider, code, state)

	if len(ret) == 0 {
		panic("no return value specified for HandleOAuthCallback")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) (string, error)); ok {
		return returnFunc(provider, code, state)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string) string); ok {
		r0 = returnFunc(provider, code, state)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = returnFunc(provider, code, state)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_HandleOAuthCallback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleOAuthCallback'
type MockService_HandleOAuthCallback_Call struct {
	*mock.Call
}

// HandleOAuthCallback is a helper method to define mock.On call
//   - provider string
//   - code string
//   - state string
func (_e *MockService_Expecter) HandleOAuthCallback(provider any, code any, state any) *MockService_HandleOAuthCallback_Call {
	return &MockService_HandleOAuthCallback_Call{Call: _e.mock.On("HandleOAuthCallback", provider, code, state)}
}

func (_c *MockService_HandleOAuthCallback_Call) Run(run func(provider string, code string, state string)) *MockService_HandleOAuthCallback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_HandleOAuthCallback_Call) Return(s string, err error) *MockService_HandleOAuthCallback_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockService_HandleOAuthCallback_Call) RunAndReturn(run func(provider string, code string, state string) (string, error)) *MockService_HandleOAuthCallback_Call {
	_c.Call.Return(run)
	return _c
}

// IsTokenRevoked provides a mock function for the type MockService
func (_mock *MockService) IsTokenRevoked(jti string) bool {
	ret := _mock.Called(jti)

	if len(ret) == 0 {
		panic("no return value specified for IsTokenRevoked")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(jti)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockService_IsTokenRevoked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsTokenRevoked'
type MockService_IsTokenRevoked_Call struct {
	*mock.Call
}

// IsTokenRevoked is a helper method to define mock.On call
//   - jti string
func (_e *MockService_Expecter) IsTokenRevoked(jti any) *MockService_IsTokenRevoked_Call {
	return &MockService_IsTokenRevoked_Call{Call: _e.mock.On("IsTokenRevoked", jti)}
}

func (_c *MockService_IsTokenRevoked_Call) Run(run func(jti string)) *MockService_IsTokenRevoked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_IsTokenRevoked_Call) Return(b bool) *MockService_IsTokenRevoked_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockService_IsTokenRevoked_Call) RunAndReturn(run func(jti string) bool) *MockService_IsTokenRevoked_Call {
	_c.Call.Return(run)
	return _c
}

// ListPasskeys provides a mock function for the type MockService
func (_mock *MockService) ListPasskeys(ctx context.Context) ([]model.PasskeyDeviceDto, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListPasskeys")
	}

	var r0 []model.PasskeyDeviceDto
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]model.PasskeyDeviceDto, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []model.PasskeyDeviceDto); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.PasskeyDeviceDto)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListPasskeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPasskeys'
type MockService_ListPasskeys_Call struct {
	*mock.Call
}

// ListPasskeys is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) ListPasskeys(ctx any) *MockService_ListPasskeys_Call {
	return &MockService_ListPasskeys_Call{Call: _e.mock.On("ListPasskeys", ctx)}
}

func (_c *MockService_ListPasskeys_Call) Run(run func(ctx context.Context)) *MockService_ListPasskeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_ListPasskeys_Call) Return(passkeyDeviceDtos []model.PasskeyDeviceDto, err error) *MockService_ListPasskeys_Call {
	_c.Call.Return(passkeyDeviceDtos, err)
	return _c
}

func (_c *MockService_ListPasskeys_Call) RunAndReturn(run func(ctx context.Context) ([]model.PasskeyDeviceDto, error)) *MockService_ListPasskeys_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type MockService
func (_mock *MockService) Login(loginDto *model.LoginDto) (*model.TokenPair, error) {
	ret := _mock.Called(loginDto)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *model.TokenPair
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*model.LoginDto) (*model.TokenPair, error)); ok {
		return returnFunc(loginDto)
	}
	if returnFunc, ok := ret.Get(0).(func(*model.LoginDto) *model.TokenPair); ok {
		r0 = returnFunc(loginDto)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TokenPair)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*model.LoginDto) error); ok {
		r1 = returnFunc(loginDto)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockService_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - loginDto *model.LoginDto
func (_e *MockService_Expecter) Login(loginDto any) *MockService_Login_Call {
	return &MockService_Login_Call{Call: _e.mock.On("Login", loginDto)}
}

func (_c *MockService_Login_Call) Run(run func(loginDto *model.LoginDto)) *MockService_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.LoginDto
		if args[0] != nil {
			arg0 = args[0].(*model.LoginDto)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_Login_Call) Return(tokenPair *model.TokenPair, err error) *MockService_Login_Call {
	_c.Call.Return(tokenPair, err)
	return _c
}

func (_c *MockService_Login_Call) RunAndReturn(run func(loginDto *model.LoginDto) (*model.TokenPair, error)) *MockService_Login_Call {
	_c.Call.Return(run)
	return _c
}

// PasskeyBoundary provides a mock function for the type MockService
func (_mock *MockService) PasskeyBoundary(ctx context.Context) (string, []string) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PasskeyBoundary")
	}

	var r0 string
	var r1 []string
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, []string)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) []string); ok {
		r1 = returnFunc(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]string)
		}
	}
	return r0, r1
}

// MockService_PasskeyBoundary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PasskeyBoundary'
type MockService_PasskeyBoundary_Call struct {
	*mock.Call
}

// PasskeyBoundary is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) PasskeyBoundary(ctx any) *MockService_PasskeyBoundary_Call {
	return &MockService_PasskeyBoundary_Call{Call: _e.mock.On("PasskeyBoundary", ctx)}
}

func (_c *MockService_PasskeyBoundary_Call) Run(run func(ctx context.Context)) *MockService_PasskeyBoundary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_PasskeyBoundary_Call) Return(rpID string, origins []string) *MockService_PasskeyBoundary_Call {
	_c.Call.Return(rpID, origins)
	return _c
}

func (_c *MockService_PasskeyBoundary_Call) RunAndReturn(run func(ctx context.Context) (string, []string)) *MockService_PasskeyBoundary_Call {
	_c.Call.Return(run)
	return _c
}

// PasskeyLoginBegin provides a mock function for the type MockService
func (_mock *MockService) PasskeyLoginBegin(rpID string, origin string) (model.PasskeyLoginBeginResp, error) {
	ret := _mock.Called(rpID, origin)

	if len(ret) == 0 {
		panic("no return value specified for PasskeyLoginBegin")
	}

	var r0 model.PasskeyLoginBeginResp
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (model.PasskeyLoginBeginResp, error)); ok {
		return returnFunc(rpID, origin)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) model.PasskeyLoginBeginResp); ok {
		r0 = returnFunc(rpID, origin)
	} else {
		r0 = ret.Get(0).(model.PasskeyLoginBeginResp)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(rpID, origin)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_PasskeyLoginBegin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PasskeyLoginBegin'
type MockService_PasskeyLoginBegin_Call struct {
	*mock.Call
}

// PasskeyLoginBegin is a helper method to define mock.On call
//   - rpID string
//   - origin string
func (_e *MockService_Expecter) PasskeyLoginBegin(rpID any, origin any) *MockService_PasskeyLoginBegin_Call {
	return &MockService_PasskeyLoginBegin_Call{Call: _e.mock.On("PasskeyLoginBegin", rpID, origin)}
}

func (_c *MockService_PasskeyLoginBegin_Call) Run(run func(rpID string, origin string)) *MockService_PasskeyLoginBegin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_PasskeyLoginBegin_Call) Return(passkeyLoginBeginResp model.PasskeyLoginBeginResp, err error) *MockService_PasskeyLoginBegin_Call {
	_c.Call.Return(passkeyLoginBeginResp, err)
	return _c
}

func (_c *MockService_PasskeyLoginBegin_Call) RunAndReturn(run func(rpID string, origin string) (model.PasskeyLoginBeginResp, error)) *MockService_PasskeyLoginBegin_Call {
	_c.Call.Return(run)
	return _c
}

// PasskeyLoginFinish provides a mock function for the type MockService
func (_mock *MockService) PasskeyLoginFinish(rpID string, origin string, nonce string, credential json.RawMessage) (*model.TokenPair, error) {
	ret := _mock.Called(rpID, origin, nonce, credential)

	if len(ret) == 0 {
		panic("no return value specified for PasskeyLoginFinish")
	}

	var r0 *model.TokenPair
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string, json.RawMessage) (*model.TokenPair, error)); ok {
		return returnFunc(rpID, origin, nonce, credential)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string, json.RawMessage) *model.TokenPair); ok {
		r0 = returnFunc(rpID, origin, nonce, credential)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TokenPair)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string, json.RawMessage) error); ok {
		r1 = returnFunc(rpID, origin, nonce, credential)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_PasskeyLoginFinish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PasskeyLoginFinish'
type MockService_PasskeyLoginFinish_Call struct {
	*mock.Call
}

// PasskeyLoginFinish is a helper method to define mock.On call
//   - rpID string
//   - origin string
//   - nonce string
//   - credential json.RawMessage
func (_e *MockService_Expecter) PasskeyLoginFinish(rpID any, origin any, nonce any, credential any) *MockService_PasskeyLoginFinish_Call {
	return &MockService_PasskeyLoginFinish_Call{Call: _e.mock.On("PasskeyLoginFinish", rpID, origin, nonce, credential)}
}

func (_c *MockService_PasskeyLoginFinish_Call) Run(run func(rpID string, origin string, nonce string, credential json.RawMessage)) *MockService_PasskeyLoginFinish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 json.RawMessage
		if args[3] != nil {
			arg3 = args[3].(json.RawMessage)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_PasskeyLoginFinish_Call) Return(tokenPair *model.TokenPair, err error) *MockService_PasskeyLoginFinish_Call {
	_c.Call.Return(tokenPair, err)
	return _c
}

func (_c *MockService_PasskeyLoginFinish_Call) RunAndReturn(run func(rpID string, origin string, nonce string, credential json.RawMessage) (*model.TokenPair, error)) *MockService_PasskeyLoginFinish_Call {
	_c.Call.Return(run)
	return _c
}

// PasskeyRegisterBegin provides a mock function for the type MockService
func (_mock *MockService) PasskeyRegisterBegin(ctx context.Context, rpID string, origin string, deviceName string) (model.PasskeyRegisterBeginResp, error) {
	ret := _mock.Called(ctx, rpID, origin, deviceName)

	if len(ret) == 0 {
		panic("no return value specified for PasskeyRegisterBegin")
	}

	var r0 model.PasskeyRegisterBeginResp
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (model.PasskeyRegisterBeginResp, error)); ok {
		return returnFunc(ctx, rpID, origin, deviceName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) model.PasskeyRegisterBeginResp); ok {
		r0 = returnFunc(ctx, rpID, origin, deviceName)
	} else {
		r0 = ret.Get(0).(model.PasskeyRegisterBeginResp)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, rpID, origin, deviceName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_PasskeyRegisterBegin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PasskeyRegisterBegin'
type MockService_PasskeyRegisterBegin_Call struct {
	*mock.Call
}

// PasskeyRegisterBegin is a helper method to define mock.On call
//   - ctx context.Context
//   - rpID string
//   - origin string
//   - deviceName string
func (_e *MockService_Expecter) PasskeyRegisterBegin(ctx any, rpID any, origin any, deviceName any) *MockService_PasskeyRegisterBegin_Call {
	return &MockService_PasskeyRegisterBegin_Call{Call: _e.mock.On("PasskeyRegisterBegin", ctx, rpID, origin, deviceName)}
}

func (_c *MockService_PasskeyRegisterBegin_Call) Run(run func(ctx context.Context, rpID string, origin string, deviceName string)) *MockService_PasskeyRegisterBegin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_PasskeyRegisterBegin_Call) Return(passkeyRegisterBeginResp model.PasskeyRegisterBeginResp, err error) *MockService_PasskeyRegisterBegin_Call {
	_c.Call.Return(passkeyRegisterBeginResp, err)
	return _c
}

func (_c *MockService_PasskeyRegisterBegin_Call) RunAndReturn(run func(ctx context.Context, rpID string, origin string, deviceName string) (model.PasskeyRegisterBeginResp, error)) *MockService_PasskeyRegisterBegin_Call {
	_c.Call.Return(run)
	return _c
}

// PasskeyRegisterFinish provides a mock function for the type MockService
func (_mock *MockService) PasskeyRegisterFinish(ctx context.Context, rpID string, origin string, nonce string, credential json.RawMessage) error {
	ret := _mock.Called(ctx, rpID, origin, nonce, credential)

	if len(ret) == 0 {
		panic("no return value specified for PasskeyRegisterFinish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, json.RawMessage) error); ok {
		r0 = returnFunc(ctx, rpID, origin, nonce, credential)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_PasskeyRegisterFinish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PasskeyRegisterFinish'
type MockService_PasskeyRegisterFinish_Call struct {
	*mock.Call
}

// PasskeyRegisterFinish is a helper method to define mock.On call
//   - ctx context.Context
//   - rpID string
//   - origin string
//   - nonce string
//   - credential json.RawMessage
func (_e *MockService_Expecter) PasskeyRegisterFinish(ctx any, rpID any, origin any, nonce any, credential any) *MockService_PasskeyRegisterFinish_Call {
	return &MockService_PasskeyRegisterFinish_Call{Call: _e.mock.On("PasskeyRegisterFinish", ctx, rpID, origin, nonce, credential)}
}

func (_c *MockService_PasskeyRegisterFinish_Call) Run(run func(ctx context.Context, rpID string, origin string, nonce string, credential json.RawMessage)) *MockService_PasskeyRegisterFinish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 json.RawMessage
		if args[4] != nil {
			arg4 = args[4].(json.RawMessage)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockService_PasskeyRegisterFinish_Call) Return(err error) *MockService_PasskeyRegisterFinish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_PasskeyRegisterFinish_Call) RunAndReturn(run func(ctx context.Context, rpID string, origin string, nonce string, credential json.RawMessage) error) *MockService_PasskeyRegisterFinish_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeToken provides a mock function for the type MockService
func (_mock *MockService) RevokeToken(jti string, remainTTL time.Duration) {
	_mock.Called(jti, remainTTL)
	return
}

// MockService_RevokeToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeToken'
type MockService_RevokeToken_Call struct {
	*mock.Call
}

// RevokeToken is a helper method to define mock.On call
//   - jti string
//   - remainTTL time.Duration
func (_e *MockService_Expecter) RevokeToken(jti any, remainTTL any) *MockService_RevokeToken_Call {
	return &MockService_RevokeToken_Call{Call: _e.mock.On("RevokeToken", jti, remainTTL)}
}

func (_c *MockService_RevokeToken_Call) Run(run func(jti string, remainTTL time.Duration)) *MockService_RevokeToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_RevokeToken_Call) Return() *MockService_RevokeToken_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_RevokeToken_Call) RunAndReturn(run func(jti string, remainTTL time.Duration)) *MockService_RevokeToken_Call {
	_c.Run(run)
	return _c
}

// UpdatePasskeyDeviceName provides a mock function for the type MockService
func (_mock *MockService) UpdatePasskeyDeviceName(ctx context.Context, passkeyID string, deviceName string) error {
	ret := _mock.Called(ctx, passkeyID, deviceName)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePasskeyDeviceName")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, passkeyID, deviceName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_UpdatePasskeyDeviceName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePasskeyDeviceName'
type MockService_UpdatePasskeyDeviceName_Call struct {
	*mock.Call
}

// UpdatePasskeyDeviceName is a helper method to define mock.On call
//   - ctx context.Context
//   - passkeyID string
//   - deviceName string
func (_e *MockService_Expecter) UpdatePasskeyDeviceName(ctx any, passkeyID any, deviceName any) *MockService_UpdatePasskeyDeviceName_Call {
	return &MockService_UpdatePasskeyDeviceName_Call{Call: _e.mock.On("UpdatePasskeyDeviceName", ctx, passkeyID, deviceName)}
}

func (_c *MockService_UpdatePasskeyDeviceName_Call) Run(run func(ctx context.Context, passkeyID string, deviceName string)) *MockService_UpdatePasskeyDeviceName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_UpdatePasskeyDeviceName_Call) Return(err error) *MockService_UpdatePasskeyDeviceName_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_UpdatePasskeyDeviceName_Call) RunAndReturn(run func(ctx context.Context, passkeyID string, deviceName string) error) *MockService_UpdatePasskeyDeviceName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// BindOAuth provides a mock function for the type MockRepository
func (_mock *MockRepository) BindOAuth(ctx context.Context, userID string, provider string, oauthID string, issuer string, authType string) error {
	ret := _mock.Called(ctx, userID, provider, oauthID, issuer, authType)

	if len(ret) == 0 {
		panic("no return value specified for BindOAuth")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, userID, provider, oauthID, issuer, authType)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_BindOAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BindOAuth'
type MockRepository_BindOAuth_Call struct {
	*mock.Call
}

// BindOAuth is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - provider string
//   - oauthID string
//   - issuer string
//   - authType string
func (_e *MockRepository_Expecter) BindOAuth(ctx any, userID any, provider any, oauthID any, issuer any, authType any) *MockRepository_BindOAuth_Call {
	return &MockRepository_BindOAuth_Call{Call: _e.mock.On("BindOAuth", ctx, userID, provider, oauthID, issuer, authType)}
}

func (_c *MockRepository_BindOAuth_Call) Run(run func(ctx context.Context, userID string, provider string, oauthID string, issuer string, authType string)) *MockRepository_BindOAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockRepository_BindOAuth_Call) Return(err error) *MockRepository_BindOAuth_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_BindOAuth_Call) RunAndReturn(run func(ctx context.Context, userID string, provider string, oauthID string, issuer string, authType string) error) *MockRepository_BindOAuth_Call {
	_c.Call.Return(run)
	return _c
}

// CacheDeletePasskeySession provides a mock function for the type MockRepository
func (_mock *MockRepository) CacheDeletePasskeySession(key string) {
	_mock.Called(key)
	return
}

// MockRepository_CacheDeletePasskeySession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CacheDeletePasskeySession'
type MockRepository_CacheDeletePasskeySession_Call struct {
	*mock.Call
}

// CacheDeletePasskeySession is a helper method to define mock.On call
//   - key string
func (_e *MockRepository_Expecter) CacheDeletePasskeySession(key any) *MockRepository_CacheDeletePasskeySession_Call {
	return &MockRepository_CacheDeletePasskeySession_Call{Call: _e.mock.On("CacheDeletePasskeySession", key)}
}

func (_c *MockRepository_CacheDeletePasskeySession_Call) Run(run func(key string)) *MockRepository_CacheDeletePasskeySession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_CacheDeletePasskeySession_Call) Return() *MockRepository_CacheDeletePasskeySession_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRepository_CacheDeletePasskeySession_Call) RunAndReturn(run func(key string)) *MockRepository_CacheDeletePasskeySession_Call {
	_c.Run(run)
	return _c
}

// CacheGetPasskeySession provides a mock function for the type MockRepository
func (_mock *MockRepository) CacheGetPasskeySession(key string) (any, error) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for CacheGetPasskeySession")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (any, error)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) any); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_CacheGetPasskeySession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CacheGetPasskeySession'
type MockRepository_CacheGetPasskeySession_Call struct {
	*mock.Call
}

// CacheGetPasskeySession is a helper method to define mock.On call
//   - key string
func (_e *MockRepository_Expecter) CacheGetPasskeySession(key any) *MockRepository_CacheGetPasskeySession_Call {
	return &MockRepository_CacheGetPasskeySession_Call{Call: _e.mock.On("CacheGetPasskeySession", key)}
}

func (_c *MockRepository_CacheGetPasskeySession_Call) Run(run func(key string)) *MockRepository_CacheGetPasskeySession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_CacheGetPasskeySession_Call) Return(v any, err error) *MockRepository_CacheGetPasskeySession_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockRepository_CacheGetPasskeySession_Call) RunAndReturn(run func(key string) (any, error)) *MockRepository_CacheGetPasskeySession_Call {
	_c.Call.Return(run)
	return _c
}

// CacheSetPasskeySession provides a mock function for the type MockRepository
func (_mock *MockRepository) CacheSetPasskeySession(key string, val any, ttl time.Duration) {
	_mock.Called(key, val, ttl)
	return
}

// MockRepository_CacheSetPasskeySession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CacheSetPasskeySession'
type MockRepository_CacheSetPasskeySession_Call struct {
	*mock.Call
}

// CacheSetPasskeySession is a helper method to define mock.On call
//   - key string
//   - val any
//   - ttl time.Duration
func (_e *MockRepository_Expecter) CacheSetPasskeySession(key any, val any, ttl any) *MockRepository_CacheSetPasskeySession_Call {
	return &MockRepository_CacheSetPasskeySession_Call{Call: _e.mock.On("CacheSetPasskeySession", key, val, ttl)}
}

func (_c *MockRepository_CacheSetPasskeySession_Call) Run(run func(key string, val any, ttl time.Duration)) *MockRepository_CacheSetPasskeySession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_CacheSetPasskeySession_Call) Return() *MockRepository_CacheSetPasskeySession_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRepository_CacheSetPasskeySession_Call) RunAndReturn(run func(key string, val any, ttl time.Duration)) *MockRepository_CacheSetPasskeySession_Call {
	_c.Run(run)
	return _c
}

// CreatePasskey provides a mock function for the type MockRepository
func (_mock *MockRepository) CreatePasskey(ctx context.Context, passkey *model.Passkey) error {
	ret := _mock.Called(ctx, passkey)

	if len(ret) == 0 {
		panic("no return value specified for CreatePasskey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.Passkey) error); ok {
		r0 = returnFunc(ctx, passkey)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_CreatePasskey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePasskey'
type MockRepository_CreatePasskey_Call struct {
	*mock.Call
}

// CreatePasskey is a helper method to define mock.On call
//   - ctx context.Context
//   - passkey *model.Passkey
func (_e *MockRepository_Expecter) CreatePasskey(ctx any, passkey any) *MockRepository_CreatePasskey_Call {
	return &MockRepository_CreatePasskey_Call{Call: _e.mock.On("CreatePasskey", ctx, passkey)}
}

func (_c *MockRepository_CreatePasskey_Call) Run(run func(ctx context.Context, passkey *model.Passkey)) *MockRepository_CreatePasskey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.Passkey
		if args[1] != nil {
			arg1 = args[1].(*model.Passkey)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_CreatePasskey_Call) Return(err error) *MockRepository_CreatePasskey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_CreatePasskey_Call) RunAndReturn(run func(ctx context.Context, passkey *model.Passkey) error) *MockRepository_CreatePasskey_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePasskeyByID provides a mock function for the type MockRepository
func (_mock *MockRepository) DeletePasskeyByID(ctx context.Context, userID string, passkeyID string) error {
	ret := _mock.Called(ctx, userID, passkeyID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePasskeyByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, userID, passkeyID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DeletePasskeyByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePasskeyByID'
type MockRepository_DeletePasskeyByID_Call struct {
	*mock.Call
}

// DeletePasskeyByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - passkeyID string
func (_e *MockRepository_Expecter) DeletePasskeyByID(ctx any, userID any, passkeyID any) *MockRepository_DeletePasskeyByID_Call {
	return &MockRepository_DeletePasskeyByID_Call{Call: _e.mock.On("DeletePasskeyByID", ctx, userID, passkeyID)}
}

func (_c *MockRepository_DeletePasskeyByID_Call) Run(run func(ctx context.Context, userID string, passkeyID string)) *MockRepository_DeletePasskeyByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_DeletePasskeyByID_Call) Return(err error) *MockRepository_DeletePasskeyByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DeletePasskeyByID_Call) RunAndReturn(run func(ctx context.Context, userID string, passkeyID string) error) *MockRepository_DeletePasskeyByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetOAuthInfo provides a mock function for the type MockRepository
func (_mock *MockRepository) GetOAuthInfo(userId string, provider string) (model0.UserExternalIdentity, error) {
	ret := _mock.Called(userId, provider)

	if len(ret) == 0 {
		panic("no return value specified for GetOAuthInfo")
	}

	var r0 model0.UserExternalIdentity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (model0.UserExternalIdentity, error)); ok {
		return returnFunc(userId, provider)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) model0.UserExternalIdentity); ok {
		r0 = returnFunc(userId, provider)
	} else {
		r0 = ret.Get(0).(model0.UserExternalIdentity)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(userId, provider)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetOAuthInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOAuthInfo'
type MockRepository_GetOAuthInfo_Call struct {
	*mock.Call
}

// GetOAuthInfo is a helper method to define mock.On call
//   - userId string
//   - provider string
func (_e *MockRepository_Expecter) GetOAuthInfo(userId any, provider any) *MockRepository_GetOAuthInfo_Call {
	return &MockRepository_GetOAuthInfo_Call{Call: _e.mock.On("GetOAuthInfo", userId, provider)}
}

func (_c *MockRepository_GetOAuthInfo_Call) Run(run func(userId string, provider string)) *MockRepository_GetOAuthInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetOAuthInfo_Call) Return(userExternalIdentity model0.UserExternalIdentity, err error) *MockRepository_GetOAuthInfo_Call {
	_c.Call.Return(userExternalIdentity, err)
	return _c
}

func (_c *MockRepository_GetOAuthInfo_Call) RunAndReturn(run func(userId string, provider string) (model0.UserExternalIdentity, error)) *MockRepository_GetOAuthInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetOAuthOIDCInfo provides a mock function for the type MockRepository
func (_mock *MockRepository) GetOAuthOIDCInfo(userId string, provider string, issuer string) (model0.UserExternalIdentity, error) {
	ret := _mock.Called(userId, provider, issuer)

	if len(ret) == 0 {
		panic("no return value specified for GetOAuthOIDCInfo")
	}

	var r0 model0.UserExternalIdentity
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) (model0.UserExternalIdentity, error)); ok {
		return returnFunc(userId, provider, issuer)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string) model0.UserExternalIdentity); ok {
		r0 = returnFunc(userId, provider, issuer)
	} else {
		r0 = ret.Get(0).(model0.UserExternalIdentity)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = returnFunc(userId, provider, issuer)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetOAuthOIDCInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOAuthOIDCInfo'
type MockRepository_GetOAuthOIDCInfo_Call struct {
	*mock.Call
}

// GetOAuthOIDCInfo is a helper method to define mock.On call
//   - userId string
//   - provider string
//   - issuer string
func (_e *MockRepository_Expecter) GetOAuthOIDCInfo(userId any, provider any, issuer any) *MockRepository_GetOAuthOIDCInfo_Call {
	return &MockRepository_GetOAuthOIDCInfo_Call{Call: _e.mock.On("GetOAuthOIDCInfo", userId, provider, issuer)}
}

func (_c *MockRepository_GetOAuthOIDCInfo_Call) Run(run func(userId string, provider string, issuer string)) *MockRepository_GetOAuthOIDCInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_GetOAuthOIDCInfo_Call) Return(userExternalIdentity model0.UserExternalIdentity, err error) *MockRepository_GetOAuthOIDCInfo_Call {
	_c.Call.Return(userExternalIdentity, err)
	return _c
}

func (_c *MockRepository_GetOAuthOIDCInfo_Call) RunAndReturn(run func(userId string, provider string, issuer string) (model0.UserExternalIdentity, error)) *MockRepository_GetOAuthOIDCInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetPasskeyByCredentialID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetPasskeyByCredentialID(credentialID string) (model.Passkey, error) {
	ret := _mock.Called(credentialID)

	if len(ret) == 0 {
		panic("no return value specified for GetPasskeyByCredentialID")
	}

	var r0 model.Passkey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (model.Passkey, error)); ok {
		return returnFunc(credentialID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) model.Passkey); ok {
		r0 = returnFunc(credentialID)
	} else {
		r0 = ret.Get(0).(model.Passkey)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(credentialID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetPasskeyByCredentialID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPasskeyByCredentialID'
type MockRepository_GetPasskeyByCredentialID_Call struct {
	*mock.Call
}

// GetPasskeyByCredentialID is a helper method to define mock.On call
//   - credentialID string
func (_e *MockRepository_Expecter) GetPasskeyByCredentialID(credentialID any) *MockRepository_GetPasskeyByCredentialID_Call {
	return &MockRepository_GetPasskeyByCredentialID_Call{Call: _e.mock.On("GetPasskeyByCredentialID", credentialID)}
}

func (_c *MockRepository_GetPasskeyByCredentialID_Call) Run(run func(credentialID string)) *MockRepository_GetPasskeyByCredentialID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_GetPasskeyByCredentialID_Call) Return(passkey model.Passkey, err error) *MockRepository_GetPasskeyByCredentialID_Call {
	_c.Call.Return(passkey, err)
	return _c
}

func (_c *MockRepository_GetPasskeyByCredentialID_Call) RunAndReturn(run func(credentialID string) (model.Passkey, error)) *MockRepository_GetPasskeyByCredentialID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetUserByID(ctx context.Context, id string) (model0.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 model0.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model0.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model0.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(model0.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockRepository_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockRepository_Expecter) GetUserByID(ctx any, id any) *MockRepository_GetUserByID_Call {
	return &MockRepository_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *MockRepository_GetUserByID_Call) Run(run func(ctx context.Context, id string)) *MockRepository_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetUserByID_Call) Return(user model0.User, err error) *MockRepository_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockRepository_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, id string) (model0.User, error)) *MockRepository_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByOAuthID provides a mock function for the type MockRepository
func (_mock *MockRepository) GetUserByOAuthID(ctx context.Context, provider string, oauthID string) (model0.User, error) {
	ret := _mock.Called(ctx, provider, oauthID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByOAuthID")
	}

	var r0 model0.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (model0.User, error)); ok {
		return returnFunc(ctx, provider, oauthID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) model0.User); ok {
		r0 = returnFunc(ctx, provider, oauthID)
	} else {
		r0 = ret.Get(0).(model0.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, provider, oauthID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetUserByOAuthID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByOAuthID'
type MockRepository_GetUserByOAuthID_Call struct {
	*mock.Call
}

// GetUserByOAuthID is a helper method to define mock.On call
//   - ctx context.Context
//   - provider string
//   - oauthID string
func (_e *MockRepository_Expecter) GetUserByOAuthID(ctx any, provider any, oauthID any) *MockRepository_GetUserByOAuthID_Call {
	return &MockRepository_GetUserByOAuthID_Call{Call: _e.mock.On("GetUserByOAuthID", ctx, provider, oauthID)}
}

func (_c *MockRepository_GetUserByOAuthID_Call) Run(run func(ctx context.Context, provider string, oauthID string)) *MockRepository_GetUserByOAuthID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_GetUserByOAuthID_Call) Return(user model0.User, err error) *MockRepository_GetUserByOAuthID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockRepository_GetUserByOAuthID_Call) RunAndReturn(run func(ctx context.Context, provider string, oauthID string) (model0.User, error)) *MockRepository_GetUserByOAuthID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByOIDC provides a mock function for the type MockRepository
func (_mock *MockRepository) GetUserByOIDC(ctx context.Context, provider string, oauthID string, issuer string) (model0.User, error) {
	ret := _mock.Called(ctx, provider, oauthID, issuer)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByOIDC")
	}

	var r0 model0.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (model0.User, error)); ok {
		return returnFunc(ctx, provider, oauthID, issuer)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) model0.User); ok {
		r0 = returnFunc(ctx, provider, oauthID, issuer)
	} else {
		r0 = ret.Get(0).(model0.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, provider, oauthID, issuer)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetUserByOIDC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByOIDC'
type MockRepository_GetUserByOIDC_Call struct {
	*mock.Call
}

// GetUserByOIDC is a helper method to define mock.On call
//   - ctx context.Context
//   - provider string
//   - oauthID string
//   - issuer string
func (_e *MockRepository_Expecter) GetUserByOIDC(ctx any, provider any, oauthID any, issuer any) *MockRepository_GetUserByOIDC_Call {
	return &MockRepository_GetUserByOIDC_Call{Call: _e.mock.On("GetUserByOIDC", ctx, provider, oauthID, issuer)}
}

func (_c *MockRepository_GetUserByOIDC_Call) Run(run func(ctx context.Context, provider string, oauthID string, issuer string)) *MockRepository_GetUserByOIDC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_GetUserByOIDC_Call) Return(user model0.User, err error) *MockRepository_GetUserByOIDC_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockRepository_GetUserByOIDC_Call) RunAndReturn(run func(ctx context.Context, provider string, oauthID string, issuer string) (model0.User, error)) *MockRepository_GetUserByOIDC_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByUsername provides a mock function for the type MockRepository
func (_mock *MockRepository) GetUserByUsername(ctx context.Context, username string) (model0.User, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUsername")
	}

	var r0 model0.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model0.User, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model0.User); ok {
		r0 = returnFunc(ctx, username)
	} else {
		r0 = ret.Get(0).(model0.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetUserByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByUsername'
type MockRepository_GetUserByUsername_Call struct {
	*mock.Call
}

// GetUserByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockRepository_Expecter) GetUserByUsername(ctx any, username any) *MockRepository_GetUserByUsername_Call {
	return &MockRepository_GetUserByUsername_Call{Call: _e.mock.On("GetUserByUsername", ctx, username)}
}

func (_c *MockRepository_GetUserByUsername_Call) Run(run func(ctx context.Context, username string)) *MockRepository_GetUserByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetUserByUsername_Call) Return(user model0.User, err error) *MockRepository_GetUserByUsername_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockRepository_GetUserByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (model0.User, error)) *MockRepository_GetUserByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// ListPasskeysByUserID provides a mock function for the type MockRepository
func (_mock *MockRepository) ListPasskeysByUserID(userID string) ([]model.Passkey, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for ListPasskeysByUserID")
	}

	var r0 []model.Passkey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]model.Passkey, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []model.Passkey); ok {
		r0 = returnFunc(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Passkey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ListPasskeysByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPasskeysByUserID'
type MockRepository_ListPasskeysByUserID_Call struct {
	*mock.Call
}

// ListPasskeysByUserID is a helper method to define mock.On call
//   - userID string
func (_e *MockRepository_Expecter) ListPasskeysByUserID(userID any) *MockRepository_ListPasskeysByUserID_Call {
	return &MockRepository_ListPasskeysByUserID_Call{Call: _e.mock.On("ListPasskeysByUserID", userID)}
}

func (_c *MockRepository_ListPasskeysByUserID_Call) Run(run func(userID string)) *MockRepository_ListPasskeysByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_ListPasskeysByUserID_Call) Return(passkeys []model.Passkey, err error) *MockRepository_ListPasskeysByUserID_Call {
	_c.Call.Return(passkeys, err)
	return _c
}

func (_c *MockRepository_ListPasskeysByUserID_Call) RunAndReturn(run func(userID string) ([]model.Passkey, error)) *MockRepository_ListPasskeysByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePasskeyDeviceName provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdatePasskeyDeviceName(ctx context.Context, userID string, passkeyID string, deviceName string) error {
	ret := _mock.Called(ctx, userID, passkeyID, deviceName)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePasskeyDeviceName")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, userID, passkeyID, deviceName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdatePasskeyDeviceName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePasskeyDeviceName'
type MockRepository_UpdatePasskeyDeviceName_Call struct {
	*mock.Call
}

// UpdatePasskeyDeviceName is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - passkeyID string
//   - deviceName string
func (_e *MockRepository_Expecter) UpdatePasskeyDeviceName(ctx any, userID any, passkeyID any, deviceName any) *MockRepository_UpdatePasskeyDeviceName_Call {
	return &MockRepository_UpdatePasskeyDeviceName_Call{Call: _e.mock.On("UpdatePasskeyDeviceName", ctx, userID, passkeyID, deviceName)}
}

func (_c *MockRepository_UpdatePasskeyDeviceName_Call) Run(run func(ctx context.Context, userID string, passkeyID string, deviceName string)) *MockRepository_UpdatePasskeyDeviceName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_UpdatePasskeyDeviceName_Call) Return(err error) *MockRepository_UpdatePasskeyDeviceName_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdatePasskeyDeviceName_Call) RunAndReturn(run func(ctx context.Context, userID string, passkeyID string, deviceName string) error) *MockRepository_UpdatePasskeyDeviceName_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePasskeyUsage provides a mock function for the type MockRepository
func (_mock *MockRepository) UpdatePasskeyUsage(ctx context.Context, passkeyID string, signCount uint32, lastUsedAt int64) error {
	ret := _mock.Called(ctx, passkeyID, signCount, lastUsedAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePasskeyUsage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, uint32, int64) error); ok {
		r0 = returnFunc(ctx, passkeyID, signCount, lastUsedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_UpdatePasskeyUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePasskeyUsage'
type MockRepository_UpdatePasskeyUsage_Call struct {
	*mock.Call
}

// UpdatePasskeyUsage is a helper method to define mock.On call
//   - ctx context.Context
//   - passkeyID string
//   - signCount uint32
//   - lastUsedAt int64
func (_e *MockRepository_Expecter) UpdatePasskeyUsage(ctx any, passkeyID any, signCount any, lastUsedAt any) *MockRepository_UpdatePasskeyUsage_Call {
	return &MockRepository_UpdatePasskeyUsage_Call{Call: _e.mock.On("UpdatePasskeyUsage", ctx, passkeyID, signCount, lastUsedAt)}
}

func (_c *MockRepository_UpdatePasskeyUsage_Call) Run(run func(ctx context.Context, passkeyID string, signCount uint32, lastUsedAt int64)) *MockRepository_UpdatePasskeyUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 uint32
		if args[2] != nil {
			arg2 = args[2].(uint32)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_UpdatePasskeyUsage_Call) Return(err error) *MockRepository_UpdatePasskeyUsage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_UpdatePasskeyUsage_Call) RunAndReturn(run func(ctx context.Context, passkeyID string, signCount uint32, lastUsedAt int64) error) *MockRepository_UpdatePasskeyUsage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthRepo creates a new instance of MockAuthRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthRepo {
	mock := &MockAuthRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthRepo is an autogenerated mock type for the AuthRepo type
type MockAuthRepo struct {
	mock.Mock
}

type MockAuthRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthRepo) EXPECT() *MockAuthRepo_Expecter {
	return &MockAuthRepo_Expecter{mock: &_m.Mock}
}

// GetAndDeleteOAuthCode provides a mock function for the type MockAuthRepo
func (_mock *MockAuthRepo) GetAndDeleteOAuthCode(code string) (*model.TokenPair, error) {
	ret := _mock.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for GetAndDeleteOAuthCode")
	}

	var r0 *model.TokenPair
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*model.TokenPair, error)); ok {
		return returnFunc(code)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *model.TokenPair); ok {
		r0 = returnFunc(code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TokenPair)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepo_GetAndDeleteOAuthCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAndDeleteOAuthCode'
type MockAuthRepo_GetAndDeleteOAuthCode_Call struct {
	*mock.Call
}

// GetAndDeleteOAuthCode is a helper method to define mock.On call
//   - code string
func (_e *MockAuthRepo_Expecter) GetAndDeleteOAuthCode(code any) *MockAuthRepo_GetAndDeleteOAuthCode_Call {
	return &MockAuthRepo_GetAndDeleteOAuthCode_Call{Call: _e.mock.On("GetAndDeleteOAuthCode", code)}
}

func (_c *MockAuthRepo_GetAndDeleteOAuthCode_Call) Run(run func(code string)) *MockAuthRepo_GetAndDeleteOAuthCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthRepo_GetAndDeleteOAuthCode_Call) Return(tokenPair *model.TokenPair, err error) *MockAuthRepo_GetAndDeleteOAuthCode_Call {
	_c.Call.Return(tokenPair, err)
	return _c
}

func (_c *MockAuthRepo_GetAndDeleteOAuthCode_Call) RunAndReturn(run func(code string) (*model.TokenPair, error)) *MockAuthRepo_GetAndDeleteOAuthCode_Call {
	_c.Call.Return(run)
	return _c
}

// IsTokenRevoked provides a mock function for the type MockAuthRepo
func (_mock *MockAuthRepo) IsTokenRevoked(jti string) bool {
	ret := _mock.Called(jti)

	if len(ret) == 0 {
		panic("no return value specified for IsTokenRevoked")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(jti)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockAuthRepo_IsTokenRevoked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsTokenRevoked'
type MockAuthRepo_IsTokenRevoked_Call struct {
	*mock.Call
}

// IsTokenRevoked is a helper method to define mock.On call
//   - jti string
func (_e *MockAuthRepo_Expecter) IsTokenRevoked(jti any) *MockAuthRepo_IsTokenRevoked_Call {
	return &MockAuthRepo_IsTokenRevoked_Call{Call: _e.mock.On("IsTokenRevoked", jti)}
}

func (_c *MockAuthRepo_IsTokenRevoked_Call) Run(run func(jti string)) *MockAuthRepo_IsTokenRevoked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthRepo_IsTokenRevoked_Call) Return(b bool) *MockAuthRepo_IsTokenRevoked_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockAuthRepo_IsTokenRevoked_Call) RunAndReturn(run func(jti string) bool) *MockAuthRepo_IsTokenRevoked_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeToken provides a mock function for the type MockAuthRepo
func (_mock *MockAuthRepo) RevokeToken(jti string, remainTTL time.Duration) {
	_mock.Called(jti, remainTTL)
	return
}

// MockAuthRepo_RevokeToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeToken'
type MockAuthRepo_RevokeToken_Call struct {
	*mock.Call
}

// RevokeToken is a helper method to define mock.On call
//   - jti string
//   - remainTTL time.Duration
func (_e *MockAuthRepo_Expecter) RevokeToken(jti any, remainTTL any) *MockAuthRepo_RevokeToken_Call {
	return &MockAuthRepo_RevokeToken_Call{Call: _e.mock.On("RevokeToken", jti, remainTTL)}
}

func (_c *MockAuthRepo_RevokeToken_Call) Run(run func(jti string, remainTTL time.Duration)) *MockAuthRepo_RevokeToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepo_RevokeToken_Call) Return() *MockAuthRepo_RevokeToken_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAuthRepo_RevokeToken_Call) RunAndReturn(run func(jti string, remainTTL time.Duration)) *MockAuthRepo_RevokeToken_Call {
	_c.Run(run)
	return _c
}

// StoreOAuthCode provides a mock function for the type MockAuthRepo
func (_mock *MockAuthRepo) StoreOAuthCode(code string, pair *model.TokenPair, ttl time.Duration) {
	_mock.Called(code, pair, ttl)
	return
}

// MockAuthRepo_StoreOAuthCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreOAuthCode'
type MockAuthRepo_StoreOAuthCode_Call struct {
	*mock.Call
}

// StoreOAuthCode is a helper method to define mock.On call
//   - code string
//   - pair *model.TokenPair
//   - ttl time.Duration
func (_e *MockAuthRepo_Expecter) StoreOAuthCode(code any, pair any, ttl any) *MockAuthRepo_StoreOAuthCode_Call {
	return &MockAuthRepo_StoreOAuthCode_Call{Call: _e.mock.On("StoreOAuthCode", code, pair, ttl)}
}

func (_c *MockAuthRepo_StoreOAuthCode_Call) Run(run func(code string, pair *model.TokenPair, ttl time.Duration)) *MockAuthRepo_StoreOAuthCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *model.TokenPair
		if args[1] != nil {
			arg1 = args[1].(*model.TokenPair)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthRepo_StoreOAuthCode_Call) Return() *MockAuthRepo_StoreOAuthCode_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAuthRepo_StoreOAuthCode_Call) RunAndReturn(run func(code string, pair *model.TokenPair, ttl time.Duration)) *MockAuthRepo_StoreOAuthCode_Call {
	_c.Run(run)
	return _c
}
