// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2025-2026 lin-snow

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package dashboardmock

import (
	"net/http"

	"github.com/lin-snow/ech0/internal/service/dashboard"
	"github.com/lin-snow/ech0/internal/util/log"
	"github.com/lin-snow/ech0/internal/visitor"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// GetSystemLogs provides a mock function for the type MockService
func (_mock *MockService) GetSystemLogs(query service.SystemLogQuery) ([]util.LogEntry, error) {
	ret := _mock.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for GetSystemLogs")
	}

	var r0 []util.LogEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(service.SystemLogQuery) ([]util.LogEntry, error)); ok {
		return returnFunc(query)
	}
	if returnFunc, ok := ret.Get(0).(func(service.SystemLogQuery) []util.LogEntry); ok {
		r0 = returnFunc(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]util.LogEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(service.SystemLogQuery) error); ok {
		r1 = returnFunc(query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetSystemLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSystemLogs'
type MockService_GetSystemLogs_Call struct {
	*mock.Call
}

// GetSystemLogs is a helper method to define mock.On call
//   - query service.SystemLogQuery
func (_e *MockService_Expecter) GetSystemLogs(query any) *MockService_GetSystemLogs_Call {
	return &MockService_GetSystemLogs_Call{Call: _e.mock.On("GetSystemLogs", query)}
}

func (_c *MockService_GetSystemLogs_Call) Run(run func(query service.SystemLogQuery)) *MockService_GetSystemLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 service.SystemLogQuery
		if args[0] != nil {
			arg0 = args[0].(service.SystemLogQuery)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_GetSystemLogs_Call) Return(logEntrys []util.LogEntry, err error) *MockService_GetSystemLogs_Call {
	_c.Call.Return(logEntrys, err)
	return _c
}

func (_c *MockService_GetSystemLogs_Call) RunAndReturn(run func(query service.SystemLogQuery) ([]util.LogEntry, error)) *MockService_GetSystemLogs_Call {
	_c.Call.Return(run)
	return _c
}

// GetVisitorStats provides a mock function for the type MockService
func (_mock *MockService) GetVisitorStats() []visitor.DayStat {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetVisitorStats")
	}

	var r0 []visitor.DayStat
	if returnFunc, ok := ret.Get(0).(func() []visitor.DayStat); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]visitor.DayStat)
		}
	}
	return r0
}

// MockService_GetVisitorStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVisitorStats'
type MockService_GetVisitorStats_Call struct {
	*mock.Call
}

// GetVisitorStats is a helper method to define mock.On call
func (_e *MockService_Expecter) GetVisitorStats() *MockService_GetVisitorStats_Call {
	return &MockService_GetVisitorStats_Call{Call: _e.mock.On("GetVisitorStats")}
}

func (_c *MockService_GetVisitorStats_Call) Run(run func()) *MockService_GetVisitorStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_GetVisitorStats_Call) Return(dayStats []visitor.DayStat) *MockService_GetVisitorStats_Call {
	_c.Call.Return(dayStats)
	return _c
}

func (_c *MockService_GetVisitorStats_Call) RunAndReturn(run func() []visitor.DayStat) *MockService_GetVisitorStats_Call {
	_c.Call.Return(run)
	return _c
}

// SSESubscribeSystemLogs provides a mock function for the type MockService
func (_mock *MockService) SSESubscribeSystemLogs(w http.ResponseWriter, r *http.Request, filter service.SystemLogStreamFilter) error {
	ret := _mock.Called(w, r, filter)

	if len(ret) == 0 {
		panic("no return value specified for SSESubscribeSystemLogs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request, service.SystemLogStreamFilter) error); ok {
		r0 = returnFunc(w, r, filter)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_SSESubscribeSystemLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SSESubscribeSystemLogs'
type MockService_SSESubscribeSystemLogs_Call struct {
	*mock.Call
}

// SSESubscribeSystemLogs is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
//   - filter service.SystemLogStreamFilter
func (_e *MockService_Expecter) SSESubscribeSystemLogs(w any, r any, filter any) *MockService_SSESubscribeSystemLogs_Call {
	return &MockService_SSESubscribeSystemLogs_Call{Call: _e.mock.On("SSESubscribeSystemLogs", w, r, filter)}
}

func (_c *MockService_SSESubscribeSystemLogs_Call) Run(run func(w http.ResponseWriter, r *http.Request, filter service.SystemLogStreamFilter)) *MockService_SSESubscribeSystemLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		var arg2 service.SystemLogStreamFilter
		if args[2] != nil {
			arg2 = args[2].(service.SystemLogStreamFilter)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_SSESubscribeSystemLogs_Call) Return(err error) *MockService_SSESubscribeSystemLogs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_SSESubscribeSystemLogs_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request, filter service.SystemLogStreamFilter) error) *MockService_SSESubscribeSystemLogs_Call {
	_c.Call.Return(run)
	return _c
}

// WSSubscribeSystemLogs provides a mock function for the type MockService
func (_mock *MockService) WSSubscribeSystemLogs(w http.ResponseWriter, r *http.Request, filter service.SystemLogStreamFilter) error {
	ret := _mock.Called(w, r, filter)

	if len(ret) == 0 {
		panic("no return value specified for WSSubscribeSystemLogs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request, service.SystemLogStreamFilter) error); ok {
		r0 = returnFunc(w, r, filter)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_WSSubscribeSystemLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WSSubscribeSystemLogs'
type MockService_WSSubscribeSystemLogs_Call struct {
	*mock.Call
}

// WSSubscribeSystemLogs is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
//   - filter service.SystemLogStreamFilter
func (_e *MockService_Expecter) WSSubscribeSystemLogs(w any, r any, filter any) *MockService_WSSubscribeSystemLogs_Call {
	return &MockService_WSSubscribeSystemLogs_Call{Call: _e.mock.On("WSSubscribeSystemLogs", w, r, filter)}
}

func (_c *MockService_WSSubscribeSystemLogs_Call) Run(run func(w http.ResponseWriter, r *http.Request, filter service.SystemLogStreamFilter)) *MockService_WSSubscribeSystemLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		var arg2 service.SystemLogStreamFilter
		if args[2] != nil {
			arg2 = args[2].(service.SystemLogStreamFilter)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_WSSubscribeSystemLogs_Call) Return(err error) *MockService_WSSubscribeSystemLogs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_WSSubscribeSystemLogs_Call) RunAndReturn(run func(w http.ResponseWriter, r *http.Request, filter service.SystemLogStreamFilter) error) *MockService_WSSubscribeSystemLogs_Call {
	_c.Call.Return(run)
	return _c
}
