// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2025-2026 lin-snow

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package copilotmock

import (
	"context"
	"net/http"

	"github.com/lin-snow/ech0/internal/service/copilot"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSummaryService creates a new instance of MockSummaryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSummaryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSummaryService {
	mock := &MockSummaryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSummaryService is an autogenerated mock type for the SummaryService type
type MockSummaryService struct {
	mock.Mock
}

type MockSummaryService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSummaryService) EXPECT() *MockSummaryService_Expecter {
	return &MockSummaryService_Expecter{mock: &_m.Mock}
}

// GetRecent provides a mock function for the type MockSummaryService
func (_mock *MockSummaryService) GetRecent(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRecent")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSummaryService_GetRecent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecent'
type MockSummaryService_GetRecent_Call struct {
	*mock.Call
}

// GetRecent is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSummaryService_Expecter) GetRecent(ctx any) *MockSummaryService_GetRecent_Call {
	return &MockSummaryService_GetRecent_Call{Call: _e.mock.On("GetRecent", ctx)}
}

func (_c *MockSummaryService_GetRecent_Call) Run(run func(ctx context.Context)) *MockSummaryService_GetRecent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSummaryService_GetRecent_Call) Return(s string, err error) *MockSummaryService_GetRecent_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockSummaryService_GetRecent_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *MockSummaryService_GetRecent_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChatService creates a new instance of MockChatService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatService {
	mock := &MockChatService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChatService is an autogenerated mock type for the ChatService type
type MockChatService struct {
	mock.Mock
}

type MockChatService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatService) EXPECT() *MockChatService_Expecter {
	return &MockChatService_Expecter{mock: &_m.Mock}
}

// AskStream provides a mock function for the type MockChatService
func (_mock *MockChatService) AskStream(ctx context.Context, question string, locale string, timezone string, w http.ResponseWriter) error {
	ret := _mock.Called(ctx, question, locale, timezone, w)

	if len(ret) == 0 {
		panic("no return value specified for AskStream")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, http.ResponseWriter) error); ok {
		r0 = returnFunc(ctx, question, locale, timezone, w)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatService_AskStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AskStream'
type MockChatService_AskStream_Call struct {
	*mock.Call
}

// AskStream is a helper method to define mock.On call
//   - ctx context.Context
//   - question string
//   - locale string
//   - timezone string
//   - w http.ResponseWriter
func (_e *MockChatService_Expecter) AskStream(ctx any, question any, locale any, timezone any, w any) *MockChatService_AskStream_Call {
	return &MockChatService_AskStream_Call{Call: _e.mock.On("AskStream", ctx, question, locale, timezone, w)}
}

func (_c *MockChatService_AskStream_Call) Run(run func(ctx context.Context, question string, locale string, timezone string, w http.ResponseWriter)) *MockChatService_AskStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 http.ResponseWriter
		if args[4] != nil {
			arg4 = args[4].(http.ResponseWriter)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockChatService_AskStream_Call) Return(err error) *MockChatService_AskStream_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatService_AskStream_Call) RunAndReturn(run func(ctx context.Context, question string, locale string, timezone string, w http.ResponseWriter) error) *MockChatService_AskStream_Call {
	_c.Call.Return(run)
	return _c
}

// ClearSession provides a mock function for the type MockChatService
func (_mock *MockChatService) ClearSession(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ClearSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatService_ClearSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearSession'
type MockChatService_ClearSession_Call struct {
	*mock.Call
}

// ClearSession is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockChatService_Expecter) ClearSession(ctx any) *MockChatService_ClearSession_Call {
	return &MockChatService_ClearSession_Call{Call: _e.mock.On("ClearSession", ctx)}
}

func (_c *MockChatService_ClearSession_Call) Run(run func(ctx context.Context)) *MockChatService_ClearSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockChatService_ClearSession_Call) Return(err error) *MockChatService_ClearSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatService_ClearSession_Call) RunAndReturn(run func(ctx context.Context) error) *MockChatService_ClearSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetSession provides a mock function for the type MockChatService
func (_mock *MockChatService) GetSession(ctx context.Context) ([]service.ChatMessage, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSession")
	}

	var r0 []service.ChatMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]service.ChatMessage, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []service.ChatMessage); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]service.ChatMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatService_GetSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSession'
type MockChatService_GetSession_Call struct {
	*mock.Call
}

// GetSession is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockChatService_Expecter) GetSession(ctx any) *MockChatService_GetSession_Call {
	return &MockChatService_GetSession_Call{Call: _e.mock.On("GetSession", ctx)}
}

func (_c *MockChatService_GetSession_Call) Run(run func(ctx context.Context)) *MockChatService_GetSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockChatService_GetSession_Call) Return(chatMessages []service.ChatMessage, err error) *MockChatService_GetSession_Call {
	_c.Call.Return(chatMessages, err)
	return _c
}

func (_c *MockChatService_GetSession_Call) RunAndReturn(run func(ctx context.Context) ([]service.ChatMessage, error)) *MockChatService_GetSession_Call {
	_c.Call.Return(run)
	return _c
}
