// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/lin-snow/ech0/internal/app"
	"github.com/lin-snow/ech0/internal/cache"
	"github.com/lin-snow/ech0/internal/database"
	"github.com/lin-snow/ech0/internal/event/bus"
	"github.com/lin-snow/ech0/internal/event/publisher"
	"github.com/lin-snow/ech0/internal/event/registry"
	"github.com/lin-snow/ech0/internal/event/subscriber"
	"github.com/lin-snow/ech0/internal/handler"
	handler15 "github.com/lin-snow/ech0/internal/handler/agent"
	handler4 "github.com/lin-snow/ech0/internal/handler/auth"
	handler12 "github.com/lin-snow/ech0/internal/handler/backup"
	handler16 "github.com/lin-snow/ech0/internal/handler/chat"
	handler7 "github.com/lin-snow/ech0/internal/handler/comment"
	handler9 "github.com/lin-snow/ech0/internal/handler/common"
	handler11 "github.com/lin-snow/ech0/internal/handler/connect"
	handler14 "github.com/lin-snow/ech0/internal/handler/dashboard"
	handler5 "github.com/lin-snow/ech0/internal/handler/echo"
	handler17 "github.com/lin-snow/ech0/internal/handler/embedding"
	handler6 "github.com/lin-snow/ech0/internal/handler/file"
	handler8 "github.com/lin-snow/ech0/internal/handler/init"
	handler13 "github.com/lin-snow/ech0/internal/handler/migration"
	handler10 "github.com/lin-snow/ech0/internal/handler/setting"
	handler3 "github.com/lin-snow/ech0/internal/handler/user"
	handler2 "github.com/lin-snow/ech0/internal/handler/web"
	"github.com/lin-snow/ech0/internal/mcp"
	"github.com/lin-snow/ech0/internal/middleware"
	"github.com/lin-snow/ech0/internal/migrator"
	repository14 "github.com/lin-snow/ech0/internal/repository"
	repository9 "github.com/lin-snow/ech0/internal/repository/auth"
	repository10 "github.com/lin-snow/ech0/internal/repository/comment"
	repository6 "github.com/lin-snow/ech0/internal/repository/common"
	repository12 "github.com/lin-snow/ech0/internal/repository/connect"
	repository4 "github.com/lin-snow/ech0/internal/repository/echo"
	repository3 "github.com/lin-snow/ech0/internal/repository/embedding"
	repository7 "github.com/lin-snow/ech0/internal/repository/file"
	repository11 "github.com/lin-snow/ech0/internal/repository/init"
	"github.com/lin-snow/ech0/internal/repository/keyvalue"
	repository2 "github.com/lin-snow/ech0/internal/repository/queue"
	repository8 "github.com/lin-snow/ech0/internal/repository/setting"
	repository5 "github.com/lin-snow/ech0/internal/repository/user"
	repository13 "github.com/lin-snow/ech0/internal/repository/visitor"
	"github.com/lin-snow/ech0/internal/repository/webhook"
	"github.com/lin-snow/ech0/internal/server"
	service15 "github.com/lin-snow/ech0/internal/service"
	service13 "github.com/lin-snow/ech0/internal/service/agent"
	"github.com/lin-snow/ech0/internal/service/auth"
	service10 "github.com/lin-snow/ech0/internal/service/backup"
	service14 "github.com/lin-snow/ech0/internal/service/chat"
	service7 "github.com/lin-snow/ech0/internal/service/comment"
	service2 "github.com/lin-snow/ech0/internal/service/common"
	service9 "github.com/lin-snow/ech0/internal/service/connect"
	service12 "github.com/lin-snow/ech0/internal/service/dashboard"
	service6 "github.com/lin-snow/ech0/internal/service/echo"
	"github.com/lin-snow/ech0/internal/service/embedding"
	service3 "github.com/lin-snow/ech0/internal/service/file"
	service8 "github.com/lin-snow/ech0/internal/service/init"
	service11 "github.com/lin-snow/ech0/internal/service/migrator"
	service4 "github.com/lin-snow/ech0/internal/service/setting"
	service5 "github.com/lin-snow/ech0/internal/service/user"
	"github.com/lin-snow/ech0/internal/storage"
	"github.com/lin-snow/ech0/internal/task"
	"github.com/lin-snow/ech0/internal/transaction"
	"github.com/lin-snow/ech0/internal/visitor"
	"github.com/lin-snow/ech0/internal/webhook"
	"github.com/lin-snow/ech0/pkg/busen"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// BuildApp 构建 Web 生命周期应用。
func BuildApp() (*app.App, error) {
	v := database.ProvideDBProvider()
	v2 := bus.ProvideProvider()
	iCache, err := cache.ProvideCache()
	if err != nil {
		return nil, err
	}
	gormTransactor := transaction.NewGormTransactor(v)
	tracker := visitor.NewTracker()
	tasker, err := BuildTasker(v, iCache, gormTransactor, v2, tracker)
	if err != nil {
		return nil, err
	}
	backupScheduleApplier := ProvideBackupScheduleApplier(tasker)
	eventRegistrar, err := BuildEventRegistrar(v, v2, iCache, gormTransactor, backupScheduleApplier)
	if err != nil {
		return nil, err
	}
	eventBus := bus.NewEventBus(v2)
	worker, err := BuildMigrator(v, iCache, gormTransactor)
	if err != nil {
		return nil, err
	}
	engine := server.ProvideGinEngine()
	bundle, err := BuildHandlers(v, iCache, gormTransactor, v2, tracker)
	if err != nil {
		return nil, err
	}
	deps, err := BuildMiddlewares(v, iCache)
	if err != nil {
		return nil, err
	}
	serverServer := server.ProvideHTTPServer(engine, bundle, deps)
	v3 := app.ProvideOptions(eventRegistrar, eventBus, tasker, worker, serverServer)
	appApp := app.NewApp(v3)
	return appApp, nil
}

func BuildEventRegistrar(dbProvider func() *gorm.DB, ebProvider func() *busen.Bus, appCache cache.ICache[string, any], tx transaction.Transactor, backupScheduleApplier subscriber.BackupScheduleApplier) (*registry.EventRegistrar, error) {
	webhookRepository := repository.NewWebhookRepository(dbProvider)
	queueRepository := repository2.NewQueueRepository(dbProvider)
	dispatcher := webhook.NewDispatcher(webhookRepository, queueRepository, tx)
	deadLetterResolver := subscriber.NewDeadLetterResolver(queueRepository, dispatcher)
	backupScheduler := subscriber.NewBackupScheduler(backupScheduleApplier)
	keyValueRepository := keyvalue.NewKeyValueRepository(dbProvider, appCache)
	agentProcessor := subscriber.NewAgentProcessor(keyValueRepository)
	embeddingRepository := repository3.NewEmbeddingRepository(dbProvider)
	echoRepository := repository4.NewEchoRepository(dbProvider, appCache)
	embeddingService := service.NewEmbeddingService(embeddingRepository, keyValueRepository, echoRepository)
	embeddingProcessor := subscriber.NewEmbeddingProcessor(embeddingService)
	v := ProvideSubscriptionProviders(deadLetterResolver, backupScheduler, agentProcessor, embeddingProcessor)
	eventRegistrar := registry.NewEventRegistry(ebProvider, dispatcher, v)
	return eventRegistrar, nil
}

// BuildHandlers 使用 wire 生成的代码来构建 Handlers 实例。
// tracker 由顶层 BuildApp/BuildServer 注入,保证整个进程只有一个 visitor.Tracker 实例。
func BuildHandlers(dbProvider func() *gorm.DB, appCache cache.ICache[string, any], tx transaction.Transactor, ebProvider func() *busen.Bus, tracker *visitor.Tracker) (*handler.Bundle, error) {
	webHandler := handler2.NewWebHandler(tracker)
	userRepository := repository5.NewUserRepository(dbProvider, appCache)
	commonRepository := repository6.NewCommonRepository(dbProvider)
	commonService := service2.NewCommonService(commonRepository, appCache)
	keyValueRepository := keyvalue.NewKeyValueRepository(dbProvider, appCache)
	fileRepository := repository7.NewFileRepository(dbProvider)
	manager := storage.ProvideStorageManager(keyValueRepository)
	publisherPublisher := publisher.New(ebProvider)
	fileService := service3.NewFileService(tx, commonRepository, keyValueRepository, fileRepository, manager, publisherPublisher)
	settingRepository := repository8.NewSettingRepository(dbProvider)
	webhookRepository := repository.NewWebhookRepository(dbProvider)
	authRepository := repository9.NewAuthRepository(dbProvider, appCache)
	settingService := service4.NewSettingService(tx, commonService, fileService, manager, keyValueRepository, settingRepository, webhookRepository, authRepository, publisherPublisher)
	userService := service5.NewUserService(tx, userRepository, settingService, fileService, publisherPublisher)
	userHandler := handler3.NewUserHandler(userService)
	authService := auth.NewAuthService(tx, authRepository, authRepository, settingService)
	authHandler := handler4.NewAuthHandler(authService, userService)
	echoRepository := repository4.NewEchoRepository(dbProvider, appCache)
	echoService := service6.NewEchoService(tx, commonService, fileService, echoRepository, publisherPublisher)
	echoHandler := handler5.NewEchoHandler(echoService)
	fileHandler := handler6.NewFileHandler(fileService)
	commentRepository := repository10.NewCommentRepository(dbProvider)
	goMailSender := service7.NewGoMailSender()
	commentService := service7.NewCommentService(commonService, commentRepository, keyValueRepository, publisherPublisher, goMailSender)
	commentHandler := handler7.NewCommentHandler(commentService)
	initRepository := repository11.NewInitRepository(dbProvider)
	initService := service8.NewInitService(initRepository, userService)
	initHandler := handler8.NewInitHandler(initService)
	commonHandler := handler9.NewCommonHandler(commonService)
	settingHandler := handler10.NewSettingHandler(settingService)
	connectRepository := repository12.NewConnectRepository(dbProvider)
	connectService := service9.NewConnectService(tx, connectRepository, echoRepository, commonService, settingService)
	connectHandler := handler11.NewConnectHandler(connectService)
	backupService := service10.NewBackupService(commonService, publisherPublisher, manager)
	backupHandler := handler12.NewBackupHandler(backupService)
	migratorService := service11.NewMigratorService(commonService, keyValueRepository, manager, appCache)
	migrationHandler := handler13.NewMigrationHandler(migratorService)
	dashboardService := service12.NewDashboardService(tracker)
	dashboardHandler := handler14.NewDashboardHandler(dashboardService)
	agentService := service13.NewAgentService(settingService, echoService, keyValueRepository)
	agentHandler := handler15.NewAgentHandler(agentService)
	embeddingRepository := repository3.NewEmbeddingRepository(dbProvider)
	embeddingService := service.NewEmbeddingService(embeddingRepository, keyValueRepository, echoRepository)
	chatService := service14.NewChatService(embeddingService, keyValueRepository)
	chatHandler := handler16.NewChatHandler(chatService)
	embeddingHandler := handler17.NewEmbeddingHandler(embeddingService)
	mcpHandler := mcp.NewHandler(echoService, userService, commentService, fileService, commonService, connectService, agentService, settingService)
	bundle := handler.NewBundle(webHandler, userHandler, authHandler, echoHandler, fileHandler, commentHandler, initHandler, commonHandler, settingHandler, connectHandler, backupHandler, migrationHandler, dashboardHandler, agentHandler, chatHandler, embeddingHandler, mcpHandler)
	return bundle, nil
}

// BuildMiddlewares 构建中间件依赖。
func BuildMiddlewares(dbProvider func() *gorm.DB, appCache cache.ICache[string, any]) (*middleware.Deps, error) {
	authRepository := repository9.NewAuthRepository(dbProvider, appCache)
	deps := middleware.NewDeps(authRepository)
	return deps, nil
}

// BuildServer 构建 HTTP server
func BuildServer() (*server.Server, error) {
	engine := server.ProvideGinEngine()
	v := database.ProvideDBProvider()
	iCache, err := cache.ProvideCache()
	if err != nil {
		return nil, err
	}
	gormTransactor := transaction.NewGormTransactor(v)
	v2 := bus.ProvideProvider()
	tracker := visitor.NewTracker()
	bundle, err := BuildHandlers(v, iCache, gormTransactor, v2, tracker)
	if err != nil {
		return nil, err
	}
	deps, err := BuildMiddlewares(v, iCache)
	if err != nil {
		return nil, err
	}
	serverServer := server.ProvideHTTPServer(engine, bundle, deps)
	return serverServer, nil
}

func BuildTasker(dbProvider func() *gorm.DB, appCache cache.ICache[string, any], tx transaction.Transactor, ebProvider func() *busen.Bus, tracker *visitor.Tracker) (*task.Tasker, error) {
	commonRepository := repository6.NewCommonRepository(dbProvider)
	keyValueRepository := keyvalue.NewKeyValueRepository(dbProvider, appCache)
	fileRepository := repository7.NewFileRepository(dbProvider)
	manager := storage.ProvideStorageManager(keyValueRepository)
	publisherPublisher := publisher.New(ebProvider)
	fileService := service3.NewFileService(tx, commonRepository, keyValueRepository, fileRepository, manager, publisherPublisher)
	commonService := service2.NewCommonService(commonRepository, appCache)
	settingRepository := repository8.NewSettingRepository(dbProvider)
	webhookRepository := repository.NewWebhookRepository(dbProvider)
	authRepository := repository9.NewAuthRepository(dbProvider, appCache)
	settingService := service4.NewSettingService(tx, commonService, fileService, manager, keyValueRepository, settingRepository, webhookRepository, authRepository, publisherPublisher)
	queueRepository := repository2.NewQueueRepository(dbProvider)
	visitorRepository := repository13.NewVisitorRepository(dbProvider)
	tasker := task.NewTasker(fileService, settingService, publisherPublisher, queueRepository, manager, tracker, visitorRepository)
	return tasker, nil
}

func BuildMigrator(dbProvider func() *gorm.DB, appCache cache.ICache[string, any], tx transaction.Transactor) (*migrator.Worker, error) {
	worker := migrator.NewWorker()
	return worker, nil
}

// wire.go:

var AppSet = app.ProviderSet

// VisitorSet 独立于 HandlerSet/TaskerSet,避免 wire 为两个 Build 各自生成一个 Tracker
// 导致"WebHandler 写入 #1、Tasker 从 #2 读出恒为 0"的 bug。必须在 BuildApp/BuildServer
// 顶层引入一次,统一下沉给 BuildHandlers 和 BuildTasker。
var VisitorSet = wire.NewSet(visitor.NewTracker)

var DomainSet = wire.NewSet(
	BuildHandlers,
	BuildMiddlewares,
	BuildTasker,
	BuildMigrator,
	ProvideBackupScheduleApplier,
	BuildEventRegistrar,
)

var InfraSet = wire.NewSet(database.ProviderSet, bus.ProvideProvider, cache.ProviderSet, transaction.ProviderSet)

var RuntimeSet = server.ProviderSet

var EventSet = wire.NewSet(repository14.EchoSet, repository14.UserSet, repository14.KeyValueSet, repository14.QueueSet, repository14.WebhookSet, repository14.EmbeddingSet, wire.Bind(new(registry.WebhookObserver), new(*webhook.Dispatcher)), wire.Bind(new(subscriber.DeadLetterProcessor), new(*webhook.Dispatcher)), webhook.NewDispatcher, subscriber.NewBackupScheduler, subscriber.NewDeadLetterResolver, subscriber.NewAgentProcessor, subscriber.NewEmbeddingProcessor, service15.EmbeddingSet, ProvideSubscriptionProviders, registry.NewEventRegistry)

var HandlerSet = wire.NewSet(publisher.New, wire.Bind(new(service7.EventPublisher), new(*publisher.Publisher)), storage.ProviderSet, wire.Bind(new(storage.S3SettingStore), new(*keyvalue.KeyValueRepository)), repository14.FileSet, handler.WebSet, repository14.UserSet, repository14.AuthSet, service15.UserSet, service15.AuthSet, handler.UserSet, handler.AuthSet, repository14.EchoSet, service15.EchoSet, handler.EchoSet, repository14.CommentSet, service15.CommentSet, handler.CommentSet, repository14.CommonSet, service15.FileSet, handler.FileSet, repository14.InitSet, service15.InitSet, handler.InitSet, service15.CommonSet, handler.CommonSet, repository14.WebhookSet, repository14.KeyValueSet, repository14.SettingSet, service15.SettingSet, handler.SettingSet, repository14.ConnectSet, service15.ConnectSet, handler.ConnectSet, service15.DashboardSet, handler.DashboardSet, service15.AgentSet, handler.AgentSet, repository14.EmbeddingSet, service15.EmbeddingSet, handler.EmbeddingSet, service15.ChatSet, handler.ChatSet, service15.BackupSet, handler.BackupSet, repository14.MigrationSet, service15.MigratorSet, handler.MigrationSet, handler.MCPSet, handler.NewBundle)

var MiddlewareSet = wire.NewSet(repository14.AuthSet, middleware.ProviderSet)

var TaskerSet = wire.NewSet(publisher.New, storage.ProviderSet, wire.Bind(new(storage.S3SettingStore), new(*keyvalue.KeyValueRepository)), repository14.FileSet, repository14.KeyValueSet, repository14.WebhookSet, repository14.AuthSet, repository14.SettingSet, service15.SettingSet, repository14.EchoSet, service15.EchoSet, repository14.CommonSet, service15.FileSet, service15.CommonSet, repository14.QueueSet, repository14.VisitorSet, task.ProviderSet)

var MigratorSet = wire.NewSet(migrator.ProviderSet)

func ProvideBackupScheduleApplier(t *task.Tasker) subscriber.BackupScheduleApplier {
	return t
}

func ProvideSubscriptionProviders(
	dlr *subscriber.DeadLetterResolver,
	bs *subscriber.BackupScheduler,
	ap *subscriber.AgentProcessor,
	ep *subscriber.EmbeddingProcessor,
) []registry.SubscriptionProvider {
	return []registry.SubscriptionProvider{dlr, bs, ap, ep}
}
