// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/lin-snow/ech0/internal/app"
	"github.com/lin-snow/ech0/internal/cache"
	"github.com/lin-snow/ech0/internal/database"
	"github.com/lin-snow/ech0/internal/event/bus"
	"github.com/lin-snow/ech0/internal/event/publisher"
	"github.com/lin-snow/ech0/internal/event/registry"
	"github.com/lin-snow/ech0/internal/event/subscriber"
	"github.com/lin-snow/ech0/internal/handler"
	handler4 "github.com/lin-snow/ech0/internal/handler/auth"
	handler12 "github.com/lin-snow/ech0/internal/handler/backup"
	handler7 "github.com/lin-snow/ech0/internal/handler/comment"
	handler9 "github.com/lin-snow/ech0/internal/handler/common"
	handler11 "github.com/lin-snow/ech0/internal/handler/connect"
	handler15 "github.com/lin-snow/ech0/internal/handler/copilot"
	handler14 "github.com/lin-snow/ech0/internal/handler/dashboard"
	handler5 "github.com/lin-snow/ech0/internal/handler/echo"
	handler16 "github.com/lin-snow/ech0/internal/handler/embedding"
	handler6 "github.com/lin-snow/ech0/internal/handler/file"
	handler8 "github.com/lin-snow/ech0/internal/handler/init"
	handler13 "github.com/lin-snow/ech0/internal/handler/migration"
	handler10 "github.com/lin-snow/ech0/internal/handler/setting"
	handler3 "github.com/lin-snow/ech0/internal/handler/user"
	handler2 "github.com/lin-snow/ech0/internal/handler/web"
	"github.com/lin-snow/ech0/internal/job"
	"github.com/lin-snow/ech0/internal/job/runner"
	"github.com/lin-snow/ech0/internal/mcp"
	"github.com/lin-snow/ech0/internal/middleware"
	"github.com/lin-snow/ech0/internal/migrator"
	"github.com/lin-snow/ech0/internal/model/job"
	repository15 "github.com/lin-snow/ech0/internal/repository"
	repository9 "github.com/lin-snow/ech0/internal/repository/auth"
	repository10 "github.com/lin-snow/ech0/internal/repository/comment"
	repository6 "github.com/lin-snow/ech0/internal/repository/common"
	repository12 "github.com/lin-snow/ech0/internal/repository/connect"
	repository4 "github.com/lin-snow/ech0/internal/repository/echo"
	repository3 "github.com/lin-snow/ech0/internal/repository/embedding"
	repository7 "github.com/lin-snow/ech0/internal/repository/file"
	repository11 "github.com/lin-snow/ech0/internal/repository/init"
	repository13 "github.com/lin-snow/ech0/internal/repository/job"
	"github.com/lin-snow/ech0/internal/repository/keyvalue"
	repository2 "github.com/lin-snow/ech0/internal/repository/queue"
	repository8 "github.com/lin-snow/ech0/internal/repository/setting"
	repository5 "github.com/lin-snow/ech0/internal/repository/user"
	repository14 "github.com/lin-snow/ech0/internal/repository/visitor"
	"github.com/lin-snow/ech0/internal/repository/webhook"
	"github.com/lin-snow/ech0/internal/server"
	service14 "github.com/lin-snow/ech0/internal/service"
	"github.com/lin-snow/ech0/internal/service/auth"
	service10 "github.com/lin-snow/ech0/internal/service/backup"
	service7 "github.com/lin-snow/ech0/internal/service/comment"
	service2 "github.com/lin-snow/ech0/internal/service/common"
	service9 "github.com/lin-snow/ech0/internal/service/connect"
	service13 "github.com/lin-snow/ech0/internal/service/copilot"
	service12 "github.com/lin-snow/ech0/internal/service/dashboard"
	service6 "github.com/lin-snow/ech0/internal/service/echo"
	"github.com/lin-snow/ech0/internal/service/embedding"
	service3 "github.com/lin-snow/ech0/internal/service/file"
	service8 "github.com/lin-snow/ech0/internal/service/init"
	service11 "github.com/lin-snow/ech0/internal/service/migrator"
	service4 "github.com/lin-snow/ech0/internal/service/setting"
	service5 "github.com/lin-snow/ech0/internal/service/user"
	"github.com/lin-snow/ech0/internal/storage"
	"github.com/lin-snow/ech0/internal/task"
	"github.com/lin-snow/ech0/internal/transaction"
	"github.com/lin-snow/ech0/internal/visitor"
	"github.com/lin-snow/ech0/internal/webhook"
	"github.com/lin-snow/ech0/pkg/busen"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// BuildApp 构建 Web 生命周期应用。
func BuildApp() (*app.App, error) {
	v := database.ProvideDBProvider()
	v2 := bus.ProvideProvider()
	iCache, err := cache.ProvideCache()
	if err != nil {
		return nil, err
	}
	gormTransactor := transaction.NewGormTransactor(v)
	tracker := visitor.NewTracker()
	keyValueRepository := keyvalue.NewKeyValueRepository(v, iCache)
	manager := storage.ProvideStorageManager(keyValueRepository)
	tasker, err := BuildTasker(v, iCache, gormTransactor, v2, tracker, manager)
	if err != nil {
		return nil, err
	}
	backupScheduleApplier := ProvideBackupScheduleApplier(tasker)
	eventRegistrar, err := BuildEventRegistrar(v, v2, iCache, gormTransactor, backupScheduleApplier)
	if err != nil {
		return nil, err
	}
	eventBus := bus.NewEventBus(v2)
	jobManager, err := BuildJobManager(v, iCache, manager)
	if err != nil {
		return nil, err
	}
	worker, err := BuildMigrator(v, iCache, gormTransactor)
	if err != nil {
		return nil, err
	}
	engine := server.ProvideGinEngine()
	bundle, err := BuildHandlers(v, iCache, gormTransactor, v2, tracker, jobManager, manager)
	if err != nil {
		return nil, err
	}
	deps, err := BuildMiddlewares(v, iCache)
	if err != nil {
		return nil, err
	}
	serverServer := server.ProvideHTTPServer(engine, bundle, deps)
	v3 := app.ProvideOptions(eventRegistrar, eventBus, jobManager, tasker, worker, serverServer)
	appApp := app.NewApp(v3)
	return appApp, nil
}

func BuildEventRegistrar(dbProvider func() *gorm.DB, ebProvider func() *busen.Bus, appCache cache.ICache[string, any], tx transaction.Transactor, backupScheduleApplier subscriber.BackupScheduleApplier) (*registry.EventRegistrar, error) {
	webhookRepository := repository.NewWebhookRepository(dbProvider)
	queueRepository := repository2.NewQueueRepository(dbProvider)
	dispatcher := webhook.NewDispatcher(webhookRepository, queueRepository, tx)
	deadLetterResolver := subscriber.NewDeadLetterResolver(queueRepository, dispatcher)
	backupScheduler := subscriber.NewBackupScheduler(backupScheduleApplier)
	keyValueRepository := keyvalue.NewKeyValueRepository(dbProvider, appCache)
	agentProcessor := subscriber.NewAgentProcessor(keyValueRepository)
	embeddingRepository := repository3.NewEmbeddingRepository(dbProvider)
	echoRepository := repository4.NewEchoRepository(dbProvider, appCache)
	embeddingService := service.NewEmbeddingService(embeddingRepository, keyValueRepository, echoRepository)
	embeddingProcessor := subscriber.NewEmbeddingProcessor(embeddingService)
	v := ProvideSubscriptionProviders(deadLetterResolver, backupScheduler, agentProcessor, embeddingProcessor)
	eventRegistrar := registry.NewEventRegistry(ebProvider, dispatcher, v)
	return eventRegistrar, nil
}

// BuildHandlers 使用 wire 生成的代码来构建 Handlers 实例。
// tracker 由顶层 BuildApp/BuildServer 注入,保证整个进程只有一个 visitor.Tracker 实例。
func BuildHandlers(dbProvider func() *gorm.DB, appCache cache.ICache[string, any], tx transaction.Transactor, ebProvider func() *busen.Bus, tracker *visitor.Tracker, jobManager *job.Manager, storageManager *storage.Manager) (*handler.Bundle, error) {
	webHandler := handler2.NewWebHandler(tracker)
	userRepository := repository5.NewUserRepository(dbProvider, appCache)
	commonRepository := repository6.NewCommonRepository(dbProvider)
	commonService := service2.NewCommonService(commonRepository, appCache)
	keyValueRepository := keyvalue.NewKeyValueRepository(dbProvider, appCache)
	fileRepository := repository7.NewFileRepository(dbProvider)
	publisherPublisher := publisher.New(ebProvider)
	fileService := service3.NewFileService(tx, commonRepository, keyValueRepository, fileRepository, storageManager, publisherPublisher)
	settingRepository := repository8.NewSettingRepository(dbProvider)
	webhookRepository := repository.NewWebhookRepository(dbProvider)
	authRepository := repository9.NewAuthRepository(dbProvider, appCache)
	settingService := service4.NewSettingService(tx, commonService, fileService, storageManager, keyValueRepository, settingRepository, webhookRepository, authRepository, publisherPublisher)
	userService := service5.NewUserService(tx, userRepository, settingService, fileService, publisherPublisher)
	userHandler := handler3.NewUserHandler(userService)
	authService := auth.NewAuthService(tx, authRepository, authRepository, settingService)
	authHandler := handler4.NewAuthHandler(authService, userService)
	echoRepository := repository4.NewEchoRepository(dbProvider, appCache)
	echoService := service6.NewEchoService(tx, commonService, fileService, echoRepository, publisherPublisher)
	echoHandler := handler5.NewEchoHandler(echoService)
	fileHandler := handler6.NewFileHandler(fileService)
	commentRepository := repository10.NewCommentRepository(dbProvider)
	goMailSender := service7.NewGoMailSender()
	commentService := service7.NewCommentService(commonService, commentRepository, keyValueRepository, publisherPublisher, goMailSender)
	commentHandler := handler7.NewCommentHandler(commentService)
	initRepository := repository11.NewInitRepository(dbProvider)
	initService := service8.NewInitService(initRepository, userService)
	initHandler := handler8.NewInitHandler(initService)
	commonHandler := handler9.NewCommonHandler(commonService)
	settingHandler := handler10.NewSettingHandler(settingService)
	connectRepository := repository12.NewConnectRepository(dbProvider)
	connectService := service9.NewConnectService(tx, connectRepository, echoRepository, commonService, settingService)
	connectHandler := handler11.NewConnectHandler(connectService)
	backupService := service10.NewBackupService(commonService, publisherPublisher, storageManager)
	backupHandler := handler12.NewBackupHandler(backupService)
	migratorService := service11.NewMigratorService(commonService, jobManager)
	migrationHandler := handler13.NewMigrationHandler(migratorService)
	dashboardService := service12.NewDashboardService(tracker)
	dashboardHandler := handler14.NewDashboardHandler(dashboardService)
	embeddingRepository := repository3.NewEmbeddingRepository(dbProvider)
	embeddingService := service.NewEmbeddingService(embeddingRepository, keyValueRepository, echoRepository)
	copilotService := service13.NewCopilotService(echoService, embeddingService, userService, keyValueRepository, storageManager)
	copilotHandler := handler15.NewCopilotHandler(copilotService, copilotService)
	embeddingHandler := handler16.NewEmbeddingHandler(jobManager)
	mcpHandler := mcp.NewHandler(echoService, userService, commentService, fileService, commonService, connectService, copilotService, settingService)
	bundle := handler.NewBundle(webHandler, userHandler, authHandler, echoHandler, fileHandler, commentHandler, initHandler, commonHandler, settingHandler, connectHandler, backupHandler, migrationHandler, dashboardHandler, copilotHandler, embeddingHandler, mcpHandler)
	return bundle, nil
}

// BuildJobManager 装配共享单例 *job.Manager：repo + 各领域 Runner（含其依赖的领域
// service），在构造期注册完成。Runner 依赖的 EmbeddingService / migrator.Importer 均不
// 含 *job.Manager，故无构造环。storageManager 由顶层共享单例注入，确保迁移导入 S3
// 设置时 reload 的就是文件服务在用的那份 Manager。
func BuildJobManager(dbProvider func() *gorm.DB, appCache cache.ICache[string, any], storageManager *storage.Manager) (*job.Manager, error) {
	jobRepository := repository13.NewJobRepository(dbProvider)
	embeddingRepository := repository3.NewEmbeddingRepository(dbProvider)
	keyValueRepository := keyvalue.NewKeyValueRepository(dbProvider, appCache)
	echoRepository := repository4.NewEchoRepository(dbProvider, appCache)
	embeddingService := service.NewEmbeddingService(embeddingRepository, keyValueRepository, echoRepository)
	reindexRunner := runner.NewReindexRunner(embeddingService)
	importer := service11.NewImporter(keyValueRepository, storageManager, appCache)
	migrationRunner := runner.NewMigrationRunner(importer)
	manager := ProvideJobManager(jobRepository, reindexRunner, migrationRunner)
	return manager, nil
}

// BuildMiddlewares 构建中间件依赖。
func BuildMiddlewares(dbProvider func() *gorm.DB, appCache cache.ICache[string, any]) (*middleware.Deps, error) {
	authRepository := repository9.NewAuthRepository(dbProvider, appCache)
	deps := middleware.NewDeps(authRepository)
	return deps, nil
}

// BuildServer 构建 HTTP server
func BuildServer() (*server.Server, error) {
	engine := server.ProvideGinEngine()
	v := database.ProvideDBProvider()
	iCache, err := cache.ProvideCache()
	if err != nil {
		return nil, err
	}
	gormTransactor := transaction.NewGormTransactor(v)
	v2 := bus.ProvideProvider()
	tracker := visitor.NewTracker()
	keyValueRepository := keyvalue.NewKeyValueRepository(v, iCache)
	manager := storage.ProvideStorageManager(keyValueRepository)
	jobManager, err := BuildJobManager(v, iCache, manager)
	if err != nil {
		return nil, err
	}
	bundle, err := BuildHandlers(v, iCache, gormTransactor, v2, tracker, jobManager, manager)
	if err != nil {
		return nil, err
	}
	deps, err := BuildMiddlewares(v, iCache)
	if err != nil {
		return nil, err
	}
	serverServer := server.ProvideHTTPServer(engine, bundle, deps)
	return serverServer, nil
}

func BuildTasker(dbProvider func() *gorm.DB, appCache cache.ICache[string, any], tx transaction.Transactor, ebProvider func() *busen.Bus, tracker *visitor.Tracker, storageManager *storage.Manager) (*task.Tasker, error) {
	commonRepository := repository6.NewCommonRepository(dbProvider)
	keyValueRepository := keyvalue.NewKeyValueRepository(dbProvider, appCache)
	fileRepository := repository7.NewFileRepository(dbProvider)
	publisherPublisher := publisher.New(ebProvider)
	fileService := service3.NewFileService(tx, commonRepository, keyValueRepository, fileRepository, storageManager, publisherPublisher)
	commonService := service2.NewCommonService(commonRepository, appCache)
	settingRepository := repository8.NewSettingRepository(dbProvider)
	webhookRepository := repository.NewWebhookRepository(dbProvider)
	authRepository := repository9.NewAuthRepository(dbProvider, appCache)
	settingService := service4.NewSettingService(tx, commonService, fileService, storageManager, keyValueRepository, settingRepository, webhookRepository, authRepository, publisherPublisher)
	queueRepository := repository2.NewQueueRepository(dbProvider)
	visitorRepository := repository14.NewVisitorRepository(dbProvider)
	tasker := task.NewTasker(fileService, settingService, publisherPublisher, queueRepository, storageManager, tracker, visitorRepository)
	return tasker, nil
}

func BuildMigrator(dbProvider func() *gorm.DB, appCache cache.ICache[string, any], tx transaction.Transactor) (*migrator.Worker, error) {
	worker := migrator.NewWorker()
	return worker, nil
}

// wire.go:

var AppSet = app.ProviderSet

// VisitorSet 独立于 HandlerSet/TaskerSet,避免 wire 为两个 Build 各自生成一个 Tracker
// 导致"WebHandler 写入 #1、Tasker 从 #2 读出恒为 0"的 bug。必须在 BuildApp/BuildServer
// 顶层引入一次,统一下沉给 BuildHandlers 和 BuildTasker。
var VisitorSet = wire.NewSet(visitor.NewTracker)

// ProvideJobManager 构造已装配好 Runner 的共享单例 *job.Manager（在构造期一次性
// 完成注册）。Runner 只依赖 EmbeddingService / migrator.Importer（均不含 *job.Manager），
// 故不会与「MigratorService 需要 Manager」形成构造环。
func ProvideJobManager(
	repo job.JobRepository,
	reindex *runner.ReindexRunner,
	migration *runner.MigrationRunner,
) *job.Manager {
	m := job.NewManager(repo)
	m.Register(model.TypeReindex, job.Adapt(reindex.Run))
	m.Register(model.TypeMigration, job.Adapt(migration.Run))
	return m
}

// StorageSet 提供进程级共享单例 *storage.Manager。storage.Manager 是有状态基础设施
// （缓存当前存储后端，ReloadFromConfigAndDB 会改写它），必须全进程一个实例，否则
// 「设置页 / 迁移改了 S3 → 只 reload 了自己那份 Manager，文件服务仍用旧后端」。同
// VisitorSet：顶层引入一次，统一下沉给 BuildHandlers/BuildTasker/BuildJobManager。
// 它自带一份 KeyValueRepository 仅供读取 S3 设置，与各 Build 内的 KeyValueSet 互不冲突。
var StorageSet = wire.NewSet(keyvalue.NewKeyValueRepository, wire.Bind(new(storage.S3SettingStore), new(*keyvalue.KeyValueRepository)), storage.ProviderSet)

var DomainSet = wire.NewSet(
	BuildHandlers,
	BuildMiddlewares,
	BuildTasker,
	BuildMigrator,
	BuildJobManager,
	ProvideBackupScheduleApplier,
	BuildEventRegistrar,
)

var InfraSet = wire.NewSet(database.ProviderSet, bus.ProvideProvider, cache.ProviderSet, transaction.ProviderSet)

var RuntimeSet = server.ProviderSet

var EventSet = wire.NewSet(repository15.EchoSet, repository15.UserSet, repository15.KeyValueSet, repository15.QueueSet, repository15.WebhookSet, repository15.EmbeddingSet, wire.Bind(new(registry.WebhookObserver), new(*webhook.Dispatcher)), wire.Bind(new(subscriber.DeadLetterProcessor), new(*webhook.Dispatcher)), webhook.NewDispatcher, subscriber.NewBackupScheduler, subscriber.NewDeadLetterResolver, subscriber.NewAgentProcessor, subscriber.NewEmbeddingProcessor, service14.EmbeddingSet, ProvideSubscriptionProviders, registry.NewEventRegistry)

var HandlerSet = wire.NewSet(publisher.New, wire.Bind(new(service7.EventPublisher), new(*publisher.Publisher)), repository15.FileSet, handler.WebSet, repository15.UserSet, repository15.AuthSet, service14.UserSet, service14.AuthSet, handler.UserSet, handler.AuthSet, repository15.EchoSet, service14.EchoSet, handler.EchoSet, repository15.CommentSet, service14.CommentSet, handler.CommentSet, repository15.CommonSet, service14.FileSet, handler.FileSet, repository15.InitSet, service14.InitSet, handler.InitSet, service14.CommonSet, handler.CommonSet, repository15.WebhookSet, repository15.KeyValueSet, repository15.SettingSet, service14.SettingSet, handler.SettingSet, repository15.ConnectSet, service14.ConnectSet, handler.ConnectSet, service14.DashboardSet, handler.DashboardSet, repository15.EmbeddingSet, service14.EmbeddingSet, handler.EmbeddingSet, service14.CopilotSet, wire.Bind(new(service13.UserReader), new(*service5.UserService)), handler.CopilotSet, service14.BackupSet, handler.BackupSet, service14.MigratorSet, handler.MigrationSet, handler.MCPSet, handler.NewBundle)

var MiddlewareSet = wire.NewSet(repository15.AuthSet, middleware.ProviderSet)

var TaskerSet = wire.NewSet(publisher.New, repository15.FileSet, repository15.KeyValueSet, repository15.WebhookSet, repository15.AuthSet, repository15.SettingSet, service14.SettingSet, repository15.EchoSet, service14.EchoSet, repository15.CommonSet, service14.FileSet, service14.CommonSet, repository15.QueueSet, repository15.VisitorSet, task.ProviderSet)

var MigratorSet = wire.NewSet(migrator.ProviderSet)

func ProvideBackupScheduleApplier(t *task.Tasker) subscriber.BackupScheduleApplier {
	return t
}

func ProvideSubscriptionProviders(
	dlr *subscriber.DeadLetterResolver,
	bs *subscriber.BackupScheduler,
	ap *subscriber.AgentProcessor,
	ep *subscriber.EmbeddingProcessor,
) []registry.SubscriptionProvider {
	return []registry.SubscriptionProvider{dlr, bs, ap, ep}
}
