// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/lin-snow/ech0/internal/app"
	"github.com/lin-snow/ech0/internal/cache"
	event2 "github.com/lin-snow/ech0/internal/event"
	"github.com/lin-snow/ech0/internal/handler"
	handler12 "github.com/lin-snow/ech0/internal/handler/agent"
	handler10 "github.com/lin-snow/ech0/internal/handler/backup"
	handler5 "github.com/lin-snow/ech0/internal/handler/common"
	handler9 "github.com/lin-snow/ech0/internal/handler/connect"
	handler11 "github.com/lin-snow/ech0/internal/handler/dashboard"
	handler4 "github.com/lin-snow/ech0/internal/handler/echo"
	handler7 "github.com/lin-snow/ech0/internal/handler/inbox"
	handler6 "github.com/lin-snow/ech0/internal/handler/setting"
	handler8 "github.com/lin-snow/ech0/internal/handler/todo"
	handler3 "github.com/lin-snow/ech0/internal/handler/user"
	handler2 "github.com/lin-snow/ech0/internal/handler/web"
	"github.com/lin-snow/ech0/internal/metric"
	"github.com/lin-snow/ech0/internal/monitor"
	repository11 "github.com/lin-snow/ech0/internal/repository"
	repository7 "github.com/lin-snow/ech0/internal/repository/common"
	repository10 "github.com/lin-snow/ech0/internal/repository/connect"
	repository3 "github.com/lin-snow/ech0/internal/repository/echo"
	repository8 "github.com/lin-snow/ech0/internal/repository/file"
	repository6 "github.com/lin-snow/ech0/internal/repository/inbox"
	"github.com/lin-snow/ech0/internal/repository/keyvalue"
	repository2 "github.com/lin-snow/ech0/internal/repository/queue"
	repository9 "github.com/lin-snow/ech0/internal/repository/setting"
	repository4 "github.com/lin-snow/ech0/internal/repository/todo"
	repository5 "github.com/lin-snow/ech0/internal/repository/user"
	"github.com/lin-snow/ech0/internal/repository/webhook"
	cache2 "github.com/lin-snow/ech0/internal/runtime/cache"
	"github.com/lin-snow/ech0/internal/runtime/event"
	"github.com/lin-snow/ech0/internal/runtime/http"
	"github.com/lin-snow/ech0/internal/runtime/task"
	service11 "github.com/lin-snow/ech0/internal/service"
	service10 "github.com/lin-snow/ech0/internal/service/agent"
	service8 "github.com/lin-snow/ech0/internal/service/backup"
	"github.com/lin-snow/ech0/internal/service/common"
	service7 "github.com/lin-snow/ech0/internal/service/connect"
	service9 "github.com/lin-snow/ech0/internal/service/dashboard"
	service4 "github.com/lin-snow/ech0/internal/service/echo"
	service5 "github.com/lin-snow/ech0/internal/service/inbox"
	service2 "github.com/lin-snow/ech0/internal/service/setting"
	service6 "github.com/lin-snow/ech0/internal/service/todo"
	service3 "github.com/lin-snow/ech0/internal/service/user"
	"github.com/lin-snow/ech0/internal/storage"
	task2 "github.com/lin-snow/ech0/internal/task"
	"github.com/lin-snow/ech0/internal/transaction"
	"gorm.io/gorm"
)

// Injectors from wire.go:

// BuildApp 构建应用内核。
func BuildApp() (*app.App, func(), error) {
	cacheFactory := cache.NewCacheFactory()
	v := cache.ProvideCleanup(cacheFactory)
	runtime := cache2.New(v)
	v2 := ProvideDBProvider()
	v3 := ProvideEventBusProvider()
	transactionManagerFactory := transaction.NewTransactionManagerFactory(v2)
	eventRegistrar, err := ProvideEventRegistrar(v2, v3, cacheFactory, transactionManagerFactory)
	if err != nil {
		return nil, nil, err
	}
	eventRuntime := event.New(eventRegistrar)
	tasker, err := ProvideTasker(v2, cacheFactory, transactionManagerFactory, v3)
	if err != nil {
		return nil, nil, err
	}
	taskRuntime := task.New(tasker)
	engine := ProvideGinEngine()
	bundle, err := ProvideHandlers(v2, cacheFactory, transactionManagerFactory, v3)
	if err != nil {
		return nil, nil, err
	}
	server := ProvideHTTPServer(engine, bundle)
	httpRuntime := http.New(server)
	v4 := ProvideWebComponents(runtime, eventRuntime, taskRuntime, httpRuntime)
	v5 := app.NewApp(v4)
	return v5, func() {
	}, nil
}

func BuildEventRegistrar(dbProvider func() *gorm.DB, ebProvider func() event2.IEventBus, cacheFactory *cache.CacheFactory, tmFactory *transaction.TransactionManagerFactory) (*event2.EventRegistrar, error) {
	webhookRepositoryInterface := repository.NewWebhookRepository(dbProvider)
	queueRepositoryInterface := repository2.NewQueueRepository(dbProvider)
	transactionManager := transaction.ProvideTransactionManager(tmFactory)
	webhookDispatcher := event2.NewWebhookDispatcher(ebProvider, webhookRepositoryInterface, queueRepositoryInterface, transactionManager)
	deadLetterResolver := event2.NewDeadLetterResolver(queueRepositoryInterface, webhookDispatcher)
	backupScheduler := event2.NewBackupScheduler()
	iCache := cache.ProvideCache(cacheFactory)
	echoRepositoryInterface := repository3.NewEchoRepository(dbProvider, iCache)
	todoRepositoryInterface := repository4.NewTodoRepository(dbProvider, iCache)
	userRepositoryInterface := repository5.NewUserRepository(dbProvider, iCache)
	keyValueRepositoryInterface := keyvalue.NewKeyValueRepository(dbProvider, iCache)
	inboxRepositoryInterface := repository6.NewInboxRepository(dbProvider)
	agentProcessor := event2.NewAgentProcessor(echoRepositoryInterface, todoRepositoryInterface, userRepositoryInterface, keyValueRepositoryInterface, inboxRepositoryInterface)
	inboxDispatcher := event2.NewInboxDispatcher(inboxRepositoryInterface, keyValueRepositoryInterface)
	eventHandlers := event2.NewEventHandlers(webhookDispatcher, deadLetterResolver, backupScheduler, agentProcessor, inboxDispatcher)
	eventRegistrar := event2.NewEventRegistry(ebProvider, eventHandlers)
	return eventRegistrar, nil
}

// BuildHandlers 使用 wire 生成的代码来构建 Handlers 实例。
func BuildHandlers(dbProvider func() *gorm.DB, cacheFactory *cache.CacheFactory, tmFactory *transaction.TransactionManagerFactory, ebProvider func() event2.IEventBus) (*handler.Bundle, error) {
	webHandler := handler2.NewWebHandler()
	transactionManager := transaction.ProvideTransactionManager(tmFactory)
	iCache := cache.ProvideCache(cacheFactory)
	userRepositoryInterface := repository5.NewUserRepository(dbProvider, iCache)
	commonRepositoryInterface := repository7.NewCommonRepository(dbProvider)
	echoRepositoryInterface := repository3.NewEchoRepository(dbProvider, iCache)
	keyValueRepositoryInterface := keyvalue.NewKeyValueRepository(dbProvider, iCache)
	fileRepositoryInterface := repository8.NewFileRepository(dbProvider)
	fs := storage.ProvideFS()
	urlResolver := storage.ProvideURLResolver()
	commonService := service.NewCommonService(transactionManager, commonRepositoryInterface, echoRepositoryInterface, keyValueRepositoryInterface, fileRepositoryInterface, fs, urlResolver, ebProvider)
	settingRepositoryInterface := repository9.NewSettingRepository(dbProvider)
	webhookRepositoryInterface := repository.NewWebhookRepository(dbProvider)
	settingService := service2.NewSettingService(transactionManager, commonService, keyValueRepositoryInterface, settingRepositoryInterface, webhookRepositoryInterface, ebProvider)
	userService := service3.NewUserService(transactionManager, userRepositoryInterface, settingService, ebProvider)
	userHandler := handler3.NewUserHandler(userService)
	echoService := service4.NewEchoService(transactionManager, commonService, echoRepositoryInterface, commonRepositoryInterface, keyValueRepositoryInterface, ebProvider)
	echoHandler := handler4.NewEchoHandler(echoService)
	commonHandler := handler5.NewCommonHandler(commonService)
	settingHandler := handler6.NewSettingHandler(settingService)
	inboxRepositoryInterface := repository6.NewInboxRepository(dbProvider)
	inboxService := service5.NewInboxService(transactionManager, commonService, inboxRepositoryInterface)
	inboxHandler := handler7.NewInboxHandler(inboxService)
	todoRepositoryInterface := repository4.NewTodoRepository(dbProvider, iCache)
	todoService := service6.NewTodoService(transactionManager, todoRepositoryInterface, commonService)
	todoHandler := handler8.NewTodoHandler(todoService)
	connectRepositoryInterface := repository10.NewConnectRepository(dbProvider)
	connectService := service7.NewConnectService(transactionManager, connectRepositoryInterface, echoRepositoryInterface, commonService, settingService)
	connectHandler := handler9.NewConnectHandler(connectService)
	backupService := service8.NewBackupService(commonService, ebProvider)
	backupHandler := handler10.NewBackupHandler(backupService)
	metricCollector := metric.NewSystemCollector()
	monitorMonitor := monitor.NewMonitor(metricCollector)
	dashboardService := service9.NewDashboardService(monitorMonitor, commonService)
	dashboardHandler := handler11.NewDashboardHandler(dashboardService)
	agentService := service10.NewAgentService(settingService, echoService, todoService, keyValueRepositoryInterface)
	agentHandler := handler12.NewAgentHandler(agentService)
	bundle := handler.NewBundle(webHandler, userHandler, echoHandler, commonHandler, settingHandler, inboxHandler, todoHandler, connectHandler, backupHandler, dashboardHandler, agentHandler)
	return bundle, nil
}

// BuildWebRuntime 构建 HTTP runtime（用于测试和独立启动场景）。
func BuildWebRuntime() (*http.Runtime, error) {
	engine := ProvideGinEngine()
	v := ProvideDBProvider()
	cacheFactory := cache.NewCacheFactory()
	transactionManagerFactory := transaction.NewTransactionManagerFactory(v)
	v2 := ProvideEventBusProvider()
	bundle, err := ProvideHandlers(v, cacheFactory, transactionManagerFactory, v2)
	if err != nil {
		return nil, err
	}
	server := ProvideHTTPServer(engine, bundle)
	runtime := http.New(server)
	return runtime, nil
}

func BuildTasker(dbProvider func() *gorm.DB, cacheFactory *cache.CacheFactory, tmFactory *transaction.TransactionManagerFactory, ebProvider func() event2.IEventBus) (*task2.Tasker, error) {
	transactionManager := transaction.ProvideTransactionManager(tmFactory)
	commonRepositoryInterface := repository7.NewCommonRepository(dbProvider)
	iCache := cache.ProvideCache(cacheFactory)
	echoRepositoryInterface := repository3.NewEchoRepository(dbProvider, iCache)
	keyValueRepositoryInterface := keyvalue.NewKeyValueRepository(dbProvider, iCache)
	fileRepositoryInterface := repository8.NewFileRepository(dbProvider)
	fs := storage.ProvideFS()
	urlResolver := storage.ProvideURLResolver()
	commonService := service.NewCommonService(transactionManager, commonRepositoryInterface, echoRepositoryInterface, keyValueRepositoryInterface, fileRepositoryInterface, fs, urlResolver, ebProvider)
	settingRepositoryInterface := repository9.NewSettingRepository(dbProvider)
	webhookRepositoryInterface := repository.NewWebhookRepository(dbProvider)
	settingService := service2.NewSettingService(transactionManager, commonService, keyValueRepositoryInterface, settingRepositoryInterface, webhookRepositoryInterface, ebProvider)
	queueRepositoryInterface := repository2.NewQueueRepository(dbProvider)
	tasker := task2.NewTasker(commonService, settingService, ebProvider, queueRepositoryInterface)
	return tasker, nil
}

// wire.go:

var AppSet = wire.NewSet(
	ProvideWebComponents, app.ProviderSet,
)

var DomainSet = wire.NewSet(
	ProvideHandlers,
	ProvideTasker,
	ProvideEventRegistrar,
)

var InfraSet = wire.NewSet(
	ProvideDBProvider,
	ProvideEventBusProvider, cache.ProviderSet, transaction.ProviderSet, ProvideGinEngine,
)

var RuntimeSet = wire.NewSet(
	ProvideHTTPServer, http.ProviderSet, event.ProviderSet, task.ProviderSet, cache2.ProviderSet,
)

var WebSet = wire.NewSet(handler.WebSet)

var UserSet = wire.NewSet(repository11.UserSet, service11.UserSet, handler.UserSet)

var EchoSet = wire.NewSet(repository11.EchoSet, service11.EchoSet, handler.EchoSet)

var CommonSet = wire.NewSet(repository11.CommonSet, service11.CommonSet, handler.CommonSet)

var KeyValueSet = wire.NewSet(repository11.KeyValueSet)

var SettingSet = wire.NewSet(repository11.SettingSet, service11.SettingSet, handler.SettingSet)

var TodoSet = wire.NewSet(repository11.TodoSet, service11.TodoSet, handler.TodoSet)

var ConnectSet = wire.NewSet(repository11.ConnectSet, service11.ConnectSet, handler.ConnectSet)

var BackupSet = wire.NewSet(service11.BackupSet, handler.BackupSet)

var DashboardSet = wire.NewSet(service11.DashboardSet, handler.DashboardSet)

var AgentSet = wire.NewSet(service11.AgentSet, handler.AgentSet)

var WebhookSet = wire.NewSet(repository11.WebhookSet)

var InboxSet = wire.NewSet(repository11.InboxSet, service11.InboxSet, handler.InboxSet)

var QueueSet = wire.NewSet(repository11.QueueSet)

var TaskSet = wire.NewSet(task2.NewTasker)

var EventSet = wire.NewSet(event2.NewWebhookDispatcher, event2.NewBackupScheduler, event2.NewDeadLetterResolver, event2.NewAgentProcessor, event2.NewInboxDispatcher, event2.NewEventHandlers, event2.NewEventRegistry)

var MetricSet = wire.NewSet(metric.NewSystemCollector)

var MonitorSet = wire.NewSet(monitor.NewMonitor)
