// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2025-2026 lin-snow

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package commonmock

import (
	"context"

	"github.com/gin-gonic/gin"
	model0 "github.com/lin-snow/ech0/internal/model/common"
	model1 "github.com/lin-snow/ech0/internal/model/echo"
	"github.com/lin-snow/ech0/internal/model/user"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CommonGetUserByUserId provides a mock function for the type MockService
func (_mock *MockService) CommonGetUserByUserId(ctx context.Context, userId string) (model.User, error) {
	ret := _mock.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for CommonGetUserByUserId")
	}

	var r0 model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.User, error)); ok {
		return returnFunc(ctx, userId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.User); ok {
		r0 = returnFunc(ctx, userId)
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_CommonGetUserByUserId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommonGetUserByUserId'
type MockService_CommonGetUserByUserId_Call struct {
	*mock.Call
}

// CommonGetUserByUserId is a helper method to define mock.On call
//   - ctx context.Context
//   - userId string
func (_e *MockService_Expecter) CommonGetUserByUserId(ctx any, userId any) *MockService_CommonGetUserByUserId_Call {
	return &MockService_CommonGetUserByUserId_Call{Call: _e.mock.On("CommonGetUserByUserId", ctx, userId)}
}

func (_c *MockService_CommonGetUserByUserId_Call) Run(run func(ctx context.Context, userId string)) *MockService_CommonGetUserByUserId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_CommonGetUserByUserId_Call) Return(user model.User, err error) *MockService_CommonGetUserByUserId_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockService_CommonGetUserByUserId_Call) RunAndReturn(run func(ctx context.Context, userId string) (model.User, error)) *MockService_CommonGetUserByUserId_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateRSS provides a mock function for the type MockService
func (_mock *MockService) GenerateRSS(ctx *gin.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GenerateRSS")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*gin.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(*gin.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(*gin.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GenerateRSS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateRSS'
type MockService_GenerateRSS_Call struct {
	*mock.Call
}

// GenerateRSS is a helper method to define mock.On call
//   - ctx *gin.Context
func (_e *MockService_Expecter) GenerateRSS(ctx any) *MockService_GenerateRSS_Call {
	return &MockService_GenerateRSS_Call{Call: _e.mock.On("GenerateRSS", ctx)}
}

func (_c *MockService_GenerateRSS_Call) Run(run func(ctx *gin.Context)) *MockService_GenerateRSS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_GenerateRSS_Call) Return(s string, err error) *MockService_GenerateRSS_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockService_GenerateRSS_Call) RunAndReturn(run func(ctx *gin.Context) (string, error)) *MockService_GenerateRSS_Call {
	_c.Call.Return(run)
	return _c
}

// GetHeatMap provides a mock function for the type MockService
func (_mock *MockService) GetHeatMap(timezone string) ([]model0.Heatmap, error) {
	ret := _mock.Called(timezone)

	if len(ret) == 0 {
		panic("no return value specified for GetHeatMap")
	}

	var r0 []model0.Heatmap
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]model0.Heatmap, error)); ok {
		return returnFunc(timezone)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []model0.Heatmap); ok {
		r0 = returnFunc(timezone)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model0.Heatmap)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(timezone)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetHeatMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHeatMap'
type MockService_GetHeatMap_Call struct {
	*mock.Call
}

// GetHeatMap is a helper method to define mock.On call
//   - timezone string
func (_e *MockService_Expecter) GetHeatMap(timezone any) *MockService_GetHeatMap_Call {
	return &MockService_GetHeatMap_Call{Call: _e.mock.On("GetHeatMap", timezone)}
}

func (_c *MockService_GetHeatMap_Call) Run(run func(timezone string)) *MockService_GetHeatMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_GetHeatMap_Call) Return(heatmaps []model0.Heatmap, err error) *MockService_GetHeatMap_Call {
	_c.Call.Return(heatmaps, err)
	return _c
}

func (_c *MockService_GetHeatMap_Call) RunAndReturn(run func(timezone string) ([]model0.Heatmap, error)) *MockService_GetHeatMap_Call {
	_c.Call.Return(run)
	return _c
}

// GetOwner provides a mock function for the type MockService
func (_mock *MockService) GetOwner() (model.User, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetOwner")
	}

	var r0 model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (model.User, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() model.User); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOwner'
type MockService_GetOwner_Call struct {
	*mock.Call
}

// GetOwner is a helper method to define mock.On call
func (_e *MockService_Expecter) GetOwner() *MockService_GetOwner_Call {
	return &MockService_GetOwner_Call{Call: _e.mock.On("GetOwner")}
}

func (_c *MockService_GetOwner_Call) Run(run func()) *MockService_GetOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_GetOwner_Call) Return(user model.User, err error) *MockService_GetOwner_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockService_GetOwner_Call) RunAndReturn(run func() (model.User, error)) *MockService_GetOwner_Call {
	_c.Call.Return(run)
	return _c
}

// GetWebsiteTitle provides a mock function for the type MockService
func (_mock *MockService) GetWebsiteTitle(websiteURL string) (string, error) {
	ret := _mock.Called(websiteURL)

	if len(ret) == 0 {
		panic("no return value specified for GetWebsiteTitle")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(websiteURL)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(websiteURL)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(websiteURL)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetWebsiteTitle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWebsiteTitle'
type MockService_GetWebsiteTitle_Call struct {
	*mock.Call
}

// GetWebsiteTitle is a helper method to define mock.On call
//   - websiteURL string
func (_e *MockService_Expecter) GetWebsiteTitle(websiteURL any) *MockService_GetWebsiteTitle_Call {
	return &MockService_GetWebsiteTitle_Call{Call: _e.mock.On("GetWebsiteTitle", websiteURL)}
}

func (_c *MockService_GetWebsiteTitle_Call) Run(run func(websiteURL string)) *MockService_GetWebsiteTitle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_GetWebsiteTitle_Call) Return(s string, err error) *MockService_GetWebsiteTitle_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockService_GetWebsiteTitle_Call) RunAndReturn(run func(websiteURL string) (string, error)) *MockService_GetWebsiteTitle_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCommonRepository creates a new instance of MockCommonRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommonRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommonRepository {
	mock := &MockCommonRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommonRepository is an autogenerated mock type for the CommonRepository type
type MockCommonRepository struct {
	mock.Mock
}

type MockCommonRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommonRepository) EXPECT() *MockCommonRepository_Expecter {
	return &MockCommonRepository_Expecter{mock: &_m.Mock}
}

// GetAllEchos provides a mock function for the type MockCommonRepository
func (_mock *MockCommonRepository) GetAllEchos(ctx context.Context, showPrivate bool) ([]model1.Echo, error) {
	ret := _mock.Called(ctx, showPrivate)

	if len(ret) == 0 {
		panic("no return value specified for GetAllEchos")
	}

	var r0 []model1.Echo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool) ([]model1.Echo, error)); ok {
		return returnFunc(ctx, showPrivate)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool) []model1.Echo); ok {
		r0 = returnFunc(ctx, showPrivate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model1.Echo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bool) error); ok {
		r1 = returnFunc(ctx, showPrivate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommonRepository_GetAllEchos_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllEchos'
type MockCommonRepository_GetAllEchos_Call struct {
	*mock.Call
}

// GetAllEchos is a helper method to define mock.On call
//   - ctx context.Context
//   - showPrivate bool
func (_e *MockCommonRepository_Expecter) GetAllEchos(ctx any, showPrivate any) *MockCommonRepository_GetAllEchos_Call {
	return &MockCommonRepository_GetAllEchos_Call{Call: _e.mock.On("GetAllEchos", ctx, showPrivate)}
}

func (_c *MockCommonRepository_GetAllEchos_Call) Run(run func(ctx context.Context, showPrivate bool)) *MockCommonRepository_GetAllEchos_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommonRepository_GetAllEchos_Call) Return(echos []model1.Echo, err error) *MockCommonRepository_GetAllEchos_Call {
	_c.Call.Return(echos, err)
	return _c
}

func (_c *MockCommonRepository_GetAllEchos_Call) RunAndReturn(run func(ctx context.Context, showPrivate bool) ([]model1.Echo, error)) *MockCommonRepository_GetAllEchos_Call {
	_c.Call.Return(run)
	return _c
}

// GetHeatMap provides a mock function for the type MockCommonRepository
func (_mock *MockCommonRepository) GetHeatMap(ctx context.Context, startTime int64, endTime int64) ([]int64, error) {
	ret := _mock.Called(ctx, startTime, endTime)

	if len(ret) == 0 {
		panic("no return value specified for GetHeatMap")
	}

	var r0 []int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) ([]int64, error)); ok {
		return returnFunc(ctx, startTime, endTime)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int64) []int64); ok {
		r0 = returnFunc(ctx, startTime, endTime)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = returnFunc(ctx, startTime, endTime)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommonRepository_GetHeatMap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHeatMap'
type MockCommonRepository_GetHeatMap_Call struct {
	*mock.Call
}

// GetHeatMap is a helper method to define mock.On call
//   - ctx context.Context
//   - startTime int64
//   - endTime int64
func (_e *MockCommonRepository_Expecter) GetHeatMap(ctx any, startTime any, endTime any) *MockCommonRepository_GetHeatMap_Call {
	return &MockCommonRepository_GetHeatMap_Call{Call: _e.mock.On("GetHeatMap", ctx, startTime, endTime)}
}

func (_c *MockCommonRepository_GetHeatMap_Call) Run(run func(ctx context.Context, startTime int64, endTime int64)) *MockCommonRepository_GetHeatMap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCommonRepository_GetHeatMap_Call) Return(int64s []int64, err error) *MockCommonRepository_GetHeatMap_Call {
	_c.Call.Return(int64s, err)
	return _c
}

func (_c *MockCommonRepository_GetHeatMap_Call) RunAndReturn(run func(ctx context.Context, startTime int64, endTime int64) ([]int64, error)) *MockCommonRepository_GetHeatMap_Call {
	_c.Call.Return(run)
	return _c
}

// GetOwner provides a mock function for the type MockCommonRepository
func (_mock *MockCommonRepository) GetOwner(ctx context.Context) (model.User, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetOwner")
	}

	var r0 model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (model.User, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) model.User); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommonRepository_GetOwner_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOwner'
type MockCommonRepository_GetOwner_Call struct {
	*mock.Call
}

// GetOwner is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCommonRepository_Expecter) GetOwner(ctx any) *MockCommonRepository_GetOwner_Call {
	return &MockCommonRepository_GetOwner_Call{Call: _e.mock.On("GetOwner", ctx)}
}

func (_c *MockCommonRepository_GetOwner_Call) Run(run func(ctx context.Context)) *MockCommonRepository_GetOwner_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCommonRepository_GetOwner_Call) Return(user model.User, err error) *MockCommonRepository_GetOwner_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockCommonRepository_GetOwner_Call) RunAndReturn(run func(ctx context.Context) (model.User, error)) *MockCommonRepository_GetOwner_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByUserId provides a mock function for the type MockCommonRepository
func (_mock *MockCommonRepository) GetUserByUserId(ctx context.Context, id string) (model.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUserId")
	}

	var r0 model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommonRepository_GetUserByUserId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByUserId'
type MockCommonRepository_GetUserByUserId_Call struct {
	*mock.Call
}

// GetUserByUserId is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCommonRepository_Expecter) GetUserByUserId(ctx any, id any) *MockCommonRepository_GetUserByUserId_Call {
	return &MockCommonRepository_GetUserByUserId_Call{Call: _e.mock.On("GetUserByUserId", ctx, id)}
}

func (_c *MockCommonRepository_GetUserByUserId_Call) Run(run func(ctx context.Context, id string)) *MockCommonRepository_GetUserByUserId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommonRepository_GetUserByUserId_Call) Return(user model.User, err error) *MockCommonRepository_GetUserByUserId_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockCommonRepository_GetUserByUserId_Call) RunAndReturn(run func(ctx context.Context, id string) (model.User, error)) *MockCommonRepository_GetUserByUserId_Call {
	_c.Call.Return(run)
	return _c
}

// TrackRSSCacheKey provides a mock function for the type MockCommonRepository
func (_mock *MockCommonRepository) TrackRSSCacheKey(cacheKey string) {
	_mock.Called(cacheKey)
	return
}

// MockCommonRepository_TrackRSSCacheKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TrackRSSCacheKey'
type MockCommonRepository_TrackRSSCacheKey_Call struct {
	*mock.Call
}

// TrackRSSCacheKey is a helper method to define mock.On call
//   - cacheKey string
func (_e *MockCommonRepository_Expecter) TrackRSSCacheKey(cacheKey any) *MockCommonRepository_TrackRSSCacheKey_Call {
	return &MockCommonRepository_TrackRSSCacheKey_Call{Call: _e.mock.On("TrackRSSCacheKey", cacheKey)}
}

func (_c *MockCommonRepository_TrackRSSCacheKey_Call) Run(run func(cacheKey string)) *MockCommonRepository_TrackRSSCacheKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCommonRepository_TrackRSSCacheKey_Call) Return() *MockCommonRepository_TrackRSSCacheKey_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCommonRepository_TrackRSSCacheKey_Call) RunAndReturn(run func(cacheKey string)) *MockCommonRepository_TrackRSSCacheKey_Call {
	_c.Run(run)
	return _c
}
