// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/access-tokens": {
            "get": {
                "description": "列出当前用户的所有访问令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统设置"
                ],
                "summary": "列出访问令牌",
                "responses": {
                    "200": {
                        "description": "列出访问令牌失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "为当前用户创建一个新的访问令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统设置"
                ],
                "summary": "创建访问令牌",
                "parameters": [
                    {
                        "description": "新的访问令牌信息",
                        "name": "accessToken",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AccessTokenSettingDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建访问令牌失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/access-tokens/{id}": {
            "delete": {
                "description": "根据 ID 删除指定的访问令牌",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统设置"
                ],
                "summary": "删除访问令牌",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "要删除的访问令牌 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除访问令牌失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/agent/info": {
            "get": {
                "description": "获取系统的 Agent 信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统设置"
                ],
                "summary": "获取 Agent 信息",
                "responses": {
                    "200": {
                        "description": "获取 Agent 信息失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/agent/recent": {
            "get": {
                "description": "获取 Agent 近期动态列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统设置"
                ],
                "summary": "获取近期动态",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/agent/settings": {
            "get": {
                "description": "获取系统的 Agent 相关设置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统设置"
                ],
                "summary": "获取 Agent 设置",
                "responses": {
                    "200": {
                        "description": "获取 Agent 设置失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "更新系统的 Agent 相关设置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统设置"
                ],
                "summary": "更新 Agent 设置",
                "parameters": [
                    {
                        "description": "新的 Agent 设置",
                        "name": "settings",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.AgentSettingDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新 Agent 设置失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/backup/export": {
            "get": {
                "description": "用户导出备份文件，成功后触发文件下载",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "系统备份"
                ],
                "summary": "导出数据备份",
                "responses": {
                    "200": {
                        "description": "导出备份失败",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/backup/schedule": {
            "get": {
                "description": "获取系统的定期备份计划设置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统设置"
                ],
                "summary": "获取备份计划",
                "responses": {
                    "200": {
                        "description": "获取备份计划失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "为系统设置定期备份计划",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统设置"
                ],
                "summary": "更新备份计划",
                "parameters": [
                    {
                        "description": "备份计划设置",
                        "name": "backupSchedule",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.BackupScheduleDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "设置备份计划失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/backup/snapshot": {
            "post": {
                "description": "仅在服务端创建本地快照；若配置了 S3 则尝试上传（失败静默）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统备份"
                ],
                "summary": "手动创建快照",
                "responses": {
                    "200": {
                        "description": "创建快照失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/backup/snapshot/{taskId}": {
            "get": {
                "description": "根据 taskId 查询创建快照任务的执行状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统备份"
                ],
                "summary": "查询快照任务状态",
                "responses": {
                    "200": {
                        "description": "查询快照状态失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/comments": {
            "get": {
                "description": "按动态 ID 获取评论列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论"
                ],
                "summary": "获取评论列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "提交新评论",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论"
                ],
                "summary": "创建评论",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/comments/form": {
            "get": {
                "description": "获取评论发布所需表单元数据",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论"
                ],
                "summary": "获取评论表单配置",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/comments/integration": {
            "post": {
                "description": "供第三方集成平台（AI / 自动化）通过 access token 发布评论，免验证码与表单 token。需要 comment:write scope 与 integration audience。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论"
                ],
                "summary": "集成评论",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer \u003caccess_token\u003e",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "请求体",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/comments/public": {
            "get": {
                "description": "获取公开评论流",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论"
                ],
                "summary": "获取公开评论",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/connect": {
            "get": {
                "description": "获取当前实例的连接详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "连接管理"
                ],
                "summary": "获取当前实例的连接信息",
                "responses": {
                    "200": {
                        "description": "获取连接信息失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/connect/list": {
            "get": {
                "description": "获取当前实例添加的所有连接列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "连接管理"
                ],
                "summary": "获取所有连接",
                "responses": {
                    "200": {
                        "description": "获取连接列表失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/connects": {
            "post": {
                "description": "用户添加一个新的连接",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "连接管理"
                ],
                "summary": "添加连接",
                "parameters": [
                    {
                        "description": "连接信息",
                        "name": "connected",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Connected"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "添加连接失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/connects/info": {
            "get": {
                "description": "获取当前用户所有已添加的连接的详细信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "连接管理"
                ],
                "summary": "获取所有添加的连接信息",
                "responses": {
                    "200": {
                        "description": "获取连接信息失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/connects/{id}": {
            "delete": {
                "description": "用户根据ID删除一个已添加的连接",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "连接管理"
                ],
                "summary": "删除连接",
                "parameters": [
                    {
                        "type": "string",
                        "description": "连接ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除连接失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/echo": {
            "put": {
                "description": "更新指定的Echo动态内容",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Echo"
                ],
                "summary": "更新Echo",
                "parameters": [
                    {
                        "description": "要更新的Echo内容",
                        "name": "echo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.EchoUpsertDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "用户创建一条新的Echo动态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Echo"
                ],
                "summary": "创建新的Echo",
                "parameters": [
                    {
                        "description": "Echo内容",
                        "name": "echo",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.EchoUpsertDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/echo/hot": {
            "get": {
                "description": "从最近发布的动态池中按「点赞数 + 已审核评论数×2」计算热度并排序，返回前若干条 Echo。需走认证路由（无有效 token 时按匿名处理）；管理员可包含私有 Echo。查询参数 limit 为可选正整数，默认 5，服务端最大返回 20 条；无效或非正整数时使用默认值。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Echo"
                ],
                "summary": "获取热门 Echo 列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "返回条数，默认 5，最大 20",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/echo/like/{id}": {
            "put": {
                "description": "根据ID为指定的Echo动态点赞",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Echo"
                ],
                "summary": "点赞Echo",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Echo ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "点赞失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/echo/page": {
            "get": {
                "description": "Deprecated: 请使用 POST /echo/query 替代。获取Echo列表，支持分页，兼容 GET Query 和 POST JSON 请求",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Echo"
                ],
                "summary": "获取Echo列表（分页）[Deprecated]",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码（GET方式）",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量（GET方式）",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "description": "分页参数（POST方式）",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/model.PageQueryDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "Deprecated: 请使用 POST /echo/query 替代。获取Echo列表，支持分页，兼容 GET Query 和 POST JSON 请求",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Echo"
                ],
                "summary": "获取Echo列表（分页）[Deprecated]",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "页码（GET方式）",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量（GET方式）",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "description": "分页参数（POST方式）",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/model.PageQueryDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/echo/query": {
            "post": {
                "description": "统一的 Echo 查询接口，支持分页、搜索、标签过滤、排序等组合条件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Echo"
                ],
                "summary": "统一查询 Echo 列表",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.EchoQueryDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "查询失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/echo/tag/{tagid}": {
            "get": {
                "description": "Deprecated: 请使用 POST /echo/query 的 tagIds 参数替代。根据标签 ID 获取包含该标签的 Echo 列表，支持 query 分页与搜索",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Echo"
                ],
                "summary": "获取指定标签 ID 的 Echo 列表 [Deprecated]",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "标签 ID",
                        "name": "tagid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "搜索关键字",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/echo/today": {
            "get": {
                "description": "获取当前用户今天发布的所有Echo动态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Echo"
                ],
                "summary": "获取今天的Echo列表",
                "responses": {
                    "200": {
                        "description": "获取失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/echo/{id}": {
            "get": {
                "description": "根据ID获取指定的Echo动态详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Echo"
                ],
                "summary": "获取指定ID的Echo",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Echo ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "获取失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "根据ID删除指定的Echo动态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Echo"
                ],
                "summary": "删除Echo",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Echo ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/file/stream": {
            "get": {
                "description": "按路径读取并返回文件流",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "按路径流式读取文件",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        },
        "/file/tree": {
            "get": {
                "description": "获取文件树结构",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "文件树",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/file/{id}": {
            "get": {
                "description": "通过 ID 查询文件元信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "按 ID 获取文件",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "description": "根据 ID 删除文件",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "删除文件",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/file/{id}/meta": {
            "put": {
                "description": "用于 ObjectFS 预签名直传完成后回填 size/width/height",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "File"
                ],
                "summary": "更新对象存储文件元信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "文件ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "文件元信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UpdateFileMetaDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/file/{id}/stream": {
            "get": {
                "description": "通过 ID 读取并返回文件流",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "按 ID 流式读取文件",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        },
        "/files": {
            "get": {
                "description": "分页获取文件列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "文件列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/files/external": {
            "post": {
                "description": "创建外部 URL 文件记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "创建外链文件",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/files/presign": {
            "put": {
                "description": "获取文件直传预签名 URL",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "获取文件预签名 URL",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/files/upload": {
            "post": {
                "description": "上传文件到存储系统",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "文件管理"
                ],
                "summary": "上传文件",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "description": "服务健康检查接口",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统"
                ],
                "summary": "健康检查",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/init/owner": {
            "post": {
                "description": "创建首个 Owner 账号",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "初始化"
                ],
                "summary": "初始化 Owner",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/init/status": {
            "get": {
                "description": "获取系统初始化状态",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "初始化"
                ],
                "summary": "获取初始化状态",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "用户通过用户名和密码登录，返回 JWT Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户认证"
                ],
                "summary": "用户登录接口",
                "parameters": [
                    {
                        "description": "登录请求体",
                        "name": "login",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.LoginDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "登录失败，返回错误信息",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/migration/cancel": {
            "post": {
                "description": "取消当前迁移任务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "迁移"
                ],
                "summary": "取消迁移",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/migration/cleanup": {
            "post": {
                "description": "清理迁移临时文件与状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "迁移"
                ],
                "summary": "清理迁移",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/migration/start": {
            "post": {
                "description": "启动迁移任务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "迁移"
                ],
                "summary": "开始迁移",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/migration/status": {
            "get": {
                "description": "查询当前迁移任务状态",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "迁移"
                ],
                "summary": "迁移状态",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/migration/upload": {
            "post": {
                "description": "上传迁移源文件",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "迁移"
                ],
                "summary": "上传迁移包",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/oauth2/settings": {
            "get": {
                "description": "获取系统的 OAuth2 相关设置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统设置"
                ],
                "summary": "获取 OAuth2 设置",
                "responses": {
                    "200": {
                        "description": "获取 OAuth2 设置失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "更新系统的 OAuth2 相关设置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统设置"
                ],
                "summary": "更新 OAuth2 设置",
                "parameters": [
                    {
                        "description": "新的 OAuth 设置",
                        "name": "oauthSettings",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.OAuth2SettingDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新 OAuth 设置失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/oauth2/status": {
            "get": {
                "description": "获取系统的 OAuth2 启用状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统设置"
                ],
                "summary": "获取 OAuth2 状态",
                "responses": {
                    "200": {
                        "description": "获取 OAuth2 状态失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/panel/comments": {
            "get": {
                "description": "管理后台获取评论列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论管理"
                ],
                "summary": "评论管理列表",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/panel/comments/batch": {
            "post": {
                "description": "管理后台批量操作评论",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论管理"
                ],
                "summary": "批量操作评论",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/panel/comments/settings": {
            "get": {
                "description": "管理后台获取评论设置",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论管理"
                ],
                "summary": "获取评论设置",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "put": {
                "description": "管理后台更新评论设置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论管理"
                ],
                "summary": "更新评论设置",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/panel/comments/settings/test-email": {
            "post": {
                "description": "管理后台发送评论邮件测试",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论管理"
                ],
                "summary": "测试评论邮件",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/panel/comments/{id}": {
            "get": {
                "description": "管理后台按 ID 获取评论详情",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论管理"
                ],
                "summary": "获取评论详情",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "description": "管理后台删除评论",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论管理"
                ],
                "summary": "删除评论",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/panel/comments/{id}/hot": {
            "patch": {
                "description": "管理后台更新评论热度/置顶状态",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论管理"
                ],
                "summary": "更新评论置顶",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/panel/comments/{id}/status": {
            "patch": {
                "description": "管理后台更新评论状态",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "评论管理"
                ],
                "summary": "更新评论状态",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/passkey/settings": {
            "get": {
                "description": "获取系统的 Passkey(WebAuthn) 相关设置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统设置"
                ],
                "summary": "获取 Passkey 设置",
                "responses": {
                    "200": {
                        "description": "获取 Passkey 设置失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "更新系统的 Passkey(WebAuthn) 相关设置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统设置"
                ],
                "summary": "更新 Passkey 设置",
                "parameters": [
                    {
                        "description": "新的 Passkey 设置",
                        "name": "passkeySettings",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.PasskeySettingDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新 Passkey 设置失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/passkey/status": {
            "get": {
                "description": "获取系统的 Passkey(WebAuthn) 就绪状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统设置"
                ],
                "summary": "获取 Passkey 状态",
                "responses": {
                    "200": {
                        "description": "获取 Passkey 状态失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "通过提交用户名、密码等信息完成注册",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户认证"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "注册请求体",
                        "name": "register",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.RegisterDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求参数错误或注册失败，code=0，msg错误描述",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/rss": {
            "get": {
                "description": "获取 RSS/Atom 订阅源",
                "produces": [
                    "application/rss+xml"
                ],
                "tags": [
                    "通用功能"
                ],
                "summary": "获取 RSS",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/s3/settings": {
            "get": {
                "description": "获取系统的 S3 存储相关设置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统设置"
                ],
                "summary": "获取 S3 存储设置",
                "responses": {
                    "200": {
                        "description": "获取 S3 存储设置失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "更新系统的 S3 存储相关设置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统设置"
                ],
                "summary": "更新 S3 存储设置",
                "parameters": [
                    {
                        "description": "新的 S3 存储设置",
                        "name": "s3Settings",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.S3SettingDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新 S3 存储设置失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/settings": {
            "get": {
                "description": "获取系统的全局设置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统设置"
                ],
                "summary": "获取设置",
                "responses": {
                    "200": {
                        "description": "获取设置失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "更新系统的全局设置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统设置"
                ],
                "summary": "更新设置",
                "parameters": [
                    {
                        "description": "新的系统设置",
                        "name": "settings",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.SystemSettingDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新设置失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/system/logs": {
            "get": {
                "description": "获取系统日志列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统"
                ],
                "summary": "系统日志",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/system/logs/stream": {
            "get": {
                "description": "SSE 方式订阅系统日志",
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "系统"
                ],
                "summary": "系统日志流",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/system/visitor-stats": {
            "get": {
                "description": "获取近七天 PV/UV 统计数据",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统"
                ],
                "summary": "近七天访客统计",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/tag/{id}": {
            "delete": {
                "description": "根据ID删除指定的标签",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tag"
                ],
                "summary": "删除标签",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "标签 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/tags": {
            "get": {
                "description": "获取所有标签及其使用次数",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tag"
                ],
                "summary": "获取所有标签",
                "responses": {
                    "200": {
                        "description": "获取失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/user": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取当前认证用户的详细信息，密码字段不会返回",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "获取当前用户信息",
                "responses": {
                    "200": {
                        "description": "获取失败，code=0，msg错误描述",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "接口会根据请求体更新用户相关字段，需携带有效的用户身份（如 JWT）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "更新当前用户的信息",
                "parameters": [
                    {
                        "description": "用户更新信息",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserInfoDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求参数错误或更新失败，code=0，msg错误描述",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/user/admin/{id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "通过用户ID更新其管理员权限，接口调用者需拥有相应权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "更新用户权限（管理员权限）",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "参数错误或更新失败，code=0，msg错误描述",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/user/{id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根据用户ID删除用户，调用者需具备相应权限",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "删除用户",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "参数错误或删除失败，code=0，msg错误描述",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取系统中所有用户的详细信息，接口需要认证",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "获取所有用户",
                "responses": {
                    "200": {
                        "description": "获取失败，code=0，msg错误描述",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/webhook": {
            "get": {
                "description": "获取系统中配置的所有 Webhook 列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统设置"
                ],
                "summary": "获取所有 Webhook",
                "responses": {
                    "200": {
                        "description": "获取 Webhook 列表失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "创建一个新的 Webhook 配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统设置"
                ],
                "summary": "创建新的 Webhook",
                "parameters": [
                    {
                        "description": "新的 Webhook 配置",
                        "name": "webhook",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.WebhookDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "创建 Webhook 失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/webhook/{id}": {
            "put": {
                "description": "根据 ID 更新指定的 Webhook 配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统设置"
                ],
                "summary": "更新 Webhook",
                "parameters": [
                    {
                        "type": "string",
                        "description": "要更新的 Webhook ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "新的 Webhook 配置",
                        "name": "webhook",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.WebhookDto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新 Webhook 失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "根据 ID 删除指定的 Webhook 配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统设置"
                ],
                "summary": "删除 Webhook",
                "parameters": [
                    {
                        "type": "string",
                        "description": "要删除的 Webhook ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除 Webhook 失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/webhook/{id}/test": {
            "post": {
                "description": "根据 ID 触发一次 Webhook 测试请求",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统设置"
                ],
                "summary": "测试 Webhook",
                "parameters": [
                    {
                        "type": "string",
                        "description": "要测试的 Webhook ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "测试 Webhook 失败",
                        "schema": {
                            "$ref": "#/definitions/handler.Response"
                        }
                    }
                }
            }
        },
        "/website/title": {
            "get": {
                "description": "根据 URL 获取网站标题",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "通用功能"
                ],
                "summary": "获取网站标题",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Code 状态码，非0时表示自定义HTTP业务状态码",
                    "type": "integer"
                },
                "data": {
                    "description": "Data 响应数据，具体内容因接口而异"
                },
                "error_code": {
                    "description": "ErrorCode 业务错误码，可选",
                    "type": "string"
                },
                "message_key": {
                    "description": "MessageKey 国际化消息 key，可选",
                    "type": "string"
                },
                "message_params": {
                    "description": "MessageParams 国际化模板参数，可选",
                    "type": "object",
                    "additionalProperties": {}
                },
                "msg": {
                    "description": "Msg 返回信息，通常是状态描述",
                    "type": "string"
                }
            }
        },
        "model.AccessTokenSettingDto": {
            "type": "object",
            "properties": {
                "audience": {
                    "description": "访问令牌受众（public-client/cli/integration）",
                    "type": "string"
                },
                "expiry": {
                    "description": "访问令牌过期策略（8_hours/1_month/never）",
                    "type": "string"
                },
                "name": {
                    "description": "访问令牌名称",
                    "type": "string"
                },
                "scopes": {
                    "description": "访问令牌权限范围",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "model.AgentSettingDto": {
            "type": "object",
            "properties": {
                "api_key": {
                    "description": "LLM API Key",
                    "type": "string"
                },
                "base_url": {
                    "description": "自定义 API URL（可选）",
                    "type": "string"
                },
                "enable": {
                    "description": "是否启用 Agent 功能",
                    "type": "boolean"
                },
                "model": {
                    "description": "LLM 模型名称",
                    "type": "string"
                },
                "prompt": {
                    "description": "Agent 额外使用的提示词",
                    "type": "string"
                },
                "provider": {
                    "description": "LLM 提供商 （OpenAI、DeepSeek、Anthropic、Gemini、阿里百炼、Ollama等）",
                    "type": "string"
                }
            }
        },
        "model.BackupScheduleDto": {
            "type": "object",
            "properties": {
                "cron_expression": {
                    "description": "备份计划的 Cron 表达式",
                    "type": "string"
                },
                "enable": {
                    "description": "是否启用备份计划",
                    "type": "boolean"
                }
            }
        },
        "model.Connected": {
            "type": "object",
            "properties": {
                "connect_url": {
                    "description": "连接地址",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "model.EchoExtensionDto": {
            "type": "object",
            "properties": {
                "payload": {
                    "type": "object",
                    "additionalProperties": true
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "model.EchoQueryDto": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "search": {
                    "type": "string"
                },
                "sortBy": {
                    "type": "string"
                },
                "sortOrder": {
                    "type": "string"
                },
                "tagIds": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "model.EchoUpsertDto": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "echo_files": {
                    "type": "array",
                    "items": {
                        "type": "object"
                    }
                },
                "extension": {
                    "$ref": "#/definitions/model.EchoExtensionDto"
                },
                "id": {
                    "type": "string"
                },
                "layout": {
                    "type": "string"
                },
                "private": {
                    "type": "boolean"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Tag"
                    }
                }
            }
        },
        "model.LoginDto": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "model.OAuth2SettingDto": {
            "type": "object",
            "properties": {
                "auth_redirect_allowed_return_urls": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "auth_url": {
                    "type": "string"
                },
                "client_id": {
                    "type": "string"
                },
                "client_secret": {
                    "type": "string"
                },
                "cors_allowed_origins": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "enable": {
                    "type": "boolean"
                },
                "is_oidc": {
                    "description": "是否启用 OIDC",
                    "type": "boolean"
                },
                "issuer": {
                    "description": "OIDC 颁发者",
                    "type": "string"
                },
                "jwks_url": {
                    "description": "OIDC JWKS URL",
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "redirect_uri": {
                    "type": "string"
                },
                "scopes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "token_url": {
                    "type": "string"
                },
                "user_info_url": {
                    "type": "string"
                }
            }
        },
        "model.PageQueryDto": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "search": {
                    "type": "string"
                }
            }
        },
        "model.PasskeySettingDto": {
            "type": "object",
            "properties": {
                "webauthn_allowed_origins": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "webauthn_rp_id": {
                    "type": "string"
                }
            }
        },
        "model.RegisterDto": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "model.S3SettingDto": {
            "type": "object",
            "properties": {
                "access_key": {
                    "description": "访问密钥 ID",
                    "type": "string"
                },
                "bucket_name": {
                    "description": "存储桶名称",
                    "type": "string"
                },
                "cdn_url": {
                    "description": "CDN 加速域名（可选，没有就走 Endpoint）",
                    "type": "string"
                },
                "enable": {
                    "description": "是否启用 S3 存储",
                    "type": "boolean"
                },
                "endpoint": {
                    "description": "S3 端点",
                    "type": "string"
                },
                "path_prefix": {
                    "description": "存储路径前缀，例如 \"uploads/\"，方便隔离目录",
                    "type": "string"
                },
                "provider": {
                    "description": "S3 服务提供商，例如 \"aws\", \"aliyun\", \"minio\", \"other\"",
                    "type": "string"
                },
                "public_read": {
                    "description": "上传时是否默认设置对象为 public-read",
                    "type": "boolean"
                },
                "region": {
                    "description": "区域",
                    "type": "string"
                },
                "secret_key": {
                    "description": "秘密访问密钥",
                    "type": "string"
                },
                "use_ssl": {
                    "description": "是否使用 SSL",
                    "type": "boolean"
                }
            }
        },
        "model.SystemSettingDto": {
            "type": "object",
            "properties": {
                "ICP_number": {
                    "description": "备案号",
                    "type": "string"
                },
                "allow_register": {
                    "description": "是否允许注册",
                    "type": "boolean"
                },
                "custom_css": {
                    "description": "自定义 CSS",
                    "type": "string"
                },
                "custom_js": {
                    "description": "自定义 JS",
                    "type": "string"
                },
                "default_locale": {
                    "description": "站点默认语言（如 zh-CN / en-US）",
                    "type": "string"
                },
                "footer_content": {
                    "description": "自定义页脚内容",
                    "type": "string"
                },
                "footer_link": {
                    "description": "自定义页脚链接",
                    "type": "string"
                },
                "meting_api": {
                    "description": "Meting API 地址",
                    "type": "string"
                },
                "server_logo": {
                    "description": "服务器Logo",
                    "type": "string"
                },
                "server_logo_file_id": {
                    "description": "服务器Logo文件ID（用于确认临时文件）",
                    "type": "string"
                },
                "server_name": {
                    "description": "服务器名称",
                    "type": "string"
                },
                "server_url": {
                    "description": "服务器地址",
                    "type": "string"
                },
                "site_title": {
                    "description": "站点标题",
                    "type": "string"
                }
            }
        },
        "model.Tag": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "usage_count": {
                    "type": "integer"
                }
            }
        },
        "model.UpdateFileMetaDto": {
            "type": "object",
            "required": [
                "size"
            ],
            "properties": {
                "content_type": {
                    "type": "string"
                },
                "height": {
                    "type": "integer"
                },
                "size": {
                    "type": "integer",
                    "minimum": 0
                },
                "width": {
                    "type": "integer"
                }
            }
        },
        "model.UserInfoDto": {
            "type": "object",
            "properties": {
                "avatar": {
                    "description": "头像地址\nexample: https://example.com/avatar.png",
                    "type": "string"
                },
                "avatar_file_id": {
                    "description": "头像文件ID（用于确认临时文件转正）\nexample: 0195e2a7-54a9-7bcf-8df5-6d81d671f5c7",
                    "type": "string"
                },
                "email": {
                    "description": "邮箱\nexample: owner@example.com",
                    "type": "string"
                },
                "is_admin": {
                    "description": "是否为管理员\nexample: false",
                    "type": "boolean"
                },
                "is_owner": {
                    "description": "是否为Owner\nexample: false",
                    "type": "boolean"
                },
                "locale": {
                    "description": "语言偏好\nexample: zh-CN",
                    "type": "string"
                },
                "password": {
                    "description": "密码\nexample: 123456",
                    "type": "string"
                },
                "username": {
                    "description": "用户名\nexample: linsnow",
                    "type": "string"
                }
            }
        },
        "model.WebhookDto": {
            "type": "object",
            "properties": {
                "is_active": {
                    "description": "启用/禁用状态",
                    "type": "boolean"
                },
                "name": {
                    "description": "Webhook 名称",
                    "type": "string"
                },
                "secret": {
                    "description": "签名密钥，用于请求验证（HMAC等）",
                    "type": "string"
                },
                "url": {
                    "description": "Webhook URL",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:6277",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Ech0 API 文档",
	Description:      "开源、自托管轻量级发布平台 Ech0 的 API 文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
