// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2025-2026 lin-snow

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package embeddingmock

import (
	"context"

	model0 "github.com/lin-snow/ech0/internal/model/echo"
	model1 "github.com/lin-snow/ech0/internal/model/embedding"
	"github.com/lin-snow/ech0/internal/model/setting"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEmbedder creates a new instance of MockEmbedder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmbedder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmbedder {
	mock := &MockEmbedder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEmbedder is an autogenerated mock type for the Embedder type
type MockEmbedder struct {
	mock.Mock
}

type MockEmbedder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmbedder) EXPECT() *MockEmbedder_Expecter {
	return &MockEmbedder_Expecter{mock: &_m.Mock}
}

// Embed provides a mock function for the type MockEmbedder
func (_mock *MockEmbedder) Embed(ctx context.Context, setting model.EmbeddingSetting, inputs []string) ([][]float32, error) {
	ret := _mock.Called(ctx, setting, inputs)

	if len(ret) == 0 {
		panic("no return value specified for Embed")
	}

	var r0 [][]float32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.EmbeddingSetting, []string) ([][]float32, error)); ok {
		return returnFunc(ctx, setting, inputs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.EmbeddingSetting, []string) [][]float32); ok {
		r0 = returnFunc(ctx, setting, inputs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]float32)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.EmbeddingSetting, []string) error); ok {
		r1 = returnFunc(ctx, setting, inputs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmbedder_Embed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Embed'
type MockEmbedder_Embed_Call struct {
	*mock.Call
}

// Embed is a helper method to define mock.On call
//   - ctx context.Context
//   - setting model.EmbeddingSetting
//   - inputs []string
func (_e *MockEmbedder_Expecter) Embed(ctx any, setting any, inputs any) *MockEmbedder_Embed_Call {
	return &MockEmbedder_Embed_Call{Call: _e.mock.On("Embed", ctx, setting, inputs)}
}

func (_c *MockEmbedder_Embed_Call) Run(run func(ctx context.Context, setting model.EmbeddingSetting, inputs []string)) *MockEmbedder_Embed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.EmbeddingSetting
		if args[1] != nil {
			arg1 = args[1].(model.EmbeddingSetting)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEmbedder_Embed_Call) Return(float32ss [][]float32, err error) *MockEmbedder_Embed_Call {
	_c.Call.Return(float32ss, err)
	return _c
}

func (_c *MockEmbedder_Embed_Call) RunAndReturn(run func(ctx context.Context, setting model.EmbeddingSetting, inputs []string) ([][]float32, error)) *MockEmbedder_Embed_Call {
	_c.Call.Return(run)
	return _c
}

// EmbedOne provides a mock function for the type MockEmbedder
func (_mock *MockEmbedder) EmbedOne(ctx context.Context, setting model.EmbeddingSetting, input string) ([]float32, error) {
	ret := _mock.Called(ctx, setting, input)

	if len(ret) == 0 {
		panic("no return value specified for EmbedOne")
	}

	var r0 []float32
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.EmbeddingSetting, string) ([]float32, error)); ok {
		return returnFunc(ctx, setting, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.EmbeddingSetting, string) []float32); ok {
		r0 = returnFunc(ctx, setting, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]float32)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.EmbeddingSetting, string) error); ok {
		r1 = returnFunc(ctx, setting, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmbedder_EmbedOne_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EmbedOne'
type MockEmbedder_EmbedOne_Call struct {
	*mock.Call
}

// EmbedOne is a helper method to define mock.On call
//   - ctx context.Context
//   - setting model.EmbeddingSetting
//   - input string
func (_e *MockEmbedder_Expecter) EmbedOne(ctx any, setting any, input any) *MockEmbedder_EmbedOne_Call {
	return &MockEmbedder_EmbedOne_Call{Call: _e.mock.On("EmbedOne", ctx, setting, input)}
}

func (_c *MockEmbedder_EmbedOne_Call) Run(run func(ctx context.Context, setting model.EmbeddingSetting, input string)) *MockEmbedder_EmbedOne_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.EmbeddingSetting
		if args[1] != nil {
			arg1 = args[1].(model.EmbeddingSetting)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEmbedder_EmbedOne_Call) Return(float32s []float32, err error) *MockEmbedder_EmbedOne_Call {
	_c.Call.Return(float32s, err)
	return _c
}

func (_c *MockEmbedder_EmbedOne_Call) RunAndReturn(run func(ctx context.Context, setting model.EmbeddingSetting, input string) ([]float32, error)) *MockEmbedder_EmbedOne_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIndexer creates a new instance of MockIndexer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIndexer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIndexer {
	mock := &MockIndexer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIndexer is an autogenerated mock type for the Indexer type
type MockIndexer struct {
	mock.Mock
}

type MockIndexer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIndexer) EXPECT() *MockIndexer_Expecter {
	return &MockIndexer_Expecter{mock: &_m.Mock}
}

// IndexEcho provides a mock function for the type MockIndexer
func (_mock *MockIndexer) IndexEcho(ctx context.Context, echo model0.Echo) error {
	ret := _mock.Called(ctx, echo)

	if len(ret) == 0 {
		panic("no return value specified for IndexEcho")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model0.Echo) error); ok {
		r0 = returnFunc(ctx, echo)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIndexer_IndexEcho_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IndexEcho'
type MockIndexer_IndexEcho_Call struct {
	*mock.Call
}

// IndexEcho is a helper method to define mock.On call
//   - ctx context.Context
//   - echo model0.Echo
func (_e *MockIndexer_Expecter) IndexEcho(ctx any, echo any) *MockIndexer_IndexEcho_Call {
	return &MockIndexer_IndexEcho_Call{Call: _e.mock.On("IndexEcho", ctx, echo)}
}

func (_c *MockIndexer_IndexEcho_Call) Run(run func(ctx context.Context, echo model0.Echo)) *MockIndexer_IndexEcho_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model0.Echo
		if args[1] != nil {
			arg1 = args[1].(model0.Echo)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIndexer_IndexEcho_Call) Return(err error) *MockIndexer_IndexEcho_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIndexer_IndexEcho_Call) RunAndReturn(run func(ctx context.Context, echo model0.Echo) error) *MockIndexer_IndexEcho_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveEcho provides a mock function for the type MockIndexer
func (_mock *MockIndexer) RemoveEcho(ctx context.Context, echoID string) error {
	ret := _mock.Called(ctx, echoID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveEcho")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, echoID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIndexer_RemoveEcho_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveEcho'
type MockIndexer_RemoveEcho_Call struct {
	*mock.Call
}

// RemoveEcho is a helper method to define mock.On call
//   - ctx context.Context
//   - echoID string
func (_e *MockIndexer_Expecter) RemoveEcho(ctx any, echoID any) *MockIndexer_RemoveEcho_Call {
	return &MockIndexer_RemoveEcho_Call{Call: _e.mock.On("RemoveEcho", ctx, echoID)}
}

func (_c *MockIndexer_RemoveEcho_Call) Run(run func(ctx context.Context, echoID string)) *MockIndexer_RemoveEcho_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIndexer_RemoveEcho_Call) Return(err error) *MockIndexer_RemoveEcho_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIndexer_RemoveEcho_Call) RunAndReturn(run func(ctx context.Context, echoID string) error) *MockIndexer_RemoveEcho_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// ClearAll provides a mock function for the type MockRepository
func (_mock *MockRepository) ClearAll(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ClearAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_ClearAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearAll'
type MockRepository_ClearAll_Call struct {
	*mock.Call
}

// ClearAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) ClearAll(ctx any) *MockRepository_ClearAll_Call {
	return &MockRepository_ClearAll_Call{Call: _e.mock.On("ClearAll", ctx)}
}

func (_c *MockRepository_ClearAll_Call) Run(run func(ctx context.Context)) *MockRepository_ClearAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_ClearAll_Call) Return(err error) *MockRepository_ClearAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_ClearAll_Call) RunAndReturn(run func(ctx context.Context) error) *MockRepository_ClearAll_Call {
	_c.Call.Return(run)
	return _c
}

// Count provides a mock function for the type MockRepository
func (_mock *MockRepository) Count(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) Count(ctx any) *MockRepository_Count_Call {
	return &MockRepository_Count_Call{Call: _e.mock.On("Count", ctx)}
}

func (_c *MockRepository_Count_Call) Run(run func(ctx context.Context)) *MockRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_Count_Call) Return(n int64, err error) *MockRepository_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRepository_Count_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockRepository
func (_mock *MockRepository) Delete(ctx context.Context, echoID string) error {
	ret := _mock.Called(ctx, echoID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, echoID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - echoID string
func (_e *MockRepository_Expecter) Delete(ctx any, echoID any) *MockRepository_Delete_Call {
	return &MockRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, echoID)}
}

func (_c *MockRepository_Delete_Call) Run(run func(ctx context.Context, echoID string)) *MockRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Delete_Call) Return(err error) *MockRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, echoID string) error) *MockRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DropVecTable provides a mock function for the type MockRepository
func (_mock *MockRepository) DropVecTable(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DropVecTable")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_DropVecTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DropVecTable'
type MockRepository_DropVecTable_Call struct {
	*mock.Call
}

// DropVecTable is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) DropVecTable(ctx any) *MockRepository_DropVecTable_Call {
	return &MockRepository_DropVecTable_Call{Call: _e.mock.On("DropVecTable", ctx)}
}

func (_c *MockRepository_DropVecTable_Call) Run(run func(ctx context.Context)) *MockRepository_DropVecTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRepository_DropVecTable_Call) Return(err error) *MockRepository_DropVecTable_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_DropVecTable_Call) RunAndReturn(run func(ctx context.Context) error) *MockRepository_DropVecTable_Call {
	_c.Call.Return(run)
	return _c
}

// EnsureVecTable provides a mock function for the type MockRepository
func (_mock *MockRepository) EnsureVecTable(ctx context.Context, dim int) error {
	ret := _mock.Called(ctx, dim)

	if len(ret) == 0 {
		panic("no return value specified for EnsureVecTable")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, dim)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_EnsureVecTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureVecTable'
type MockRepository_EnsureVecTable_Call struct {
	*mock.Call
}

// EnsureVecTable is a helper method to define mock.On call
//   - ctx context.Context
//   - dim int
func (_e *MockRepository_Expecter) EnsureVecTable(ctx any, dim any) *MockRepository_EnsureVecTable_Call {
	return &MockRepository_EnsureVecTable_Call{Call: _e.mock.On("EnsureVecTable", ctx, dim)}
}

func (_c *MockRepository_EnsureVecTable_Call) Run(run func(ctx context.Context, dim int)) *MockRepository_EnsureVecTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_EnsureVecTable_Call) Return(err error) *MockRepository_EnsureVecTable_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_EnsureVecTable_Call) RunAndReturn(run func(ctx context.Context, dim int) error) *MockRepository_EnsureVecTable_Call {
	_c.Call.Return(run)
	return _c
}

// GetMeta provides a mock function for the type MockRepository
func (_mock *MockRepository) GetMeta(ctx context.Context, echoID string) (*model1.EchoEmbedding, bool, error) {
	ret := _mock.Called(ctx, echoID)

	if len(ret) == 0 {
		panic("no return value specified for GetMeta")
	}

	var r0 *model1.EchoEmbedding
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model1.EchoEmbedding, bool, error)); ok {
		return returnFunc(ctx, echoID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model1.EchoEmbedding); ok {
		r0 = returnFunc(ctx, echoID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model1.EchoEmbedding)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = returnFunc(ctx, echoID)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, echoID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepository_GetMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMeta'
type MockRepository_GetMeta_Call struct {
	*mock.Call
}

// GetMeta is a helper method to define mock.On call
//   - ctx context.Context
//   - echoID string
func (_e *MockRepository_Expecter) GetMeta(ctx any, echoID any) *MockRepository_GetMeta_Call {
	return &MockRepository_GetMeta_Call{Call: _e.mock.On("GetMeta", ctx, echoID)}
}

func (_c *MockRepository_GetMeta_Call) Run(run func(ctx context.Context, echoID string)) *MockRepository_GetMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_GetMeta_Call) Return(echoEmbedding *model1.EchoEmbedding, b bool, err error) *MockRepository_GetMeta_Call {
	_c.Call.Return(echoEmbedding, b, err)
	return _c
}

func (_c *MockRepository_GetMeta_Call) RunAndReturn(run func(ctx context.Context, echoID string) (*model1.EchoEmbedding, bool, error)) *MockRepository_GetMeta_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type MockRepository
func (_mock *MockRepository) Search(ctx context.Context, vector []float32, k int, authorUsername string) ([]model1.SearchResult, error) {
	ret := _mock.Called(ctx, vector, k, authorUsername)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []model1.SearchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []float32, int, string) ([]model1.SearchResult, error)); ok {
		return returnFunc(ctx, vector, k, authorUsername)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []float32, int, string) []model1.SearchResult); ok {
		r0 = returnFunc(ctx, vector, k, authorUsername)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model1.SearchResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []float32, int, string) error); ok {
		r1 = returnFunc(ctx, vector, k, authorUsername)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockRepository_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - vector []float32
//   - k int
//   - authorUsername string
func (_e *MockRepository_Expecter) Search(ctx any, vector any, k any, authorUsername any) *MockRepository_Search_Call {
	return &MockRepository_Search_Call{Call: _e.mock.On("Search", ctx, vector, k, authorUsername)}
}

func (_c *MockRepository_Search_Call) Run(run func(ctx context.Context, vector []float32, k int, authorUsername string)) *MockRepository_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []float32
		if args[1] != nil {
			arg1 = args[1].([]float32)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_Search_Call) Return(searchResults []model1.SearchResult, err error) *MockRepository_Search_Call {
	_c.Call.Return(searchResults, err)
	return _c
}

func (_c *MockRepository_Search_Call) RunAndReturn(run func(ctx context.Context, vector []float32, k int, authorUsername string) ([]model1.SearchResult, error)) *MockRepository_Search_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type MockRepository
func (_mock *MockRepository) Upsert(ctx context.Context, meta *model1.EchoEmbedding, vector []float32) error {
	ret := _mock.Called(ctx, meta, vector)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model1.EchoEmbedding, []float32) error); ok {
		r0 = returnFunc(ctx, meta, vector)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - meta *model1.EchoEmbedding
//   - vector []float32
func (_e *MockRepository_Expecter) Upsert(ctx any, meta any, vector any) *MockRepository_Upsert_Call {
	return &MockRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, meta, vector)}
}

func (_c *MockRepository_Upsert_Call) Run(run func(ctx context.Context, meta *model1.EchoEmbedding, vector []float32)) *MockRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model1.EchoEmbedding
		if args[1] != nil {
			arg1 = args[1].(*model1.EchoEmbedding)
		}
		var arg2 []float32
		if args[2] != nil {
			arg2 = args[2].([]float32)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_Upsert_Call) Return(err error) *MockRepository_Upsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Upsert_Call) RunAndReturn(run func(ctx context.Context, meta *model1.EchoEmbedding, vector []float32) error) *MockRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEchoReader creates a new instance of MockEchoReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEchoReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEchoReader {
	mock := &MockEchoReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEchoReader is an autogenerated mock type for the EchoReader type
type MockEchoReader struct {
	mock.Mock
}

type MockEchoReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEchoReader) EXPECT() *MockEchoReader_Expecter {
	return &MockEchoReader_Expecter{mock: &_m.Mock}
}

// GetEchosByPage provides a mock function for the type MockEchoReader
func (_mock *MockEchoReader) GetEchosByPage(page int, pageSize int, search string, showPrivate bool) ([]model0.Echo, int64) {
	ret := _mock.Called(page, pageSize, search, showPrivate)

	if len(ret) == 0 {
		panic("no return value specified for GetEchosByPage")
	}

	var r0 []model0.Echo
	var r1 int64
	if returnFunc, ok := ret.Get(0).(func(int, int, string, bool) ([]model0.Echo, int64)); ok {
		return returnFunc(page, pageSize, search, showPrivate)
	}
	if returnFunc, ok := ret.Get(0).(func(int, int, string, bool) []model0.Echo); ok {
		r0 = returnFunc(page, pageSize, search, showPrivate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model0.Echo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, int, string, bool) int64); ok {
		r1 = returnFunc(page, pageSize, search, showPrivate)
	} else {
		r1 = ret.Get(1).(int64)
	}
	return r0, r1
}

// MockEchoReader_GetEchosByPage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEchosByPage'
type MockEchoReader_GetEchosByPage_Call struct {
	*mock.Call
}

// GetEchosByPage is a helper method to define mock.On call
//   - page int
//   - pageSize int
//   - search string
//   - showPrivate bool
func (_e *MockEchoReader_Expecter) GetEchosByPage(page any, pageSize any, search any, showPrivate any) *MockEchoReader_GetEchosByPage_Call {
	return &MockEchoReader_GetEchosByPage_Call{Call: _e.mock.On("GetEchosByPage", page, pageSize, search, showPrivate)}
}

func (_c *MockEchoReader_GetEchosByPage_Call) Run(run func(page int, pageSize int, search string, showPrivate bool)) *MockEchoReader_GetEchosByPage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockEchoReader_GetEchosByPage_Call) Return(echos []model0.Echo, n int64) *MockEchoReader_GetEchosByPage_Call {
	_c.Call.Return(echos, n)
	return _c
}

func (_c *MockEchoReader_GetEchosByPage_Call) RunAndReturn(run func(page int, pageSize int, search string, showPrivate bool) ([]model0.Echo, int64)) *MockEchoReader_GetEchosByPage_Call {
	_c.Call.Return(run)
	return _c
}
