// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2025-2026 lin-snow

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package filemock

import (
	"context"
	"mime/multipart"

	"github.com/gin-gonic/gin"
	"github.com/lin-snow/ech0/internal/model/common"
	model1 "github.com/lin-snow/ech0/internal/model/file"
	model0 "github.com/lin-snow/ech0/internal/model/user"
	"github.com/lin-snow/ech0/internal/storage"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CleanupOrphanFiles provides a mock function for the type MockService
func (_mock *MockService) CleanupOrphanFiles() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CleanupOrphanFiles")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_CleanupOrphanFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanupOrphanFiles'
type MockService_CleanupOrphanFiles_Call struct {
	*mock.Call
}

// CleanupOrphanFiles is a helper method to define mock.On call
func (_e *MockService_Expecter) CleanupOrphanFiles() *MockService_CleanupOrphanFiles_Call {
	return &MockService_CleanupOrphanFiles_Call{Call: _e.mock.On("CleanupOrphanFiles")}
}

func (_c *MockService_CleanupOrphanFiles_Call) Run(run func()) *MockService_CleanupOrphanFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_CleanupOrphanFiles_Call) Return(err error) *MockService_CleanupOrphanFiles_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_CleanupOrphanFiles_Call) RunAndReturn(run func() error) *MockService_CleanupOrphanFiles_Call {
	_c.Call.Return(run)
	return _c
}

// ConfirmTempFiles provides a mock function for the type MockService
func (_mock *MockService) ConfirmTempFiles(ctx context.Context, fileIDs []string) error {
	ret := _mock.Called(ctx, fileIDs)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmTempFiles")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = returnFunc(ctx, fileIDs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_ConfirmTempFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmTempFiles'
type MockService_ConfirmTempFiles_Call struct {
	*mock.Call
}

// ConfirmTempFiles is a helper method to define mock.On call
//   - ctx context.Context
//   - fileIDs []string
func (_e *MockService_Expecter) ConfirmTempFiles(ctx any, fileIDs any) *MockService_ConfirmTempFiles_Call {
	return &MockService_ConfirmTempFiles_Call{Call: _e.mock.On("ConfirmTempFiles", ctx, fileIDs)}
}

func (_c *MockService_ConfirmTempFiles_Call) Run(run func(ctx context.Context, fileIDs []string)) *MockService_ConfirmTempFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_ConfirmTempFiles_Call) Return(err error) *MockService_ConfirmTempFiles_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_ConfirmTempFiles_Call) RunAndReturn(run func(ctx context.Context, fileIDs []string) error) *MockService_ConfirmTempFiles_Call {
	_c.Call.Return(run)
	return _c
}

// CreateExternalFile provides a mock function for the type MockService
func (_mock *MockService) CreateExternalFile(ctx context.Context, dto model.CreateExternalFileDto) (model.FileDto, error) {
	ret := _mock.Called(ctx, dto)

	if len(ret) == 0 {
		panic("no return value specified for CreateExternalFile")
	}

	var r0 model.FileDto
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.CreateExternalFileDto) (model.FileDto, error)); ok {
		return returnFunc(ctx, dto)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.CreateExternalFileDto) model.FileDto); ok {
		r0 = returnFunc(ctx, dto)
	} else {
		r0 = ret.Get(0).(model.FileDto)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.CreateExternalFileDto) error); ok {
		r1 = returnFunc(ctx, dto)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_CreateExternalFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateExternalFile'
type MockService_CreateExternalFile_Call struct {
	*mock.Call
}

// CreateExternalFile is a helper method to define mock.On call
//   - ctx context.Context
//   - dto model.CreateExternalFileDto
func (_e *MockService_Expecter) CreateExternalFile(ctx any, dto any) *MockService_CreateExternalFile_Call {
	return &MockService_CreateExternalFile_Call{Call: _e.mock.On("CreateExternalFile", ctx, dto)}
}

func (_c *MockService_CreateExternalFile_Call) Run(run func(ctx context.Context, dto model.CreateExternalFileDto)) *MockService_CreateExternalFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.CreateExternalFileDto
		if args[1] != nil {
			arg1 = args[1].(model.CreateExternalFileDto)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_CreateExternalFile_Call) Return(fileDto model.FileDto, err error) *MockService_CreateExternalFile_Call {
	_c.Call.Return(fileDto, err)
	return _c
}

func (_c *MockService_CreateExternalFile_Call) RunAndReturn(run func(ctx context.Context, dto model.CreateExternalFileDto) (model.FileDto, error)) *MockService_CreateExternalFile_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFile provides a mock function for the type MockService
func (_mock *MockService) DeleteFile(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFile'
type MockService_DeleteFile_Call struct {
	*mock.Call
}

// DeleteFile is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockService_Expecter) DeleteFile(ctx any, id any) *MockService_DeleteFile_Call {
	return &MockService_DeleteFile_Call{Call: _e.mock.On("DeleteFile", ctx, id)}
}

func (_c *MockService_DeleteFile_Call) Run(run func(ctx context.Context, id string)) *MockService_DeleteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_DeleteFile_Call) Return(err error) *MockService_DeleteFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteFile_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockService_DeleteFile_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFileRecord provides a mock function for the type MockService
func (_mock *MockService) DeleteFileRecord(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteFileRecord")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteFileRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFileRecord'
type MockService_DeleteFileRecord_Call struct {
	*mock.Call
}

// DeleteFileRecord is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockService_Expecter) DeleteFileRecord(ctx any, id any) *MockService_DeleteFileRecord_Call {
	return &MockService_DeleteFileRecord_Call{Call: _e.mock.On("DeleteFileRecord", ctx, id)}
}

func (_c *MockService_DeleteFileRecord_Call) Run(run func(ctx context.Context, id string)) *MockService_DeleteFileRecord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_DeleteFileRecord_Call) Return(err error) *MockService_DeleteFileRecord_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteFileRecord_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockService_DeleteFileRecord_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteStoredFile provides a mock function for the type MockService
func (_mock *MockService) DeleteStoredFile(storageType string, key string) error {
	ret := _mock.Called(storageType, key)

	if len(ret) == 0 {
		panic("no return value specified for DeleteStoredFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(storageType, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteStoredFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteStoredFile'
type MockService_DeleteStoredFile_Call struct {
	*mock.Call
}

// DeleteStoredFile is a helper method to define mock.On call
//   - storageType string
//   - key string
func (_e *MockService_Expecter) DeleteStoredFile(storageType any, key any) *MockService_DeleteStoredFile_Call {
	return &MockService_DeleteStoredFile_Call{Call: _e.mock.On("DeleteStoredFile", storageType, key)}
}

func (_c *MockService_DeleteStoredFile_Call) Run(run func(storageType string, key string)) *MockService_DeleteStoredFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_DeleteStoredFile_Call) Return(err error) *MockService_DeleteStoredFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteStoredFile_Call) RunAndReturn(run func(storageType string, key string) error) *MockService_DeleteStoredFile_Call {
	_c.Call.Return(run)
	return _c
}

// GetFileByID provides a mock function for the type MockService
func (_mock *MockService) GetFileByID(ctx context.Context, id string) (model.FileDto, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetFileByID")
	}

	var r0 model.FileDto
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model.FileDto, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model.FileDto); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(model.FileDto)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetFileByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFileByID'
type MockService_GetFileByID_Call struct {
	*mock.Call
}

// GetFileByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockService_Expecter) GetFileByID(ctx any, id any) *MockService_GetFileByID_Call {
	return &MockService_GetFileByID_Call{Call: _e.mock.On("GetFileByID", ctx, id)}
}

func (_c *MockService_GetFileByID_Call) Run(run func(ctx context.Context, id string)) *MockService_GetFileByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetFileByID_Call) Return(fileDto model.FileDto, err error) *MockService_GetFileByID_Call {
	_c.Call.Return(fileDto, err)
	return _c
}

func (_c *MockService_GetFileByID_Call) RunAndReturn(run func(ctx context.Context, id string) (model.FileDto, error)) *MockService_GetFileByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetFilePresignURL provides a mock function for the type MockService
func (_mock *MockService) GetFilePresignURL(ctx context.Context, dto *model.GetPresignURLDto) (model.PresignDto, error) {
	ret := _mock.Called(ctx, dto)

	if len(ret) == 0 {
		panic("no return value specified for GetFilePresignURL")
	}

	var r0 model.PresignDto
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.GetPresignURLDto) (model.PresignDto, error)); ok {
		return returnFunc(ctx, dto)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model.GetPresignURLDto) model.PresignDto); ok {
		r0 = returnFunc(ctx, dto)
	} else {
		r0 = ret.Get(0).(model.PresignDto)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *model.GetPresignURLDto) error); ok {
		r1 = returnFunc(ctx, dto)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetFilePresignURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFilePresignURL'
type MockService_GetFilePresignURL_Call struct {
	*mock.Call
}

// GetFilePresignURL is a helper method to define mock.On call
//   - ctx context.Context
//   - dto *model.GetPresignURLDto
func (_e *MockService_Expecter) GetFilePresignURL(ctx any, dto any) *MockService_GetFilePresignURL_Call {
	return &MockService_GetFilePresignURL_Call{Call: _e.mock.On("GetFilePresignURL", ctx, dto)}
}

func (_c *MockService_GetFilePresignURL_Call) Run(run func(ctx context.Context, dto *model.GetPresignURLDto)) *MockService_GetFilePresignURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model.GetPresignURLDto
		if args[1] != nil {
			arg1 = args[1].(*model.GetPresignURLDto)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_GetFilePresignURL_Call) Return(presignDto model.PresignDto, err error) *MockService_GetFilePresignURL_Call {
	_c.Call.Return(presignDto, err)
	return _c
}

func (_c *MockService_GetFilePresignURL_Call) RunAndReturn(run func(ctx context.Context, dto *model.GetPresignURLDto) (model.PresignDto, error)) *MockService_GetFilePresignURL_Call {
	_c.Call.Return(run)
	return _c
}

// ListFileTree provides a mock function for the type MockService
func (_mock *MockService) ListFileTree(ctx context.Context, query model.FileTreeQueryDto) (model.FileTreeResultDto, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for ListFileTree")
	}

	var r0 model.FileTreeResultDto
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.FileTreeQueryDto) (model.FileTreeResultDto, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.FileTreeQueryDto) model.FileTreeResultDto); ok {
		r0 = returnFunc(ctx, query)
	} else {
		r0 = ret.Get(0).(model.FileTreeResultDto)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.FileTreeQueryDto) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListFileTree_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFileTree'
type MockService_ListFileTree_Call struct {
	*mock.Call
}

// ListFileTree is a helper method to define mock.On call
//   - ctx context.Context
//   - query model.FileTreeQueryDto
func (_e *MockService_Expecter) ListFileTree(ctx any, query any) *MockService_ListFileTree_Call {
	return &MockService_ListFileTree_Call{Call: _e.mock.On("ListFileTree", ctx, query)}
}

func (_c *MockService_ListFileTree_Call) Run(run func(ctx context.Context, query model.FileTreeQueryDto)) *MockService_ListFileTree_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.FileTreeQueryDto
		if args[1] != nil {
			arg1 = args[1].(model.FileTreeQueryDto)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_ListFileTree_Call) Return(fileTreeResultDto model.FileTreeResultDto, err error) *MockService_ListFileTree_Call {
	_c.Call.Return(fileTreeResultDto, err)
	return _c
}

func (_c *MockService_ListFileTree_Call) RunAndReturn(run func(ctx context.Context, query model.FileTreeQueryDto) (model.FileTreeResultDto, error)) *MockService_ListFileTree_Call {
	_c.Call.Return(run)
	return _c
}

// ListFiles provides a mock function for the type MockService
func (_mock *MockService) ListFiles(ctx context.Context, query model.FileListQueryDto) (model.FileListResultDto, error) {
	ret := _mock.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for ListFiles")
	}

	var r0 model.FileListResultDto
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.FileListQueryDto) (model.FileListResultDto, error)); ok {
		return returnFunc(ctx, query)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.FileListQueryDto) model.FileListResultDto); ok {
		r0 = returnFunc(ctx, query)
	} else {
		r0 = ret.Get(0).(model.FileListResultDto)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.FileListQueryDto) error); ok {
		r1 = returnFunc(ctx, query)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFiles'
type MockService_ListFiles_Call struct {
	*mock.Call
}

// ListFiles is a helper method to define mock.On call
//   - ctx context.Context
//   - query model.FileListQueryDto
func (_e *MockService_Expecter) ListFiles(ctx any, query any) *MockService_ListFiles_Call {
	return &MockService_ListFiles_Call{Call: _e.mock.On("ListFiles", ctx, query)}
}

func (_c *MockService_ListFiles_Call) Run(run func(ctx context.Context, query model.FileListQueryDto)) *MockService_ListFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.FileListQueryDto
		if args[1] != nil {
			arg1 = args[1].(model.FileListQueryDto)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_ListFiles_Call) Return(fileListResultDto model.FileListResultDto, err error) *MockService_ListFiles_Call {
	_c.Call.Return(fileListResultDto, err)
	return _c
}

func (_c *MockService_ListFiles_Call) RunAndReturn(run func(ctx context.Context, query model.FileListQueryDto) (model.FileListResultDto, error)) *MockService_ListFiles_Call {
	_c.Call.Return(run)
	return _c
}

// StreamFileByID provides a mock function for the type MockService
func (_mock *MockService) StreamFileByID(ctx *gin.Context, id string) {
	_mock.Called(ctx, id)
	return
}

// MockService_StreamFileByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StreamFileByID'
type MockService_StreamFileByID_Call struct {
	*mock.Call
}

// StreamFileByID is a helper method to define mock.On call
//   - ctx *gin.Context
//   - id string
func (_e *MockService_Expecter) StreamFileByID(ctx any, id any) *MockService_StreamFileByID_Call {
	return &MockService_StreamFileByID_Call{Call: _e.mock.On("StreamFileByID", ctx, id)}
}

func (_c *MockService_StreamFileByID_Call) Run(run func(ctx *gin.Context, id string)) *MockService_StreamFileByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_StreamFileByID_Call) Return() *MockService_StreamFileByID_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_StreamFileByID_Call) RunAndReturn(run func(ctx *gin.Context, id string)) *MockService_StreamFileByID_Call {
	_c.Run(run)
	return _c
}

// StreamFileByPath provides a mock function for the type MockService
func (_mock *MockService) StreamFileByPath(ctx *gin.Context, query model.FilePathStreamQueryDto) {
	_mock.Called(ctx, query)
	return
}

// MockService_StreamFileByPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StreamFileByPath'
type MockService_StreamFileByPath_Call struct {
	*mock.Call
}

// StreamFileByPath is a helper method to define mock.On call
//   - ctx *gin.Context
//   - query model.FilePathStreamQueryDto
func (_e *MockService_Expecter) StreamFileByPath(ctx any, query any) *MockService_StreamFileByPath_Call {
	return &MockService_StreamFileByPath_Call{Call: _e.mock.On("StreamFileByPath", ctx, query)}
}

func (_c *MockService_StreamFileByPath_Call) Run(run func(ctx *gin.Context, query model.FilePathStreamQueryDto)) *MockService_StreamFileByPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		var arg1 model.FilePathStreamQueryDto
		if args[1] != nil {
			arg1 = args[1].(model.FilePathStreamQueryDto)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_StreamFileByPath_Call) Return() *MockService_StreamFileByPath_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_StreamFileByPath_Call) RunAndReturn(run func(ctx *gin.Context, query model.FilePathStreamQueryDto)) *MockService_StreamFileByPath_Call {
	_c.Run(run)
	return _c
}

// UpdateFileMeta provides a mock function for the type MockService
func (_mock *MockService) UpdateFileMeta(ctx context.Context, id string, dto model.UpdateFileMetaDto) (model.FileDto, error) {
	ret := _mock.Called(ctx, id, dto)

	if len(ret) == 0 {
		panic("no return value specified for UpdateFileMeta")
	}

	var r0 model.FileDto
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.UpdateFileMetaDto) (model.FileDto, error)); ok {
		return returnFunc(ctx, id, dto)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, model.UpdateFileMetaDto) model.FileDto); ok {
		r0 = returnFunc(ctx, id, dto)
	} else {
		r0 = ret.Get(0).(model.FileDto)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, model.UpdateFileMetaDto) error); ok {
		r1 = returnFunc(ctx, id, dto)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_UpdateFileMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateFileMeta'
type MockService_UpdateFileMeta_Call struct {
	*mock.Call
}

// UpdateFileMeta is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - dto model.UpdateFileMetaDto
func (_e *MockService_Expecter) UpdateFileMeta(ctx any, id any, dto any) *MockService_UpdateFileMeta_Call {
	return &MockService_UpdateFileMeta_Call{Call: _e.mock.On("UpdateFileMeta", ctx, id, dto)}
}

func (_c *MockService_UpdateFileMeta_Call) Run(run func(ctx context.Context, id string, dto model.UpdateFileMetaDto)) *MockService_UpdateFileMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 model.UpdateFileMetaDto
		if args[2] != nil {
			arg2 = args[2].(model.UpdateFileMetaDto)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_UpdateFileMeta_Call) Return(fileDto model.FileDto, err error) *MockService_UpdateFileMeta_Call {
	_c.Call.Return(fileDto, err)
	return _c
}

func (_c *MockService_UpdateFileMeta_Call) RunAndReturn(run func(ctx context.Context, id string, dto model.UpdateFileMetaDto) (model.FileDto, error)) *MockService_UpdateFileMeta_Call {
	_c.Call.Return(run)
	return _c
}

// UploadFile provides a mock function for the type MockService
func (_mock *MockService) UploadFile(ctx context.Context, file *multipart.FileHeader, category storage.Category, storageType storage.StorageType) (model.FileDto, error) {
	ret := _mock.Called(ctx, file, category, storageType)

	if len(ret) == 0 {
		panic("no return value specified for UploadFile")
	}

	var r0 model.FileDto
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *multipart.FileHeader, storage.Category, storage.StorageType) (model.FileDto, error)); ok {
		return returnFunc(ctx, file, category, storageType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *multipart.FileHeader, storage.Category, storage.StorageType) model.FileDto); ok {
		r0 = returnFunc(ctx, file, category, storageType)
	} else {
		r0 = ret.Get(0).(model.FileDto)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *multipart.FileHeader, storage.Category, storage.StorageType) error); ok {
		r1 = returnFunc(ctx, file, category, storageType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_UploadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadFile'
type MockService_UploadFile_Call struct {
	*mock.Call
}

// UploadFile is a helper method to define mock.On call
//   - ctx context.Context
//   - file *multipart.FileHeader
//   - category storage.Category
//   - storageType storage.StorageType
func (_e *MockService_Expecter) UploadFile(ctx any, file any, category any, storageType any) *MockService_UploadFile_Call {
	return &MockService_UploadFile_Call{Call: _e.mock.On("UploadFile", ctx, file, category, storageType)}
}

func (_c *MockService_UploadFile_Call) Run(run func(ctx context.Context, file *multipart.FileHeader, category storage.Category, storageType storage.StorageType)) *MockService_UploadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *multipart.FileHeader
		if args[1] != nil {
			arg1 = args[1].(*multipart.FileHeader)
		}
		var arg2 storage.Category
		if args[2] != nil {
			arg2 = args[2].(storage.Category)
		}
		var arg3 storage.StorageType
		if args[3] != nil {
			arg3 = args[3].(storage.StorageType)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_UploadFile_Call) Return(fileDto model.FileDto, err error) *MockService_UploadFile_Call {
	_c.Call.Return(fileDto, err)
	return _c
}

func (_c *MockService_UploadFile_Call) RunAndReturn(run func(ctx context.Context, file *multipart.FileHeader, category storage.Category, storageType storage.StorageType) (model.FileDto, error)) *MockService_UploadFile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCommonRepository creates a new instance of MockCommonRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommonRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommonRepository {
	mock := &MockCommonRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommonRepository is an autogenerated mock type for the CommonRepository type
type MockCommonRepository struct {
	mock.Mock
}

type MockCommonRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommonRepository) EXPECT() *MockCommonRepository_Expecter {
	return &MockCommonRepository_Expecter{mock: &_m.Mock}
}

// GetUserByUserId provides a mock function for the type MockCommonRepository
func (_mock *MockCommonRepository) GetUserByUserId(ctx context.Context, id string) (model0.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUserId")
	}

	var r0 model0.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (model0.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) model0.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(model0.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommonRepository_GetUserByUserId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByUserId'
type MockCommonRepository_GetUserByUserId_Call struct {
	*mock.Call
}

// GetUserByUserId is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockCommonRepository_Expecter) GetUserByUserId(ctx any, id any) *MockCommonRepository_GetUserByUserId_Call {
	return &MockCommonRepository_GetUserByUserId_Call{Call: _e.mock.On("GetUserByUserId", ctx, id)}
}

func (_c *MockCommonRepository_GetUserByUserId_Call) Run(run func(ctx context.Context, id string)) *MockCommonRepository_GetUserByUserId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommonRepository_GetUserByUserId_Call) Return(user model0.User, err error) *MockCommonRepository_GetUserByUserId_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockCommonRepository_GetUserByUserId_Call) RunAndReturn(run func(ctx context.Context, id string) (model0.User, error)) *MockCommonRepository_GetUserByUserId_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFileRepository creates a new instance of MockFileRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileRepository {
	mock := &MockFileRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileRepository is an autogenerated mock type for the FileRepository type
type MockFileRepository struct {
	mock.Mock
}

type MockFileRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileRepository) EXPECT() *MockFileRepository_Expecter {
	return &MockFileRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) Create(ctx context.Context, file *model1.File) error {
	ret := _mock.Called(ctx, file)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model1.File) error); ok {
		r0 = returnFunc(ctx, file)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockFileRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - file *model1.File
func (_e *MockFileRepository_Expecter) Create(ctx any, file any) *MockFileRepository_Create_Call {
	return &MockFileRepository_Create_Call{Call: _e.mock.On("Create", ctx, file)}
}

func (_c *MockFileRepository_Create_Call) Run(run func(ctx context.Context, file *model1.File)) *MockFileRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model1.File
		if args[1] != nil {
			arg1 = args[1].(*model1.File)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileRepository_Create_Call) Return(err error) *MockFileRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileRepository_Create_Call) RunAndReturn(run func(ctx context.Context, file *model1.File) error) *MockFileRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTemp provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) CreateTemp(ctx context.Context, temp *model1.TempFile) error {
	ret := _mock.Called(ctx, temp)

	if len(ret) == 0 {
		panic("no return value specified for CreateTemp")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *model1.TempFile) error); ok {
		r0 = returnFunc(ctx, temp)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileRepository_CreateTemp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTemp'
type MockFileRepository_CreateTemp_Call struct {
	*mock.Call
}

// CreateTemp is a helper method to define mock.On call
//   - ctx context.Context
//   - temp *model1.TempFile
func (_e *MockFileRepository_Expecter) CreateTemp(ctx any, temp any) *MockFileRepository_CreateTemp_Call {
	return &MockFileRepository_CreateTemp_Call{Call: _e.mock.On("CreateTemp", ctx, temp)}
}

func (_c *MockFileRepository_CreateTemp_Call) Run(run func(ctx context.Context, temp *model1.TempFile)) *MockFileRepository_CreateTemp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *model1.TempFile
		if args[1] != nil {
			arg1 = args[1].(*model1.TempFile)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileRepository_CreateTemp_Call) Return(err error) *MockFileRepository_CreateTemp_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileRepository_CreateTemp_Call) RunAndReturn(run func(ctx context.Context, temp *model1.TempFile) error) *MockFileRepository_CreateTemp_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockFileRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockFileRepository_Expecter) Delete(ctx any, id any) *MockFileRepository_Delete_Call {
	return &MockFileRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockFileRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockFileRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileRepository_Delete_Call) Return(err error) *MockFileRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockFileRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByRoute provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) DeleteByRoute(ctx context.Context, storageType string, provider string, bucket string, key string) error {
	ret := _mock.Called(ctx, storageType, provider, bucket, key)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByRoute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, storageType, provider, bucket, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileRepository_DeleteByRoute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByRoute'
type MockFileRepository_DeleteByRoute_Call struct {
	*mock.Call
}

// DeleteByRoute is a helper method to define mock.On call
//   - ctx context.Context
//   - storageType string
//   - provider string
//   - bucket string
//   - key string
func (_e *MockFileRepository_Expecter) DeleteByRoute(ctx any, storageType any, provider any, bucket any, key any) *MockFileRepository_DeleteByRoute_Call {
	return &MockFileRepository_DeleteByRoute_Call{Call: _e.mock.On("DeleteByRoute", ctx, storageType, provider, bucket, key)}
}

func (_c *MockFileRepository_DeleteByRoute_Call) Run(run func(ctx context.Context, storageType string, provider string, bucket string, key string)) *MockFileRepository_DeleteByRoute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockFileRepository_DeleteByRoute_Call) Return(err error) *MockFileRepository_DeleteByRoute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileRepository_DeleteByRoute_Call) RunAndReturn(run func(ctx context.Context, storageType string, provider string, bucket string, key string) error) *MockFileRepository_DeleteByRoute_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTempByFileID provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) DeleteTempByFileID(ctx context.Context, fileID string) error {
	ret := _mock.Called(ctx, fileID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTempByFileID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, fileID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileRepository_DeleteTempByFileID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTempByFileID'
type MockFileRepository_DeleteTempByFileID_Call struct {
	*mock.Call
}

// DeleteTempByFileID is a helper method to define mock.On call
//   - ctx context.Context
//   - fileID string
func (_e *MockFileRepository_Expecter) DeleteTempByFileID(ctx any, fileID any) *MockFileRepository_DeleteTempByFileID_Call {
	return &MockFileRepository_DeleteTempByFileID_Call{Call: _e.mock.On("DeleteTempByFileID", ctx, fileID)}
}

func (_c *MockFileRepository_DeleteTempByFileID_Call) Run(run func(ctx context.Context, fileID string)) *MockFileRepository_DeleteTempByFileID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileRepository_DeleteTempByFileID_Call) Return(err error) *MockFileRepository_DeleteTempByFileID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileRepository_DeleteTempByFileID_Call) RunAndReturn(run func(ctx context.Context, fileID string) error) *MockFileRepository_DeleteTempByFileID_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTempByID provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) DeleteTempByID(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTempByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFileRepository_DeleteTempByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTempByID'
type MockFileRepository_DeleteTempByID_Call struct {
	*mock.Call
}

// DeleteTempByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockFileRepository_Expecter) DeleteTempByID(ctx any, id any) *MockFileRepository_DeleteTempByID_Call {
	return &MockFileRepository_DeleteTempByID_Call{Call: _e.mock.On("DeleteTempByID", ctx, id)}
}

func (_c *MockFileRepository_DeleteTempByID_Call) Run(run func(ctx context.Context, id string)) *MockFileRepository_DeleteTempByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileRepository_DeleteTempByID_Call) Return(err error) *MockFileRepository_DeleteTempByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFileRepository_DeleteTempByID_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockFileRepository_DeleteTempByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) GetByID(ctx context.Context, id string) (*model1.File, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model1.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model1.File, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model1.File); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model1.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockFileRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockFileRepository_Expecter) GetByID(ctx any, id any) *MockFileRepository_GetByID_Call {
	return &MockFileRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockFileRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockFileRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileRepository_GetByID_Call) Return(file *model1.File, err error) *MockFileRepository_GetByID_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockFileRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*model1.File, error)) *MockFileRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByKey provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) GetByKey(ctx context.Context, key string) (*model1.File, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetByKey")
	}

	var r0 *model1.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*model1.File, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *model1.File); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model1.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileRepository_GetByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByKey'
type MockFileRepository_GetByKey_Call struct {
	*mock.Call
}

// GetByKey is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockFileRepository_Expecter) GetByKey(ctx any, key any) *MockFileRepository_GetByKey_Call {
	return &MockFileRepository_GetByKey_Call{Call: _e.mock.On("GetByKey", ctx, key)}
}

func (_c *MockFileRepository_GetByKey_Call) Run(run func(ctx context.Context, key string)) *MockFileRepository_GetByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileRepository_GetByKey_Call) Return(file *model1.File, err error) *MockFileRepository_GetByKey_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockFileRepository_GetByKey_Call) RunAndReturn(run func(ctx context.Context, key string) (*model1.File, error)) *MockFileRepository_GetByKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetByRoute provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) GetByRoute(ctx context.Context, storageType string, provider string, bucket string, key string) (*model1.File, error) {
	ret := _mock.Called(ctx, storageType, provider, bucket, key)

	if len(ret) == 0 {
		panic("no return value specified for GetByRoute")
	}

	var r0 *model1.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*model1.File, error)); ok {
		return returnFunc(ctx, storageType, provider, bucket, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) *model1.File); ok {
		r0 = returnFunc(ctx, storageType, provider, bucket, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model1.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, storageType, provider, bucket, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileRepository_GetByRoute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByRoute'
type MockFileRepository_GetByRoute_Call struct {
	*mock.Call
}

// GetByRoute is a helper method to define mock.On call
//   - ctx context.Context
//   - storageType string
//   - provider string
//   - bucket string
//   - key string
func (_e *MockFileRepository_Expecter) GetByRoute(ctx any, storageType any, provider any, bucket any, key any) *MockFileRepository_GetByRoute_Call {
	return &MockFileRepository_GetByRoute_Call{Call: _e.mock.On("GetByRoute", ctx, storageType, provider, bucket, key)}
}

func (_c *MockFileRepository_GetByRoute_Call) Run(run func(ctx context.Context, storageType string, provider string, bucket string, key string)) *MockFileRepository_GetByRoute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockFileRepository_GetByRoute_Call) Return(file *model1.File, err error) *MockFileRepository_GetByRoute_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockFileRepository_GetByRoute_Call) RunAndReturn(run func(ctx context.Context, storageType string, provider string, bucket string, key string) (*model1.File, error)) *MockFileRepository_GetByRoute_Call {
	_c.Call.Return(run)
	return _c
}

// ListByStorageTypeAndKeys provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) ListByStorageTypeAndKeys(ctx context.Context, storageType string, keys []string) ([]model1.File, error) {
	ret := _mock.Called(ctx, storageType, keys)

	if len(ret) == 0 {
		panic("no return value specified for ListByStorageTypeAndKeys")
	}

	var r0 []model1.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) ([]model1.File, error)); ok {
		return returnFunc(ctx, storageType, keys)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) []model1.File); ok {
		r0 = returnFunc(ctx, storageType, keys)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model1.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = returnFunc(ctx, storageType, keys)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileRepository_ListByStorageTypeAndKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByStorageTypeAndKeys'
type MockFileRepository_ListByStorageTypeAndKeys_Call struct {
	*mock.Call
}

// ListByStorageTypeAndKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - storageType string
//   - keys []string
func (_e *MockFileRepository_Expecter) ListByStorageTypeAndKeys(ctx any, storageType any, keys any) *MockFileRepository_ListByStorageTypeAndKeys_Call {
	return &MockFileRepository_ListByStorageTypeAndKeys_Call{Call: _e.mock.On("ListByStorageTypeAndKeys", ctx, storageType, keys)}
}

func (_c *MockFileRepository_ListByStorageTypeAndKeys_Call) Run(run func(ctx context.Context, storageType string, keys []string)) *MockFileRepository_ListByStorageTypeAndKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFileRepository_ListByStorageTypeAndKeys_Call) Return(files []model1.File, err error) *MockFileRepository_ListByStorageTypeAndKeys_Call {
	_c.Call.Return(files, err)
	return _c
}

func (_c *MockFileRepository_ListByStorageTypeAndKeys_Call) RunAndReturn(run func(ctx context.Context, storageType string, keys []string) ([]model1.File, error)) *MockFileRepository_ListByStorageTypeAndKeys_Call {
	_c.Call.Return(run)
	return _c
}

// ListByStorageTypeAndSearch provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) ListByStorageTypeAndSearch(ctx context.Context, storageType string, search string, page int, pageSize int) ([]model1.File, int64, error) {
	ret := _mock.Called(ctx, storageType, search, page, pageSize)

	if len(ret) == 0 {
		panic("no return value specified for ListByStorageTypeAndSearch")
	}

	var r0 []model1.File
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, int) ([]model1.File, int64, error)); ok {
		return returnFunc(ctx, storageType, search, page, pageSize)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int, int) []model1.File); ok {
		r0 = returnFunc(ctx, storageType, search, page, pageSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model1.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int, int) int64); ok {
		r1 = returnFunc(ctx, storageType, search, page, pageSize)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, int, int) error); ok {
		r2 = returnFunc(ctx, storageType, search, page, pageSize)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockFileRepository_ListByStorageTypeAndSearch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByStorageTypeAndSearch'
type MockFileRepository_ListByStorageTypeAndSearch_Call struct {
	*mock.Call
}

// ListByStorageTypeAndSearch is a helper method to define mock.On call
//   - ctx context.Context
//   - storageType string
//   - search string
//   - page int
//   - pageSize int
func (_e *MockFileRepository_Expecter) ListByStorageTypeAndSearch(ctx any, storageType any, search any, page any, pageSize any) *MockFileRepository_ListByStorageTypeAndSearch_Call {
	return &MockFileRepository_ListByStorageTypeAndSearch_Call{Call: _e.mock.On("ListByStorageTypeAndSearch", ctx, storageType, search, page, pageSize)}
}

func (_c *MockFileRepository_ListByStorageTypeAndSearch_Call) Run(run func(ctx context.Context, storageType string, search string, page int, pageSize int)) *MockFileRepository_ListByStorageTypeAndSearch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockFileRepository_ListByStorageTypeAndSearch_Call) Return(files []model1.File, n int64, err error) *MockFileRepository_ListByStorageTypeAndSearch_Call {
	_c.Call.Return(files, n, err)
	return _c
}

func (_c *MockFileRepository_ListByStorageTypeAndSearch_Call) RunAndReturn(run func(ctx context.Context, storageType string, search string, page int, pageSize int) ([]model1.File, int64, error)) *MockFileRepository_ListByStorageTypeAndSearch_Call {
	_c.Call.Return(run)
	return _c
}

// ListByStorageTypeAndURLs provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) ListByStorageTypeAndURLs(ctx context.Context, storageType string, urls []string) ([]model1.File, error) {
	ret := _mock.Called(ctx, storageType, urls)

	if len(ret) == 0 {
		panic("no return value specified for ListByStorageTypeAndURLs")
	}

	var r0 []model1.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) ([]model1.File, error)); ok {
		return returnFunc(ctx, storageType, urls)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string) []model1.File); ok {
		r0 = returnFunc(ctx, storageType, urls)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model1.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = returnFunc(ctx, storageType, urls)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileRepository_ListByStorageTypeAndURLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByStorageTypeAndURLs'
type MockFileRepository_ListByStorageTypeAndURLs_Call struct {
	*mock.Call
}

// ListByStorageTypeAndURLs is a helper method to define mock.On call
//   - ctx context.Context
//   - storageType string
//   - urls []string
func (_e *MockFileRepository_Expecter) ListByStorageTypeAndURLs(ctx any, storageType any, urls any) *MockFileRepository_ListByStorageTypeAndURLs_Call {
	return &MockFileRepository_ListByStorageTypeAndURLs_Call{Call: _e.mock.On("ListByStorageTypeAndURLs", ctx, storageType, urls)}
}

func (_c *MockFileRepository_ListByStorageTypeAndURLs_Call) Run(run func(ctx context.Context, storageType string, urls []string)) *MockFileRepository_ListByStorageTypeAndURLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFileRepository_ListByStorageTypeAndURLs_Call) Return(files []model1.File, err error) *MockFileRepository_ListByStorageTypeAndURLs_Call {
	_c.Call.Return(files, err)
	return _c
}

func (_c *MockFileRepository_ListByStorageTypeAndURLs_Call) RunAndReturn(run func(ctx context.Context, storageType string, urls []string) ([]model1.File, error)) *MockFileRepository_ListByStorageTypeAndURLs_Call {
	_c.Call.Return(run)
	return _c
}

// ListExpiredTemps provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) ListExpiredTemps(ctx context.Context, before int64) ([]model1.TempFile, error) {
	ret := _mock.Called(ctx, before)

	if len(ret) == 0 {
		panic("no return value specified for ListExpiredTemps")
	}

	var r0 []model1.TempFile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) ([]model1.TempFile, error)); ok {
		return returnFunc(ctx, before)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) []model1.TempFile); ok {
		r0 = returnFunc(ctx, before)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model1.TempFile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, before)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileRepository_ListExpiredTemps_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListExpiredTemps'
type MockFileRepository_ListExpiredTemps_Call struct {
	*mock.Call
}

// ListExpiredTemps is a helper method to define mock.On call
//   - ctx context.Context
//   - before int64
func (_e *MockFileRepository_Expecter) ListExpiredTemps(ctx any, before any) *MockFileRepository_ListExpiredTemps_Call {
	return &MockFileRepository_ListExpiredTemps_Call{Call: _e.mock.On("ListExpiredTemps", ctx, before)}
}

func (_c *MockFileRepository_ListExpiredTemps_Call) Run(run func(ctx context.Context, before int64)) *MockFileRepository_ListExpiredTemps_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileRepository_ListExpiredTemps_Call) Return(tempFiles []model1.TempFile, err error) *MockFileRepository_ListExpiredTemps_Call {
	_c.Call.Return(tempFiles, err)
	return _c
}

func (_c *MockFileRepository_ListExpiredTemps_Call) RunAndReturn(run func(ctx context.Context, before int64) ([]model1.TempFile, error)) *MockFileRepository_ListExpiredTemps_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMetaByID provides a mock function for the type MockFileRepository
func (_mock *MockFileRepository) UpdateMetaByID(ctx context.Context, id string, size int64, width *int, height *int, contentType *string) (*model1.File, error) {
	ret := _mock.Called(ctx, id, size, width, height, contentType)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMetaByID")
	}

	var r0 *model1.File
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, *int, *int, *string) (*model1.File, error)); ok {
		return returnFunc(ctx, id, size, width, height, contentType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64, *int, *int, *string) *model1.File); ok {
		r0 = returnFunc(ctx, id, size, width, height, contentType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model1.File)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64, *int, *int, *string) error); ok {
		r1 = returnFunc(ctx, id, size, width, height, contentType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileRepository_UpdateMetaByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMetaByID'
type MockFileRepository_UpdateMetaByID_Call struct {
	*mock.Call
}

// UpdateMetaByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - size int64
//   - width *int
//   - height *int
//   - contentType *string
func (_e *MockFileRepository_Expecter) UpdateMetaByID(ctx any, id any, size any, width any, height any, contentType any) *MockFileRepository_UpdateMetaByID_Call {
	return &MockFileRepository_UpdateMetaByID_Call{Call: _e.mock.On("UpdateMetaByID", ctx, id, size, width, height, contentType)}
}

func (_c *MockFileRepository_UpdateMetaByID_Call) Run(run func(ctx context.Context, id string, size int64, width *int, height *int, contentType *string)) *MockFileRepository_UpdateMetaByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 *int
		if args[3] != nil {
			arg3 = args[3].(*int)
		}
		var arg4 *int
		if args[4] != nil {
			arg4 = args[4].(*int)
		}
		var arg5 *string
		if args[5] != nil {
			arg5 = args[5].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockFileRepository_UpdateMetaByID_Call) Return(file *model1.File, err error) *MockFileRepository_UpdateMetaByID_Call {
	_c.Call.Return(file, err)
	return _c
}

func (_c *MockFileRepository_UpdateMetaByID_Call) RunAndReturn(run func(ctx context.Context, id string, size int64, width *int, height *int, contentType *string) (*model1.File, error)) *MockFileRepository_UpdateMetaByID_Call {
	_c.Call.Return(run)
	return _c
}
